Instrumented code to measure execution time of the various layers
json-api-dotnet/JsonApiDotNetCore pull request #1023
Opened 2021-06-28 17:30 UTC by bart-degreed

Example output:

```
JsonApiDotNetCoreExample.Startups.Startup: Warning: Measurement results for application startup:
Configure JSON:API (startup): 0:00:00:01.0794185 - 100.00 %
Initialize JSON:API (startup): 0:00:00:00.0067697 - 100.00 %

JsonApiDotNetCore.Middleware.JsonApiMiddleware: Warning: Measurement results for http://localhost:14140/api/v1/todoItems?include=owner,assignee,tags:
JSON:API middleware: 0:00:00:00.0001305 - 0.70 %
  Other middleware: 0:00:00:00.0012512 - 6.70 %
    Parse query string: 0:00:00:00.0001354 - 0.73 %
    Service - Get resources: 0:00:00:00.0008204 - 4.39 %
      Repository - Count resources: 0:00:00:00.0000075 - 0.04 %
        Build EF Core query: 0:00:00:00.0002538 - 1.36 %
        Execute SQL (count): 0:00:00:00.0075689 - 40.55 %
      Repository - Get resource(s): 0:00:00:00.0000045 - 0.02 %
        Build EF Core query: 0:00:00:00.0010331 - 5.53 %
        Execute SQL (data): 0:00:00:00.0048114 - 25.77 %
    Serialize response body: 0:00:00:00.0013506 - 7.24 %
      Serializer.Build (list): 0:00:00:00.0009081 - 4.86 %
      Newtonsoft.Serialize: 0:00:00:00.0003920 - 2.10 %
```

2021-08-10 13:22 UTC, bart-degreed commented
Reverted Resharper/Rider update due to hanging cibuild. Tracked at https://youtrack.jetbrains.com/issue/RSRP-481371#focus=Comments-27-5106579.0-0.

2021-08-13 09:13 UTC, maurei commented on src/JsonApiDotNetCore/Diagnostics/CascadingCodeTimer.cs
> +                // To get the CPU core more exclusively, we must prevent that other threads can use this CPU core. We set our process and thread priority to achieve this.
We set our process ~and thread~ priority to achieve this.

2021-08-13 10:19 UTC, maurei commented on src/JsonApiDotNetCore/Diagnostics/CascadingCodeTimer.cs
> +            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) || RuntimeInformation.IsOSPlatform(OSPlatform.OSX))

2021-08-13 10:34 UTC, maurei requested changes
Added two comments earlier

2021-08-13 11:47 UTC, bart-degreed commented on src/JsonApiDotNetCore/Diagnostics/CascadingCodeTimer.cs
> +            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
While not failing on OSX, setting this does not actually help. See https://github.com/dotnet/runtime/blob/defa26b9e1159f1a2a3470c52084410edff982b6/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs#L931.

2021-08-13 11:48 UTC, bart-degreed commented on src/JsonApiDotNetCore/Diagnostics/CascadingCodeTimer.cs
> +                // To get the CPU core more exclusively, we must prevent that other threads can use this CPU core. We set our process and thread priority to achieve this.
Updated.

2021-08-13 11:54 UTC, maurei approved these changes

2021-08-13 12:25 UTC, merged