Native many to many
json-api-dotnet/JsonApiDotNetCore pull request #1037
Opened 2021-07-30 14:38 UTC by bart-degreed

Fixes #935.

#### QUALITY CHECKLIST
- [x] Changes implemented in code
- [x] Complies with our [contributing guidelines](./.github/CONTRIBUTING.md)
- [x] Adapted tests
- [x] Documentation updated
- [ ] N/A: Created issue to update [Templates](https://github.com/json-api-dotnet/Templates/issues/new): {ISSUE_NUMBER}

2021-08-02 13:03 UTC, maurei requested changes

2021-08-02 13:46 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +                if (entityType is not EntityType { IsImplicitlyCreatedJoinEntityType: true })
This is not the same. I'm defining the _exceptional_ case here, which we may need to widen in the future. The exceptional case suppresses a logged warning. I'd rather see users create a bug when the warning appears where it shouldn't, as opposed to not emitting a warning in cases that we should.

2021-08-02 13:47 UTC, bart-degreed commented on src/JsonApiDotNetCore/Repositories/EntityFrameworkCoreRepository.cs
> +            if (relationship is not HasManyAttribute { IsManyToMany: true })
The same reasoning applies as before: a many-to-many relationship cannot be a _required_ relationship, therefore the check can be skipped in that case.

2021-08-02 13:48 UTC, bart-degreed commented on src/JsonApiDotNetCore/Resources/Annotations/HasManyAttribute.cs
> +        public bool IsManyToMany => _lazyIsManyToMany.Value;
See response below.

2021-08-02 13:54 UTC, bart-degreed commented on src/JsonApiDotNetCore/Resources/Annotations/HasOneAttribute.cs
> +        public bool IsOneToOne => _lazyIsOneToOne.Value;
IsOneToOne and IsManyToMany are facts about a JSON:API relationship, not EF Core-specific. They have value in themselves, but I'll make them internal because there is no need to expose that information. The reason they are defined in the relationship attributes is for caching: it removes the need to re-evaluate this for each request, while it never changes after the resource graph has been built at startup.

2021-08-02 15:07 UTC, bart-degreed commented on src/JsonApiDotNetCore/Queries/Internal/QueryableBuilding/QueryClauseBuilder.cs
> +                .Select(field => field is RelationshipAttribute relationship ? relationship.Property.Name : field.Property.Name).ToArray();
This conditional can be removed. I'll take that in my next PR.

2021-08-03 08:23 UTC, maurei approved these changes

2021-08-03 09:25 UTC, merged