Feature/allow leading space
json-api-dotnet/JsonApiDotNetCore pull request #1041
Opened 2021-08-18 10:57 UTC by sgryphon

Closes #1040

#### QUALITY CHECKLIST
- [X] Changes implemented in code
- [ ] Complies with our [contributing guidelines](./.github/CONTRIBUTING.md)
- [X] Adapted tests
- [ ] Documentation updated
- [ ] Created issue to update [Templates](https://github.com/json-api-dotnet/Templates/issues/new): {ISSUE_NUMBER}

2021-08-19 12:18 UTC, maurei requested changes
Thanks for your input!  @bart-degreed is on vacation currently, I'd like to have him have a look at it too once he returns. But for the meanwhile I've left some comments for you to look into.

2021-08-19 12:18 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/UnitTests/QueryStringParameters/FilterParseTests.cs
> +        [InlineData("filter", "contains(name,' ')", null, "contains(name,' ')")]
These tests don't pass because `name` is not does exist on the blog resource. I suggest to use the following:

```c#
[InlineData("filter", "startsWith(title,'Brian ')", null, "startsWith(title,'Brian ')")]
[InlineData("filter", "endsWith(title,' O''Quote')", null, "endsWith(title,' O''Quote')")]
[InlineData("filter", "contains(title,' ')", null, "contains(title,' ')")]
```

2021-08-19 12:18 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/UnitTests/QueryStringParameters/LegacyFilterParseTests.cs
> +        [InlineData("filter", "expr:equals(caption,' ')", "equals(caption,' ')")]
Instead of this test, I think the following would be more useful:

```c#
[InlineData("filter[caption]", " ", "equals(caption,' ')")]
```

2021-08-19 12:18 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/UnitTests/QueryStringParameters/FilterParseTests.cs
> +        [InlineData("filter", "contains(name,' ')", null, "contains(name,' ')")]
Additionally, to hit the `unexpected whitespace` error in the adjusted code path, I would suggest to add the following test:

```c#
[InlineData("filter", "equals(title, )", "Unexpected whitespace.")]
```

2021-08-31 16:02 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/UnitTests/QueryStringParameters/FilterParseTests.cs
> +        [InlineData("filter", "contains(name,' ')", null, "contains(name,' ')")]
> These tests don't pass because `name` is not does exist on the blog resource. I suggest to use the following:
> 
> ```cs
> [InlineData("filter", "startsWith(title,'Brian ')", null, "startsWith(title,'Brian ')")]
> [InlineData("filter", "endsWith(title,' O''Quote')", null, "endsWith(title,' O''Quote')")]
> [InlineData("filter", "contains(title,' ')", null, "contains(title,' ')")]
> ```

Yes, this needs to use the `title` field. However, I'd keep the values as simple as possible, as in: " Some", "Some " and not intermix this with escaped quotes.

> Additionally, to hit the `unexpected whitespace` error in the adjusted code path, I would suggest to add the following test:
> 
> ```cs
> [InlineData("filter", "equals(title, )", "Unexpected whitespace.")]
> ```

Unexpected whitespace is already covered by an existing case:
```c#
[InlineData("filter", " ", "Unexpected whitespace.")]
```

2021-08-31 16:06 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/UnitTests/QueryStringParameters/LegacyFilterParseTests.cs
> +        [InlineData("filter", "expr:equals(caption,' ')", "equals(caption,' ')")]
Agreed. The "expr:" prefix executes the exact same code which is covered by FilterParseTests, so it can be left out here. The test that was removed in this PR:
```c#
[InlineData("filter[author]", " ", "Unexpected whitespace.")]
```
was an invalid test, because it is perfectly fine to use unescaped whitespace in legacy syntax.

2021-08-31 22:44 UTC, sgryphon commented on test/JsonApiDotNetCoreExampleTests/UnitTests/QueryStringParameters/FilterParseTests.cs
> +        [InlineData("filter", "contains(name,' ')", null, "contains(name,' ')")]
I ended up using owner.displayName, so it is a concrete example of why someone might want to search for a leading space (e.g. you want a particular last name). Although I guess "containing a space" would work for titles as well. Yeah, don't want to mix up with quotes. 

Happy to still change to Some, but I think it is less meaningful.

I ended up adding the extra unexpected whitespace test, as it is not at the start of the whole expression, but the start of one token.

2021-08-31 22:45 UTC, sgryphon commented on test/JsonApiDotNetCoreExampleTests/UnitTests/QueryStringParameters/LegacyFilterParseTests.cs
> +        [InlineData("filter", "expr:equals(caption,' ')", "equals(caption,' ')")]
Legacy test changed.

2021-09-01 08:19 UTC, bart-degreed approved these changes
Looks good to me. Thanks for your contribution!

2021-09-01 09:06 UTC, maurei approved these changes

2021-09-01 09:06 UTC, merged