Removing dependency on JsonApiDotNetCoreExample project in test projects
json-api-dotnet/JsonApiDotNetCore pull request #1068
Opened 2021-09-02 07:44 UTC by maurei

Closes #1031
 
 Also required for introducing a OpenAPI testing environment in #1047.

2021-09-02 12:56 UTC, bart-degreed requested changes

2021-09-02 12:56 UTC, bart-degreed commented on test/JsonApiDotNetCoreTests/JsonApiDotNetCoreTests.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.9" />
Please use placeholder from `Directory.Build.props` in the version of added Microsoft.EntityFrameworkCore.InMemory dependency.

2021-09-02 12:56 UTC, bart-degreed commented on test/JsonApiDotNetCoreTests/JsonApiDotNetCoreTests.csproj
> +    <RootNamespace>JsonApiDotNetCoreTests</RootNamespace>
Can most likely be removed.

2021-09-02 12:56 UTC, bart-degreed commented on test/TestBuildingBlocks/IntegrationTestContext.cs
> +    /// The EF Core database context, which can be defined in the test project.
~, which can be defined in the test project.~
, which can be defined in the test project or the API project.
(twice)

2021-09-02 12:56 UTC, bart-degreed commented on test/TestBuildingBlocks/IntegrationTestContext.cs
> +    [UsedImplicitly(ImplicitUseKindFlags.InstantiatedWithFixedConstructorSignature)]
~InstantiatedWithFixedConstructorSignature~ InstantiatedNoFixedConstructorSignature (see https://docs.couchbase.com/sdk-api/couchbase-net-client-2.0.1/html/912444C.htm)

2021-09-02 12:56 UTC, bart-degreed commented on test/UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
> +            services.AddDbContext<TestContext>(options => options.UseInMemoryDatabase("UnitTestDb"));
Please rename to `TestDbContext`

2021-09-02 12:56 UTC, bart-degreed commented on test/JsonApiDotNetCoreTests/IntegrationTests/ReadWrite/Updating/Resources/UpdateResourceTests.cs
> +            responseDocument.SingleData.Attributes["isImportant"].Should().Be(true);
Should be comparing against: `existingWorkItem.IsImportant`

2021-09-02 12:56 UTC, bart-degreed commented on test/JsonApiDotNetCoreTests/IntegrationTests/NonJsonApiControllers/NonJsonApiControllerTests.cs
> +            _testContext.UseController<NonJsonApiController>();
Existing convention is to use `testContext` in ctor instead of `_testContext`. This is slightly faster. But more importantly, it makes the order of field assignments irrelevant. Please adapt for consistency.

2021-09-02 12:56 UTC, bart-degreed commented on test/JsonApiDotNetCoreTests/IntegrationTests/NonJsonApiControllers/NonJsonApiControllers.cs
> +    public sealed class NonJsonApiControllers : DbContext
Rename to something less confusing, ie `NonJsonApiDbContext`.

2021-09-02 13:02 UTC, maurei commented on test/JsonApiDotNetCoreTests/JsonApiDotNetCoreTests.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.9" />
Processed.

2021-09-02 13:02 UTC, maurei commented on test/JsonApiDotNetCoreTests/JsonApiDotNetCoreTests.csproj
> +    <RootNamespace>JsonApiDotNetCoreTests</RootNamespace>
Processed.

2021-09-02 13:02 UTC, maurei commented on test/TestBuildingBlocks/IntegrationTestContext.cs
> +    /// The EF Core database context, which can be defined in the test project.
Processed.

2021-09-02 13:02 UTC, maurei commented on test/TestBuildingBlocks/IntegrationTestContext.cs
> +    [UsedImplicitly(ImplicitUseKindFlags.InstantiatedWithFixedConstructorSignature)]
Processed.

2021-09-02 13:02 UTC, maurei commented on test/UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
> +            services.AddDbContext<TestContext>(options => options.UseInMemoryDatabase("UnitTestDb"));
Processed.

2021-09-02 13:02 UTC, maurei commented on test/JsonApiDotNetCoreTests/IntegrationTests/ReadWrite/Updating/Resources/UpdateResourceTests.cs
> +            responseDocument.SingleData.Attributes["isImportant"].Should().Be(true);
Processed.

2021-09-02 13:02 UTC, maurei commented on test/JsonApiDotNetCoreTests/IntegrationTests/NonJsonApiControllers/NonJsonApiControllerTests.cs
> +            _testContext.UseController<NonJsonApiController>();
Processed.

2021-09-02 13:03 UTC, maurei commented on test/JsonApiDotNetCoreTests/IntegrationTests/NonJsonApiControllers/NonJsonApiControllers.cs
> +    public sealed class NonJsonApiControllers : DbContext
Processed.

2021-09-02 13:19 UTC, bart-degreed commented on test/UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
> +            services.AddDbContext<TestContext>(options => options.UseInMemoryDatabase("UnitTestDb"));
There's one more `TestContext` in ResourceGraphBuilderTests.cs, can you rename that one as well, while we're at it?

2021-09-02 13:36 UTC, maurei commented on test/UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
> +            services.AddDbContext<TestContext>(options => options.UseInMemoryDatabase("UnitTestDb"));
Done!

2021-09-03 08:01 UTC, bart-degreed commented on test/TestBuildingBlocks/appsettings.json
> +  }
The "JsonApiDotNetCoreExample" line in this file can be removed.

2021-09-03 10:12 UTC, maurei commented on test/TestBuildingBlocks/appsettings.json
> +  }
Processed

2021-09-03 14:20 UTC, bart-degreed approved these changes

2021-09-03 14:20 UTC, merged