Minimal Swashbuckle setup
json-api-dotnet/JsonApiDotNetCore pull request #1073
Opened 2021-09-06 10:58 UTC by maurei

- Introduces a very minimal `OpenApi` project in which the integration will live. It currently only contains the dependency on Swashbuckle and I've added a very minimal implementation of `IActionModelConvention` as to not have a project without any code.
- Introduces a full document test in a new test project in which a local document is checked against a document retrieved from a swagger endpoint.
- Closes #1047

2021-09-07 07:18 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTests.csproj
> +    </ItemGroup>
This produces the next error in Visual Studio:

![image](https://user-images.githubusercontent.com/54280078/132301278-cd014cda-7cef-458e-9d1c-e49d9a25e2d8.png)

Please apply the fix from our internal prototype at https://github.com/degreed/JsonApiCorePrototype/blob/master/src/Tests/JsonApiCorePrototype.Tests.csproj#L30-L35 to resolve.

2021-09-07 07:21 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTests.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
The spacing in the added .csproj files does not match configured layout settings. Please reformat them manually using your IDE.

2021-09-07 07:23 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/JsonApiDotNetCore.OpenApi.csproj
> +    </ItemGroup>
All other projects have project references before package references. Please adjust for consistency.

2021-09-07 07:26 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTests.csproj
> +        </None>
There is no file `xunit.runner.json` in this directory. Either add it or remove this.

Note this file is used to prevent running many test classes in parallel. We need it for integration tests, otherwise, too many PostgreSQL connections are opened at the same time and PostgreSQL starts to fail.

2021-09-07 07:45 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiDotNetCore.OpenApi.csproj
> +    </ItemGroup>
Adjusted

2021-09-07 08:56 UTC, bart-degreed requested changes

2021-09-07 08:56 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/JsonApiDotNetCore.OpenApi.csproj
> +    </ItemGroup>
I'm not seeing a reference to `Swashbuckle.AspNetCore.SwaggerUI` anywhere in the solution. I'd like ExampleProject to have that, including a reference to JADNC.OpenApi so we can demonstrate loading the documentation UI in a browser, aside from producing openapi.json. And we should have an OpenApi section in the docs that describes how to use it (ie. add NuGet, call `UseXXX` etc, basically what you'd put in ExampleProject).

2021-09-07 08:56 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/ServiceCollectionExtensions.cs
> +        public static void AddOpenApi(this IServiceCollection services, IMvcCoreBuilder builder, Action<SwaggerGenOptions> setupSwaggerGenAction)
`setupSwaggerGenAction` is declared as optional in `AddSwaggerGen`. Unless future PRs are going to depend on this or _not_ passing it is never going to work, we should probably make it optional too.

2021-09-07 08:56 UTC, bart-degreed commented on test/OpenApiTests/AirplanesController.cs
> +        public AirplanesController(IJsonApiOptions options, ILoggerFactory loggerFactory, IResourceService<Airplane, int> resourceService)
Should be: `IResourceService<Airplane>`

2021-09-07 08:56 UTC, bart-degreed commented on test/OpenApiTests/Flight.cs
> +    public sealed class Flight : Identifiable
Should probably have a to-one relationship to Airplane, to cover basic relationship kinds.

2021-09-07 08:56 UTC, bart-degreed commented on test/OpenApiTests/OpenApiDbContext.cs
> +        }
This is unneeded, EF Core discovers this automatically.

2021-09-07 08:56 UTC, bart-degreed commented on test/OpenApiTests/OpenApiStartup.cs
> +            app.UseEndpoints(endpoints => endpoints.MapControllers());
Nit: I don't think the blank lines are helpful here.

2021-09-07 08:56 UTC, bart-degreed commented on test/OpenApiTests/OpenApiDocumentTests.cs
> +            string requestUrl = $"swagger/{nameof(OpenApiTests)}/swagger.json";
Please extract `nameof(OpenApiTests)` in a shared constant in OpenApiStartup, and update usages, except for `embeddedResourceName` because that means something else.

2021-09-07 09:00 UTC, maurei commented on test/OpenApiTests/Flight.cs
> +    public sealed class Flight : Identifiable
There are many more ways these models should be more complete, but this is not needed in this PR. These models will be extensively expanded in the next PR. I'm just introducing the models here to have some files for the general structure.

2021-09-07 09:07 UTC, maurei commented on test/OpenApiTests/OpenApiDbContext.cs
> +        }
This is consistent with the rest of the codebase. See eg https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/test/JsonApiDotNetCoreTests/IntegrationTests/ReadWrite/ReadWriteDbContext.cs

2021-09-07 09:42 UTC, bart-degreed commented on test/OpenApiTests/OpenApiDbContext.cs
> +        }
No, it is required there because in that case there are multiple relationships and EF Core is unable to infer what belongs together.

2021-09-07 09:43 UTC, bart-degreed commented on test/OpenApiTests/Flight.cs
> +    public sealed class Flight : Identifiable
ok

2021-09-07 13:08 UTC, bart-degreed commented on test/OpenApiTests/OpenApiDocumentTests.cs
> +            string requestUrl = $"swagger/{nameof(OpenApiTests)}/swagger.json";
As discussed offline, let's not customize the swagger defaults (such as document name, version, title, file name, etc) at this point.

2021-09-07 13:25 UTC, bart-degreed requested changes

2021-09-07 13:25 UTC, bart-degreed commented on docs/getting-started/install.md
> +  <PackageReference Include="JsonApiDotnetCore" Version="4.0.0" />
Why this change? The difference is in the casing of Dotnet.

2021-09-07 13:25 UTC, bart-degreed commented on docs/usage/toc.md
> +# [OpenAPI](openapi.md)
I think this should be near Caching, which is built-in functionality. Extensibility is a level deeper (conceptually) and should come after that.

2021-09-07 13:25 UTC, bart-degreed commented on src/Examples/JsonApiDotNetCoreExample/JsonApiDotNetCoreExample.csproj
> +    <ProjectReference Include="..\..\JsonApiDotNetCore.OpenApi\JsonApiDotNetCore.OpenApi.csproj" />
Please swap the order of these

2021-09-07 13:25 UTC, bart-degreed commented on src/Examples/JsonApiDotNetCoreExample/Startup.cs
> +namespace JsonApiDotNetCoreExample
We should do this file move in master too.

2021-09-07 13:25 UTC, bart-degreed commented on src/Examples/JsonApiDotNetCoreExample/Startup.cs
> +                services.AddOpenApi(mvcCoreBuilder);
Wouldn't it make more sense to call this _after_ AddJsonApi?

2021-09-07 13:25 UTC, bart-degreed commented on docs/usage/openapi.md
> +        IMvcCoreBuilder builder = services.AddMvcCore();
As discussed, rename to mvcBuilder

2021-09-07 13:25 UTC, bart-degreed commented on src/Examples/JsonApiDotNetCoreExample/Startup.cs
> +                app.UseSwaggerUI();
Same here, I would have expected these to come after UseJsonApi.

2021-09-07 13:25 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTests.csproj
> +    <PropertyGroup>
Sadly, this re-indents the file. Reminder to myself to reformat this one before the merge.

2021-09-07 13:35 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTests.csproj
> +
This file lacks a PropertyGroup for NuGet settings (see JsonApiDotNetCore.csproj). And we'll likely need to make changes to the build script to publish to NuGet on build.

2021-09-07 13:37 UTC, maurei commented on docs/getting-started/install.md
> +  <PackageReference Include="JsonApiDotnetCore" Version="4.0.0" />
Because there were several occurrences of the lowercase version on that same page I assumed it was the correct spelling for nuget. But you're right, all occurrences need to be replaced with the DotNet version.

2021-09-08 07:12 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/JsonApiDotNetCore.OpenApi.csproj
> +    <VersionPrefix>4.2.0</VersionPrefix>
Now that this occurs more than once, we should have a variable for this in Directory.Build.props.

2021-09-08 07:19 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/JsonApiDotNetCore.OpenApi.csproj
> +  <PropertyGroup>
Please add:
```
<Authors>json-api-dotnet</Authors>
```
to this file and JsonApiDotNetCore.csproj, to prevent the metadata become the project name.

2021-09-08 07:21 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/JsonApiDotNetCore.OpenApi.csproj
> +    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="$(SwashbuckleVersion)" />
This is fine for now, but when we're going to release we'll likely want to pin to the lowest working version while running our tests against the latest version. We do the same with EF Core dependency.

2021-09-08 07:25 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/ServiceCollectionExtensions.cs
> +        public static void AddOpenApi(this IServiceCollection services, IMvcCoreBuilder mvcBuilder, Action<SwaggerGenOptions> setupSwaggerGenAction = null)
Please document all public types and members in this assembly.

2021-09-08 07:52 UTC, bart-degreed approved these changes

2021-09-08 08:41 UTC, merged