Move existing integration to JADNC
json-api-dotnet/JsonApiDotNetCore pull request #1076
Opened 2021-09-08 17:46 UTC by maurei

Closes #{1048}

_WORK IN PROGRESS_

2021-09-14 15:54 UTC, bart-degreed requested changes
Looked at the docs so far, will review more another day.

2021-09-14 15:54 UTC, bart-degreed commented on docs/usage/openapi/client-generator.md
> +```
This is not the regular way to get started. It should describe clicking Add Service Reference in Visual Studio, which adds package references and other settings to the project file. Once the example project doesn't crash anymore, I can provide the steps here and add the resulting project file changes for completeness and non-VS users.

2021-09-14 15:54 UTC, bart-degreed commented on docs/usage/openapi/client-generator.md
> +// Note that this class should be namespace in which NSwag generates the client.
?

2021-09-14 15:54 UTC, bart-degreed commented on docs/usage/openapi/client-generator.md
> +        var requestDocument = new ApiResourcePatchRequestDocument
This should not use generic names, it makes it hard to distinguish between glue code and generated code. This should be generated against our Example project and use those names instead.

2021-09-14 15:54 UTC, bart-degreed commented on docs/usage/openapi/openapi-generator.md
> +# OpenAPI generator
I think this should remain OpenAPI. The fact we interact with the generator is an implementation detail. "OpenAPI Client library" should be a sub-chapter nested below this doc, because it is a follow-up thing you can do, once OpenAPI is activated in the first place.

2021-09-14 15:54 UTC, bart-degreed commented on docs/usage/openapi/openapi-generator.md
> +        services.AddOpenApi(mvcBuilder);
I didn't expect this change. Is this PR based on the latest version?

2021-09-14 15:54 UTC, bart-degreed commented on run-docker-postgres.ps1
> + postgres:13.4
Looks like the base branch is outdated, this change came from master.

2021-09-14 19:44 UTC, maurei commented on docs/usage/openapi/client-generator.md
> +```
This is the only way to get started that works for both Rider and Visual studio, so I think it should be documented as the main way. Additionally we can include a paragraph that mentions an alternative way for VS. Conversely, as a Rider user, having just a paragraph about how to do it in VS and having to deduce the steps I need to take myself by studying the `csproj` file is unhelpful and not at all user friendly.

2021-09-14 19:49 UTC, maurei commented on docs/usage/openapi/openapi-generator.md
> +# OpenAPI generator
One does not need to use the server-side integration in order to generate a client from an OpenAPI file and use our client library with that. Hence I don't think it should be a sub-chapter, and thus we will need a different title than just "OpenAPI"

2021-09-14 19:59 UTC, maurei commented on docs/usage/openapi/client-generator.md
> +You can you can generate a client library from an OpenAPI specification that describes a JsonApiDotNetCore application. For clients genearted with using [NSwag](http://stevetalkscode.co.uk/openapiref
The revision is good, except for the last sentence. It zooms in on a very narrow slice and covers it, which doesn't belong in an introductory paragraph.

2021-09-14 20:21 UTC, maurei commented on run-docker-postgres.ps1
> + postgres:13.4
Merged maser into base branch.

2021-09-14 20:23 UTC, maurei commented on docs/usage/openapi/openapi-generator.md
> +        services.AddOpenApi(mvcBuilder);
You asked me to convert tabs to spaces after last PR was merged. I decided not to open up a dedicated PR for that and change it in this one.

2021-09-14 21:08 UTC, maurei commented on docs/usage/openapi/client-generator.md
> +        var requestDocument = new ApiResourcePatchRequestDocument
Adjusted

2021-09-14 21:08 UTC, maurei commented on docs/usage/openapi/client-generator.md
> +// Note that this class should be namespace in which NSwag generates the client.
Rephrased it

2021-09-15 09:31 UTC, bart-degreed commented on docs/usage/openapi/client-generator.md
> +```
A recent study on IDE usage among .NET developers revealed that VS is by far the most popular IDE, above 90%, followed by VS Code, and then somewhere below 1% is Rider. Using VS is the easiest way to accomplish this, which lowers the barrier for beginners. Experienced devs (and paying Rider users) will know how to patch the project file manually, based on our guidance at the bottom. Also, the VS UI abstracts the details, such as package versions, which may change over time. In the project file, we can mark the sections that need to be added, which encompasses all the needed steps.

2021-09-15 09:38 UTC, bart-degreed commented on docs/usage/openapi/openapi-generator.md
> +# OpenAPI generator
> One is not required to use our server-side integration to use our client library
If what you mean is: "one could use another client library instead of ours", then the location is irrelevant. So I assume you mean: "non-JADNC users may also be interested in our client library support". Well, that may be the case... and it might even work. But that's not our audience and I certainly wouldn't want to support that. The most realistic case I can think of is an API developer using JADNC, then sending the OpenApi client link to its customer of which he knows is using .NET Core.

2021-09-15 09:39 UTC, bart-degreed commented on docs/usage/openapi/openapi-generator.md
> +        services.AddOpenApi(mvcBuilder);
ok

2021-09-15 09:42 UTC, bart-degreed commented on docs/usage/openapi/client-generator.md
> +You can you can generate a client library from an OpenAPI specification that describes a JsonApiDotNetCore application. For clients genearted with using [NSwag](http://stevetalkscode.co.uk/openapiref
It's not a detail, it's the only reason why the package exists. As a reader, my first question would be: why do I need this?

2021-09-15 15:45 UTC, bart-degreed requested changes
Done with review pass. Please don't force-push anymore after the code review has started.

2021-09-15 15:45 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ClientAttributeRegistrationLifeTimeTests.cs
> +    public sealed class ClientAttributeRegistrationLifetimeTests
Please keep the models 1-on-1 (data types, relationships, capabilities, etc) with our internal prototype. The plan was to drop the already reviewed code and tests in this PR, then move forward from there in follow-up PRs. But the model consolidations introduced require me to re-analyze all the tests: do they cover the intent, is there any redundancy, etc.

2021-09-15 15:45 UTC, bart-degreed commented on src/JsonApiDotNetCore/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("JsonApiDotNetCore.OpenApiClient")]
This should not be needed. There must not be a dependency between client and server libraries.

Likewise, JsonApiDotNetCore.OpenApi\AssemblyInfo.cs should be removed.

2021-09-15 15:45 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/JsonApiMetadata/EndpointResolver.cs
> +                typeof(BaseJsonApiOperationsController).IsAssignableFrom(controllerAction.ReflectedType))
`BaseJsonApiOperationsController` inherits from `CoreJsonApiController`, so the second condition should be unneeded, right?

2021-09-15 15:45 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiSchemaGenerator.cs
> +            OpenApiSchema fullSchemaForDocument = _schemaRepositoryAccessor.Current.Schemas[referenceSchemaForDocument.Reference.Id];
Why has the order been swapped here?

2021-09-15 15:45 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/ServiceCollectionExtensions.cs
> +            mvcBuilder.AddMvcOptions(options => options.InputFormatters.Add(new JsonApiRequestFormatMetadataProvider()));
This has changed, but I don't understand why. Would like to discuss this tomorrow.

2021-09-15 16:03 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi.Client/JsonApiDotNetCore.OpenApi.Client.csproj
> +    <Description>Provides support for partial PATCH and partial POST requests for a C# client generated with NSwag.</Description>
I'd like to propose:

> Provides support for OpenAPI generated clients in sending partial POST/PATCH requests against JSON:API endpoints.

Not just C#, could be VB, F# or any other .NET language. Let's not refer to NSwag when we don't reflect that in the package name. It may change over time and we may support additional generators. And we should mention this is for JSON:API.

2021-09-15 16:05 UTC, bart-degreed commented on JsonApiDotNetCore.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "JsonApiDotNetCore.OpenApi.Client", "src\JsonApiDotNetCore.OpenApi.Client\JsonApiDotNetCore.OpenApi.Client.csproj", "{5ADAA902-5A75-4ECB-B4B4-03291
OpenApiClientTests project is not in the solution.

2021-09-15 22:21 UTC, maurei commented on src/JsonApiDotNetCore.OpenApiClient/JsonApiDotNetCore.OpenApiClient.csproj
> +  </ItemGroup>
They have been removed by having introducing a local argument guard.

2021-09-15 22:22 UTC, maurei commented on test/OpenApiClientTests/LegacyClient/ClientAttributeRegistrationLifeTimeTests.cs
> +    public sealed class ClientAttributeRegistrationLifetimeTests
The models have, apart from minor exceptions, been ported 1-on-1. I have shared you a mapping in a private channel.

2021-09-15 22:30 UTC, maurei commented on test/OpenApiTests/ExistingOpenApiIntegration/FlightAttendant.cs
> +    public sealed class FlightAttendant : Identifiable<string>
That will result in deviations with the test codebase in our private repo. I prefer to keep it the same for now. Data type tests will be covered extensively in the next issue.

2021-09-15 22:32 UTC, maurei commented on test/OpenApiTests/ExistingOpenApiIntegration/ExistingIntegrationDbContext.cs
> +                .Ignore(flight => flight.ServicesOnBoard);
I chose `Ignore()` because that is the way it was configured in the private repository

2021-09-15 22:35 UTC, maurei commented on test/OpenApiTests/ExistingOpenApiIntegration/FlightAttendant.cs
> +        public int Age { get; set; }
There is no point in making an effort to cover different/new data types here. The next issue coming up will cover all of this extensively.

2021-09-15 22:37 UTC, maurei commented on docs/usage/openapi/client-generator.md
> +You can you can generate a client library from an OpenAPI specification that describes a JsonApiDotNetCore application. For clients genearted with using [NSwag](http://stevetalkscode.co.uk/openapiref
Discussed this privately. As long as partial patching/posting is the only thing the package does, we agreed that it is fine to zoom in here.

2021-09-15 22:39 UTC, maurei commented on docs/usage/openapi/client-generator.md
> +```
Discussed this privately. We will keep a section for Rider users, Bart will add a section for VS covering the common-case usage as described on de microsoft docs.

2021-09-15 22:40 UTC, maurei commented on docs/usage/openapi/openapi-generator.md
> +# OpenAPI generator
Discussed this privately: this makes sense and it implies the library should be `OpenApi.Client`, not `OpenApiClient`.

2021-09-15 22:54 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiSchemaGenerator.cs
> +            OpenApiSchema fullSchemaForDocument = _schemaRepositoryAccessor.Current.Schemas[referenceSchemaForDocument.Reference.Id];
I'm not sure what happened there

2021-09-15 23:08 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiMetadata/EndpointResolver.cs
> +                typeof(BaseJsonApiOperationsController).IsAssignableFrom(controllerAction.ReflectedType))
I think you're missing the `!`. I've refactored it a bit to make it more readable.

2021-09-16 11:02 UTC, bart-degreed requested changes
Done with another review pass. Still pending:
- review tests, based on the doc you sent me
- update install steps in .md
- diff the swagger.json against internal prototype

2021-09-16 14:16 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/ServiceCollectionExtensions.cs
> +            mvcBuilder.AddMvcOptions(options => options.InputFormatters.Add(new JsonApiRequestFormatMetadataProvider()));
Resolving, this is now covered in the PR description.

2021-09-16 14:20 UTC, maurei commented on test/OpenApiTests/LegacyOpenApiIntegration/Airplane.cs
> +        public AircraftType AircraftType { get; set; }
Discussed offline. I have (re-)ordered the properties so that they resemble the order of the models in the private repo.

2021-09-17 09:48 UTC, bart-degreed requested changes
Reviewed client tests

2021-09-17 09:48 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/RequestTests.cs
> +                airplane => airplane.SerialNumber, airplane => airplane.AirtimeInHours))
`airplane.LastServicedAt` and `airplane.IsDeleted` are missing here.

2021-09-17 09:48 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ResponseTests.cs
> +            FlightPrimaryResponseDocument document = await apiOpenApiClient.GetFlightAsync(Convert.ToInt32(flightId));
This is a bug and should take a string `id` parameter, irrespective of the typed ID, which is a server implementation detail. Please create an issue to track that and use only strings for IDs in this PR.

2021-09-17 09:48 UTC, bart-degreed commented on test/OpenApiTests/LegacyOpenApiIntegration/Flight.cs
> +        public Airplane OperatingAirplane { get; set; }
As discussed offline, these relationship characteristics differ from our internal prototype, in that we need both a to-one and a to-many of the same type, so please adjust. Another subtle difference is in casing because there is no plural for "Personnel", so this reduces coverage.

Suggestion: use to-one "Captain" and to-many "CabinCrewMembers".

2021-09-17 11:30 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/RequestTests.cs
> +            IOpenApiClient apiOpenApiClient = new OpenApiClient(wrapper.HttpClient);
Still has the wrong name.

2021-09-17 18:30 UTC, bart-degreed requested changes
Gone over client tests again. Looks good now, except what's listed. Pending: swagger.json

2021-09-17 18:30 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ResponseTests.cs
> +            const string cabinPersonnelMetaValue = "https://jsonapi.net/api/docs/#get-flight-cabin-crew-members";
Should be: `cabinCrewMembersMetaValue`

2021-09-17 18:30 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ResponseTests.cs
> +            flight.Attributes.ServicesOnBoard.ElementAt(0).Should().Be(fightServiceOnBoard);
Misspelled, should be: `flightServiceOnBoard`

2021-09-17 18:30 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiObjectNullabilityProcessor.cs
> +    /// https://github.com/degreed/JsonApiCorePrototype/blob/936db8950d925f1b8a055cf5d8bba753f6579094/src/Web/OpenApi/JsonApiObjects/Documents/ManyResourceIdentifierResponseDocument.cs#L7
Do not link into non-public repository

2021-09-17 18:30 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ResponseTests.cs
> +            const string flightMetaValue = "https://api.jsonapi.net/docs/#get-flights";
You're using `https://api.jsonapi.net/` here, but `https://jsonapi.net/api` everywhere else

2021-09-17 18:30 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ResponseTests.cs
> +            const string flightDestination = "Destination of Flight";
Use a sensible value, ie Aruba

2021-09-17 18:30 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ClientAttributeRegistrationLifeTimeTests.cs
> +#pragma warning disable AV1704 // Don't include numbers in variables, parameters and type members
Remove suppression for AV1704 here and in ResponseTests. It is configured at Info level in this repo, so won't break the build.

2021-09-17 18:30 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ResponseTests.cs
> +            flight.Attributes.FinalDestination.Should().Be(flightDestination);
Missing here (and in next test): assertion on StopOverDestination

2021-09-17 19:44 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ResponseTests.cs
> +            flight.Attributes.FinalDestination.Should().Be(flightDestination);
Should have a value (see source), not null.

2021-09-17 19:45 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ResponseTests.cs
> +
Don't add a blank line here

2021-09-17 20:09 UTC, bart-degreed approved these changes

2021-09-17 20:37 UTC, merged