Update openapi branch
json-api-dotnet/JsonApiDotNetCore pull request #1105
Opened 2021-11-08 13:31 UTC by maurei

Updates the `openapi` branch with the latest changes from master (among which the introduction of NRT).

2021-11-09 16:20 UTC, bart-degreed requested changes
Done with review pass.

2021-11-09 16:20 UTC, bart-degreed commented on test/OpenApiTests/LegacyOpenApiIntegration/Airplane.cs
> +        public ISet<Flight> Flights { get; set; } = null!;
Don't to this, it fails ModelState validation, as described [here](https://www.jsonapi.net/usage/resources/nullability.html#nrt-turned-on).

This comment applies to all `[HasMany]` usages in this project.

2021-11-09 16:20 UTC, bart-degreed commented on test/OpenApiTests/LegacyOpenApiIntegration/Airplane.cs
>          [Required]
Remove all `[Required]` usage, except for nullable value types, as described [here](https://www.jsonapi.net/usage/resources/nullability.html#nrt-turned-on).

2021-11-09 16:20 UTC, bart-degreed commented on test/OpenApiTests/LegacyOpenApiIntegration/Flight.cs
> +        public ICollection<string>? ServicesOnBoard { get; set; }
I find this quite odd. The collection can be empty or null? What would that distinction mean?

2021-11-09 16:20 UTC, bart-degreed commented on test/OpenApiTests/LegacyOpenApiIntegration/FlightAttendant.cs
>          [Attr(Capabilities = AttrCapabilities.All)]
As I recently discovered, this does not work (see [here](https://www.jsonapi.net/usage/resources/nullability.html#nrt-turned-on)). Declare the property as nullable instead, but keep `[Required]`.

2021-11-09 16:20 UTC, bart-degreed commented on test/TestBuildingBlocks/HttpRequestHeadersExtensions.cs
> +            return requestHeaders.TryGetValues(name, out IEnumerable<string>? values) ? new StringValues(values.ToArray()).ToString() : null;
I would have preferred to keep this variable, but understand why you did this: the compiler nullability flow analysis fails otherwise.

2021-11-10 09:48 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiMetadata/JsonApiEndpointMetadataProvider.cs
> +            ResourceType primaryResourceType = _controllerResourceMapping.GetResourceTypeForController(controllerAction.ReflectedType)!;
The call above it guarantees it to be a JADNC controller at this point

2021-11-10 09:50 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiMetadata/JsonApiEndpointMetadataContainer.cs
> +        public IJsonApiResponseMetadata? ResponseMetadata { get; init; }
That's not correct. Several endpoints have no request body, eg `GET` requests, and several other endpoints have no request body, eg `DELETE` endpoints. For these endpoints, the associated property is `null`.

2021-11-10 11:18 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/NullableReferenceSchemaGenerator.cs
> +        private static OpenApiSchema? _referenceSchemaForNullValue;
Issues arising from this being static is fixed in the naming convention branch

2021-11-10 11:47 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceFieldObjectSchemaBuilder.cs
> +            return GetReferenceSchemaForFieldObject(fullSchemaForAttributesObject, JsonApiObjectPropertyName.AttributesObject);
If in a resource object the `attributes` or `relationships` object has no entries, it will be omitted as a whole, in which case we don't need to configure `AdditionalPropertiesAllowed`.  So it is not a breaking change, it only removes redundancy.

2021-11-10 12:05 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/ActionDescriptorExtensions.cs
> +        public static TFilterMetaData? GetFilterMetadata<TFilterMetaData>(this ActionDescriptor descriptor)
Generally speaking: there is no guarantee that the provided `ActionDescriptor` has a filter of `TFilterMetaData` (could eg be `AuthorizeFilter` which we don't use right now), so this method can return `null`.

Its two callers are `JsonApiActionDescriptorCollectionProvider` and `JsonApiOperationIdSelector`. In the first case: we are sure that `ActionDescription` represents a JADNC action for which we're sure the requested metadata is available given that we added it ourselves earlier. In the second: this will also be triggered for non-JADNC controllers once we add them and it will break in an earlier stage. I can add a `NotSupportedException` there, which for now guarantees the suppression here is valid.

2021-11-10 12:10 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiActionDescriptorCollectionProvider.cs
> +            return produces.ContentTypes.Any(contentType => contentType == HeaderConstants.MediaType);
Because for JADNC endpoints we are guaranteed that `ProducesAttribute` exists.

2021-11-10 12:11 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiObjectPropertyName.cs
> -        public const string JsonapiObjectProfile = "profile";
They are no longer used

2021-11-10 12:20 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiActionDescriptorCollectionProvider.cs
> +                ExpandTemplate(expandedEndpoint.AttributeRouteInfo!, relationshipName);
Here we're guaranteed that `expandedEndpoint` is a JADNC action. In the default use case, we can rely on the route attributes being set on `JsonApiController`. This will break when custom controllers are introduced and attribute-based routing is replaced with a customised routing convention. I think we shouldn't worry about this for now until #1065. Do you think for now we should throw a `NotSupportedExpection` in the meanwhile?

2021-11-10 12:21 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiOperationIdSelector.cs
> +                _controllerResourceMapping.GetResourceTypeForController(endpoint.ActionDescriptor.GetActionMethod().ReflectedType)!;
Last bit of comment in https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1105#discussion_r746523239 applies here

2021-11-10 12:22 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiOperationIdSelector.cs
> +        private static Type? GetGenericTypeDefinitionOrDefault(Type type)
Leaving it out is better indeed now that we return `Type?`

2021-11-10 12:26 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiActionDescriptorCollectionProvider.cs
> +            ControllerParameterDescriptor requestBodyDescriptor = endpoint.GetBodyParameterDescriptor()!;
This will be the case for actions that have no parameters annotated with `[FromBody]`. In this method however, we are sure because earlier on the metadata we've retrieved for this action implements `IJsonApiRequestMetadata`.

2021-11-10 12:34 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/OpenApiEndpointConvention.cs
> +            ResourceType primaryResourceTypeOfEndpoint = _controllerResourceMapping.GetResourceTypeForController(controllerType)!;
Last bit of comment in https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1105#discussion_r746523239 applies here

2021-11-10 12:47 UTC, maurei commented on test/OpenApiTests/LegacyOpenApiIntegration/Flight.cs
> +        public ICollection<string>? ServicesOnBoard { get; set; }
I agree it is a bit weird, but it changing it will break the legacy integration swagger document test.

2021-11-10 12:51 UTC, maurei commented on test/OpenApiTests/LegacyOpenApiIntegration/Airplane.cs
>          [Required]
I was afraid to find a problem with this because Swashbuckle also maps this to `"required": true`, but I'm happy to see that NRT support was implemented in line with model state validation!

2021-11-10 16:15 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiObjectNullabilityProcessor.cs
> -    internal sealed class JsonApiObjectNullabilityProcessor
The JsonApiObjectNullabilityProcessor can be safely removed because it only postprocesses schemas associated with internal types in JADNC (those in the `JsonApiObjects` namespace), so this is unaffected by the NRT settings in a project that consumes JADNC.

Looking beyond the nullabiliy processor: turning NRT on has an effect on attributes defined in resources in an API project:
| NRT off | NRT on | 
| --- | --- |
| string => `{ "nullable": true }`             | string => `{ "nullable": false }`   |
| [Required] string => `{ "nullable": false }` | [Required] string => `{ "nullable": false }`  |
| - |  string? => `{ "nullable": true }`  |
| - | [Required] string? => `{ "nullable": false }`  |

So by turning NRT on in JADNC, NRT-free projects will not be able to set `"nullable": true` anymore for reference types (however, previously impossible, they can now set `"required": false` for properties that are not nullable). We could consider introducing a `CanBeNullAttribute` to enable setting properties as nullable in the outputted document.

2021-11-10 16:21 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/ServiceCollectionExtensions.cs
> +                swaggerGenOptions.SupportNonNullableReferenceTypes();
See https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1105#discussion_r746750306.  I think introducing an attribute as proposed there would be preferable over supporting allowing users to turn this on and off.

2021-11-11 09:31 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiMetadata/JsonApiEndpointMetadataContainer.cs
> +        public IJsonApiResponseMetadata? ResponseMetadata { get; init; }
Moved to constructor, kept nullability.

2021-11-11 09:32 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiMetadata/JsonApiEndpointMetadataProvider.cs
> +            ResourceType primaryResourceType = _controllerResourceMapping.GetResourceTypeForController(controllerAction.ReflectedType)!;
Added an `UnreachableCodeException`.

2021-11-11 10:05 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceTypeInfo.cs
> +            return (TResourceFieldAttribute?)_resourceType.Fields.FirstOrDefault(field => field is TResourceFieldAttribute && field.PublicName == publicName);
Exposing ResourceType is OK by Demeters law in this case.

2021-11-11 10:23 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/ActionDescriptorExtensions.cs
> +        public static TFilterMetaData? GetFilterMetadata<TFilterMetaData>(this ActionDescriptor descriptor)
We've decided to use `UnreachableCodeException`s unless it is immediately clear from the context of the code that suppressions are valid.

2021-11-11 10:30 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiActionDescriptorCollectionProvider.cs
> +            return produces.ContentTypes.Any(contentType => contentType == HeaderConstants.MediaType);
We've decided to use UnreachableCodeExceptions unless it is immediately clear from the context of the code that suppressions are valid.

2021-11-11 10:33 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiActionDescriptorCollectionProvider.cs
> +                ExpandTemplate(expandedEndpoint.AttributeRouteInfo!, relationshipName);
We have decided on throwing a NotSupportedException.

2021-11-16 17:33 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiActionDescriptorCollectionProvider.cs
> +            ControllerParameterDescriptor requestBodyDescriptor = endpoint.GetBodyParameterDescriptor()!;
Any JADNC-endpoint is guaranteed to have [FromBody] metadata.

2021-11-16 17:34 UTC, maurei commented on test/OpenApiTests/LegacyOpenApiIntegration/Flight.cs
> +        public ICollection<string>? ServicesOnBoard { get; set; }
Removed

2021-11-16 17:34 UTC, maurei commented on test/OpenApiTests/LegacyOpenApiIntegration/Airplane.cs
>          [Required]
Removed, and handing of populating the `required` property in OpenAPI schemas is adjusted to reflect the behaviour of the API.

2021-11-17 02:47 UTC, bart-degreed requested changes
Completed another review pass. Note the cibuild fails on whitespace issues.

2021-11-17 02:47 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/ServiceCollectionExtensions.cs
> +                swaggerGenOptions.SupportNonNullableReferenceTypes();
I don't think that's correct: this affects *all* types, including those in a custom API project. If you can confirm that what lies behind `SupportNonNullableReferenceTypes()` is additive only, ie. it does not make any difference when *not* using NRT in an API project, then it should not be a problem to always call this.

2021-11-17 02:47 UTC, bart-degreed commented on test/OpenApiTests/LegacyOpenApiIntegration/Flight.cs
> +        public ICollection<string>? ServicesOnBoard { get; set; }
It was recently changed into:
```
public ICollection<string> ServicesOnBoard { get; set; } = null!;
```
which fails ModelState validation, while also producing a change in swagger.json. If your goal is to keep swagger.json unchanged, this should be nullable indeed, although it looks odd and was probably never the intention. Therefore I think the appropriate action is to change into non-nullable and assign a default collection (so ModelState does not break), and it should reflect that change in swagger.json.

2021-11-17 02:47 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceFieldObjectSchemaBuilder.cs
> +                AttrAttribute? matchingAttribute = _resourceTypeInfo.ResourceType.FindAttributeByPublicName(fieldName);
fieldName => attributeName

2021-11-17 02:47 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceFieldObjectSchemaBuilder.cs
> +                RelationshipAttribute? matchingRelationship = _resourceTypeInfo.ResourceType.FindRelationshipByPublicName(fieldName);
fieldName => relationshipName

2021-11-17 02:47 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceFieldObjectSchemaBuilder.cs
> +                        }
Shouldn't setting nullable/required be applied on relationships too?

2021-11-17 10:01 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/ServiceCollectionExtensions.cs
> +                swaggerGenOptions.SupportNonNullableReferenceTypes();
I already confirmed that in the comment referenced above.

2021-11-17 10:33 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/OpenApiEndpointConvention.cs
> +            ResourceType primaryResourceType = _resourceGraph.GetResourceType(primaryResourceTypeOfEndpoint.ClrType);
This slipped through my attention when switching to the new controller resource mapper that now returns `ResourceType`, whereas before the additional call was needed to get to `ResourceContext` from `Type`.

2021-11-17 11:34 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceFieldObjectSchemaBuilder.cs
> +                AttrAttribute? matchingAttribute = _resourceTypeInfo.ResourceType.FindAttributeByPublicName(fieldName);
The entries in `_schemasForResourceFields` are both attributes and relationships, so with your suggested change the variable name would be incorrect in iterations where the entry is a relationship. Same applies in https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1105#discussion_r750839009

2021-11-18 12:29 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiObjects/Documents/PrimaryResourceResponseDocument.cs
> +
Types in the `JsonApiDotNetCore.OpenApi.JsonApiObjects` namespace are never touched by ASP.NET ModelState validation, therefore using a non-nullable reference type for a property does not imply this property is required. Instead, we rely on explicitly setting `RequiredAttribute` Which is how Swashbuckle is directed to mark properties as required.

2021-11-18 12:35 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceFieldObjectSchemaBuilder.cs
> +                        }
We've discussed this offline and have decided to introduce nullable variants for `ToOneRelationshipRequestData` and `ToOneRelationshipReponseData`. I have also introduced a new relationship `Flight.BackupPurser <--> FlightAttendant.BackupPurserOnFlights` to demonstrate both a nullable next to the non-nullable `HasOne` relationship. This introduces minor new section in the `swagger.json` file.

2021-11-18 14:17 UTC, bart-degreed requested changes
Partial review. I'm not going to assess the correctness of code while there are still broken tests.

2021-11-18 14:17 UTC, bart-degreed commented on test/OpenApiTests/LegacyOpenApiIntegration/FlightAttendant.cs
> +        public ISet<Flight> BackupPurserOnFlights { get; set; } = new HashSet<Flight>();
There's no HasMany here, so why have this property at all?

2021-11-18 14:51 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiObjects/Documents/PrimaryResourceResponseDocument.cs
> +    /// which is how Swashbuckle is instructed to mark properties as required.
I used triple-slash because if the namespace is ever to be renamed, the comment won't have to be adjusted manually. I don't see any harm in this. But since it can be avoided with "this namespace", I'll use that instead.

2021-11-18 14:52 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiObjects/SingleData.cs
> +        where TData : ResourceIdentifierObject?
That won't work for eg `ToManyRelationshipRequestData`.

2021-11-19 14:44 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiActionDescriptorCollectionProvider.cs
> +
I didn't consider it as a low-level generic cloning mechanism because it clones only that what is needed for the expansion to occur. In this sense I regarded the choice what to clone and what to skip as business logic too, and from this point of view, throwing a `NotSupportedException` when that what is required for this cloning is not present, did not seem off to me.

2021-11-22 15:24 UTC, bart-degreed requested changes
Done with another review pass.

2021-11-22 15:24 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/JsonApiActionDescriptorCollectionProvider.cs
> +                case NonPrimaryEndpointMetadata expansibleMetadata and (RelationshipResponseMetadata or SecondaryResponseMetadata):
rename variable too (multiple locations)

2021-11-23 10:35 UTC, bart-degreed approved these changes

2021-11-23 10:35 UTC, merged