OpenAPI: Generalization of naming conventions
json-api-dotnet/JsonApiDotNetCore pull request #1123
Opened 2021-12-06 14:41 UTC by maurei

_WIP_

2021-12-15 13:31 UTC, bart-degreed requested changes
Done with review pass.

2021-12-15 13:31 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/StringExtensions.cs
> +    public static string Pascalize(this string source)
It's _very_ confusing to add a method with an identical signature as in Humanizer, but with slightly different behavior. There's no way to see at the call side which one is being used.

2021-12-15 13:31 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/StringExtensions.cs
> +        return Regex.Replace(source, "(?:^|-|_| +)(.)", match => match.Groups[1].Value.ToUpper());
Perf: Create a static readonly `Regex` instance, passing in `RegexOptions.Compiled`.

2021-12-15 13:31 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ClientAttributeRegistrationLifeTimeTests.cs
> +                Type = AirplaneResourceType.Airplanes,
Why was this changed to singular? From an API consumer perspective, there is no such thing as an "airplane" resource type. There's just the "airplanes" resource type. This "type" field should be unrelated to generated CLR type names and endpoint method names.

2021-12-15 13:31 UTC, bart-degreed commented on test/OpenApiClientTests/OpenApiClientTests.csproj
> +    </None>
Please put this above external dependencies, like in the other test project files.

2021-12-15 13:31 UTC, bart-degreed commented on test/OpenApiTests/LegacyOpenApiIntegration/swagger.json
> +            "$ref": "#/components/schemas/airplane-resource-type"
I think this should remain plural as well.

2021-12-15 13:31 UTC, bart-degreed commented on test/OpenApiClientTests/OpenApiClientTests.csproj
> +    </None>
Please put this above external dependencies, like in the other test project files.

2021-12-15 13:31 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTests.csproj
> +  </ItemGroup>
Please put this above external dependencies, like in the other test project files.

2021-12-15 13:31 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/ServiceCollectionExtensions.cs
> +
Why the added line break?

2021-12-15 13:50 UTC, bart-degreed commented
It's annoying that running the tests checks out swagger.json files, which results in failure of cleanupcode later. Can we commit them as-is and exclude them from cleanupcode?

2021-12-15 14:46 UTC, maurei commented on test/OpenApiTests/OpenApiTestContext.cs
> +        UseController<SupermarketsController>();
This indeed doesn't make sense. Setting the controllers should be done in the constructor of a test suite. I would still prefer to store the loaded swagger document in the class fixture rather than using a static property on the test suite.

2021-12-15 14:58 UTC, maurei commented on test/OpenApiTests/OpenApiTestContext.cs
> +        string solutionTestDirectoryPath = Directory.GetParent(Environment.CurrentDirectory)!.Parent!.Parent!.Parent!.FullName;
> It's either a file, a directory, or a path. There's no such thing as a directory path.

With `directory path` I mean the path to a directory. [I think there is nothing wrong with that](https://unix.stackexchange.com/a/131585). Will clarify by writing `pathToDirectory`.

2021-12-15 15:02 UTC, maurei commented on test/OpenApiTests/OpenApiTestContext.cs
> +        Document = parsedContent.ToJsonElement();
I did not do this because the first line is belongs to the third line as much as it belongs to the second line. The with the separators you've introduced this is less evident.

I also don't care that much because in both cases it is perfectly readable to me, so I will use your suggestion

2021-12-15 15:07 UTC, maurei commented on test/OpenApiTests/OpenApiTests.csproj
> +    <PackageReference Include="BlushingPenguin.JsonPath" Version="1.0.*" />
Good point, thanks

2021-12-15 15:14 UTC, maurei commented on test/OpenApiTests/NamingConvention/PascalCase/PascalCaseTests.cs
> +    public void Pascal_casing_convention_is_applied_to_GetCollection_endpoint()
I deliberately avoided using the exact same test names over different suites because it makes it impossible to choose the right one when jumping to a file. That's why I decided to have all the names equal expect for the first two terms. This This way it is still easy to compare the method names while still being able to jump to the right one.

2021-12-15 15:23 UTC, maurei commented on test/TestBuildingBlocks/JsonElementExtensions.cs
> +            json.ShouldNotBeNull();
Looking at `JsonElement.ToString`, we can be sure it's not going to be null.

2021-12-15 15:37 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/StringExtensions.cs
> +    public static string Pascalize(this string source)
Why is this a problem? The job is being done i.e., the string is being pascalized. If for whatever reason you need to know where this method is defined (if at all the reader was aware of Humanizer having such method, which I do not think we should assume), it is easily figured out.

2021-12-15 15:58 UTC, maurei commented on test/OpenApiClientTests/LegacyClient/ClientAttributeRegistrationLifeTimeTests.cs
> +                Type = AirplaneResourceType.Airplanes,
I don't agree. In all CLR types we've chosen it to be singular. Choosing plural here would be weird. Perhaps you're confused with the _value_ of this enum that _should_ be plural: `SupermarketResourceType.Supermarkets`

2021-12-15 16:01 UTC, maurei commented on test/OpenApiTests/LegacyOpenApiIntegration/swagger.json
> +            "$ref": "#/components/schemas/airplane-resource-type"
This here and https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1123#discussion_r769609681 go hand in hand. What we pick here results in the CLR type name. As argued there, I think this should be singular, as long as the value is plural.

2021-12-15 16:21 UTC, maurei commented
> It's annoying that running the tests checks out swagger.json files, which results in diffs from cleanupcode later. Can we commit them as-is and exclude them from cleanupcode?

I don't know why cleanupcode is still hitting these files, we already have a `swagger.json` file mask in the code analysis. How  do we turn this off?

2021-12-15 16:24 UTC, maurei commented on test/OpenApiTests/NamingConvention/Supermarket.cs
> +[Resource(ControllerNamespace = "OpenApiTests")]
It wasn't the default, `OpenApiTests.Controllers` was the namespace value. The problem this solved is that the controllers are placed in the same namespace as where it is referenced from. Putting it in a different namespace and adding a using directive to that namespace, will trigger cleanup code to remove that using directive, which then in turn leads to a failing CI.

2021-12-16 08:29 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi/StringExtensions.cs
> +    public static string Pascalize(this string source)
Because it puts people on the wrong track, seeing the package reference to Humanizer and then this call. https://csharpcodingguidelines.com/naming-guidelines/#AV1711. Sure you could define your own class named `Int32` whose `Parse` behaves slightly different, which would be similarly confusing.

2021-12-16 08:33 UTC, bart-degreed commented on test/OpenApiClientTests/LegacyClient/ClientAttributeRegistrationLifeTimeTests.cs
> +                Type = AirplaneResourceType.Airplanes,
I'm thinking of an imaginary enum that would list all the resource types in the project:
```
public enum PlaceholderName
{
    Airplanes,
    Supermarkets
}
```
Then the convention would be to pluralize `PlaceholderName` if it had `[Flags]`, which is not the case. So I'm fine with making this singular.

2021-12-16 08:34 UTC, bart-degreed commented on test/OpenApiTests/LegacyOpenApiIntegration/swagger.json
> +            "$ref": "#/components/schemas/airplane-resource-type"
Agreed.

2021-12-16 08:35 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTestContext.cs
> +        UseController<SupermarketsController>();
I'm making a distinction to what invokes the logic, vs where that logic is defined.

2021-12-16 08:37 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTestContext.cs
> +        string solutionTestDirectoryPath = Directory.GetParent(Environment.CurrentDirectory)!.Parent!.Parent!.Parent!.FullName;
The terms are overloaded. Sometimes 'directory' means one node in the tree, at other times it implies the full path to a location in a subtree. See https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.move?view=net-6.0. I'm fine with the proposed clarification.

2021-12-16 08:39 UTC, bart-degreed commented on test/OpenApiTests/NamingConvention/PascalCase/PascalCaseTests.cs
> +    public void Pascal_casing_convention_is_applied_to_GetCollection_endpoint()
There are only 3 files, so it's not that hard. And the IDE shows the class/file name as well, IIRC. We're doing this in other places already, such as https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/test/JsonApiDotNetCoreTests/IntegrationTests/Links.

2021-12-16 08:41 UTC, bart-degreed commented on test/OpenApiTests/NamingConvention/PascalCase/PascalCaseTests.cs
> +    public void Pascal_casing_convention_is_applied_to_GetCollection_endpoint()
Likewise, jump to Can_get_primary_resources and you'll find a bunch of matches in different namespaces. That's what namespaces are for. You wouldn't encode the namespace in regular class names, would you?

2021-12-16 10:29 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/JsonApiObjects/Documents/NullableResourceIdentifierResponseDocument.cs
> +    [JsonPropertyName("meta")]
It does; in the case of a pascal casing convention, swashbuckle will also apply it to the keys in the data structure. I noticed I missed a few, added them there too.

2021-12-16 13:40 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTests.csproj
> +    <PackageReference Include="BlushingPenguin.JsonPath" Version="1.0.*" />
I'm still seeing it.

2021-12-16 13:42 UTC, bart-degreed commented on test/TestBuildingBlocks/JsonElementExtensions.cs
> +    public sealed class ReferenceSchemaIdAssertion
You changed it here, but variables of this type are still named as `documentSchemaRefId`.

2021-12-16 13:54 UTC, bart-degreed commented on JsonApiDotNetCore.sln.DotSettings
> +
Why the extra line breaks? Did you review changes before commit?

2021-12-16 13:54 UTC, bart-degreed commented on test/OpenApiTests/JsonElementExtensions.cs
> +        }
Why add another version of `BeJson` when we already have one? Reuse the existing one.

2021-12-16 13:54 UTC, bart-degreed commented on test/OpenApiTests/JsonElementExtensions.cs
> +        internal string ReferenceSchemaId { get; init; } = null!;
Why this clumsiness? You're using the wrong construct so that you need to suppress a compiler warning.

2021-12-16 13:54 UTC, bart-degreed commented on src/JsonApiDotNetCore.OpenApi.Client/ApiException.cs
> +// ReSharper disable All
I'm not seeing the expected improvements.

2021-12-16 13:54 UTC, bart-degreed requested changes
Will look at other parts later

2021-12-20 14:14 UTC, bart-degreed requested changes

2021-12-20 14:14 UTC, bart-degreed commented on test/OpenApiTests/NamingConventions/CamelCase/CamelCaseTests.cs
> +public sealed class PascalCaseTests
PascalCaseTests in CamelCaseTests.cs

2021-12-20 14:14 UTC, bart-degreed commented on test/OpenApiTests/NamingConventions/KebabCase/KebabCaseTests.cs
> +public sealed class PascalCaseTests
PascalCaseTests in KebabCaseTests.cs

2021-12-20 14:14 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTestContext.cs
> +        string outputPath = Path.Join(solutionRoot, relativePath, "swagger.g.json");
See my earlier remark on `Path.Combine` vs `Path.Join`.

2021-12-20 14:14 UTC, bart-degreed commented on test/OpenApiTests/OpenApiTests.csproj
>    </ItemGroup>
Based on the existing convention to place project items above dependencies, this should be moved up.

2021-12-20 19:58 UTC, bart-degreed commented on test/OpenApiTests/NamingConventions/CamelCase/CamelCaseTests.cs
> +public sealed class PascalCaseTests
If I diff CamelCaseTests.cs with PascalCaseTests.cs in case-insensitive mode, I'm still seeing changes, for example in variable names. Also, the test names are back to Camel_casing_convention... vs Pascal_casing_convention..., which we discussed earlier and decided to avoid such cosmetic differences.

2021-12-20 20:01 UTC, bart-degreed commented on test/OpenApiTests/NamingConventions/KebabCase/KebabCaseTests.cs
> +public sealed class PascalCaseTests
If I diff CamelCaseTests.cs with KebabCaseTests.cs (ignoring all '-' chars), I'm still seeing changes, for example in variable names.

2021-12-21 11:23 UTC, bart-degreed approved these changes

2021-12-21 12:33 UTC, merged