Support NRT and MSV in `required` and `nullable`
json-api-dotnet/JsonApiDotNetCore pull request #1185
Opened 2022-09-06 15:40 UTC by maurei

This PR introduces improved support for `required` and `nullable` properties in OpenAPI schemas, by taking into account enabled/disabled nullable reference types and enabled/disabled model state validation. The table in [Google Sheets](https://docs.google.com/spreadsheets/d/1er4YxE1An9GEyKeHAGwTN0FlDrbOWi0PNdtw-eIM8wA/edit?usp=sharing) (copy below) supersedes the original table from #1111.

Includes:
- Use the native `NullabilityInfoContext` to check nullability information rather than relying on Swashbuckles work-around (supersedes #1167).
- Take into account if model state validation is enabled/disabled when generating OpenAPI schemas.
- Small tweak in `OpenApiTestContext` to allow for retrieving a swagger file without having to write it to disk.

Closes #1111
Closes #1242

![image](https://github.com/json-api-dotnet/JsonApiDotNetCore/assets/10324372/d5c545bf-80cc-4851-8b71-aed3962dc278)

#### QUALITY CHECKLIST
- [x] Changes implemented in code
- [x] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [x] Adapted tests
- [x] Documentation updated

2022-09-08 00:09 UTC, bkoelman requested changes
Very nice job! The implementation is straightforward and it's easy to verify the tests against what's in https://user-images.githubusercontent.com/9339132/177394179-2943249b-f5f1-4a72-adab-1c1d7ae85fc6.png. The code looks clean with good naming and structure.

The used models remind me of the [Cow and Chicken series](https://www.youtube.com/watch?v=yj3bpF5VPi4) that my younger brother always watched! :)

2022-09-08 00:36 UTC, bkoelman commented
I took the liberty to merge in #1186, I hope you don't mind. However, I was surprised that _running the tests_ changed two swagger.g.json files on disk, _without_ any of the tests failing. That doesn't seem right: when an OAS file changes unexpectedly, something definitely should fail.

2022-12-19 08:11 UTC, maurei commented on test/OpenApiTests/SchemaProperties/NullableReferenceTypesDisabled/ModelStateValidationEnabledTests.cs
> +    public async Task Resource_when_ModelStateValidation_is_enabled_produces_expected_required_property_in_schema()
For the schemas in this test it is relevant that their generation is driven by resources specifically, it was my intent to convey that. With the "when" clause removed that becomes clearer, and I agree that clause can be dropped.

I believe `property` is fine. The term is commonly used for key-value pairs in JSON objects, and it is frequently used in the OpenAPI spec too. It is also consistent with the test folder name.

2022-12-19 08:14 UTC, maurei commented
Review item's I've reacted to are processed in my latest commit. The other ones are related to something I'm still investigating and will follow

2022-12-19 11:57 UTC, bkoelman commented on test/OpenApiTests/SchemaProperties/NullableReferenceTypesDisabled/ModelStateValidationEnabledTests.cs
> +    public async Task Resource_when_ModelStateValidation_is_enabled_produces_expected_required_property_in_schema()
You're right that the terms "property" and "element" are both widely used in JSON and OpenAPI content online. Apparently, this is a case of using multiple terms for the same thing. I prefer we'd use "element" for two reasons:
1. It takes away any ambiguity with .NET properties.
2. The code inside tests refer to "element" for them, because they are typed as `JsonElement`. So using that same terminology in the test name conveys it's about the same thing.

2022-12-19 12:03 UTC, bkoelman commented on test/OpenApiTests/SchemaProperties/NullableReferenceTypesDisabled/ModelStateValidationEnabledTests.cs
> +    public async Task Resource_when_ModelStateValidation_is_enabled_produces_expected_required_property_in_schema()
Related to this, the test named "Produces_expected_nullable_properties_in_schema_for_resource" adds to the terminology confusion. It actually asserts that _elements_ are added, which are named "properties".

2022-12-19 18:53 UTC, maurei commented on test/OpenApiTests/SchemaProperties/NullableReferenceTypesDisabled/ModelStateValidationEnabledTests.cs
> +    public async Task Resource_when_ModelStateValidation_is_enabled_produces_expected_required_property_in_schema()
Here `element` and `property` are not interchangeable. The `property` choice is in line with [Microsoft.OpenApi.Models.OpenApiSchema#Properties](https://github.com/microsoft/OpenAPI.NET/blob/760445cf88cdb6aff00a6ca3a0fd0827f45f91db/src/Microsoft.OpenApi/Models/OpenApiSchema.cs#L165), which is based on the terminology from the corresponding [JSON Schema spec item](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-5.4.4.1), and `element` is not because in that doc it occurs only in the context of arrays. 

The little (imo non-existent) ambiguity with .NET properties here isn't a strong enough reason to break with the laid out  terminology. Also consider the naming of tangent properties like `AdditionalPropertiesAllowed`, `MaxProperties`, `MinProperties`. See also [property set](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-2) where `element` and `property` are used in a non-interchangeable manner.


> So using that same terminology in the test name conveys it's about the same thing.

To me they clearly do not: the test name contains a high-level OAS related term (required property), whereas `element` refers to a low-level technical detail (`JsonElement` clr type), hence _not_ the same. I'll take this confusion out by making no reference to `JsonElement`

2022-12-19 19:02 UTC, maurei commented on test/OpenApiClientTests/SchemaProperties/NullableReferenceTypesDisabled/NullabilityTests.cs
> +    }
Here `element` and `property` are not interchangeable. The choice for `property` comes from [Microsoft.OpenApi.Models.OpenApiSchema#Properties](https://github.com/microsoft/OpenAPI.NET/blob/760445cf88cdb6aff00a6ca3a0fd0827f45f91db/src/Microsoft.OpenApi/Models/OpenApiSchema.cs#L165), which is in accordance with terminology defined in the [JSON Schema spec](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-2) despite of little (imo non-existent) risk of ambiguity, whereas `element` isn't, because in this doc "element" only occurs in the context of collections. Also consider the naming of tangent properties like `AdditionalPropertiesAllowed`, `MaxProperties`, `MinProperties`.

1) 

So unless there is a really strong reason, I don't want to deviate from the standard term here.


Technically, the value in the key-value pair `"required": [ "prop1", "prop2", "prop3" ]` is defined as a [property set](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-2) where the set consists of _elements_. I.e. to refer to this key-value pair as a whole as _element_ mixes up that terminology. 

so `Produces_expected_required_property_in_schema_for_resource` could be improved slightly to `Produces_expected_required_property_set_in_schema_for_resource`



> Related to this, the test named "Produces_expected_nullable_properties_in_schema_for_resource" adds to the terminology confusion. It actually asserts that elements are added, which are named "properties".

"Nullable properties" denotes is high-level functional behaviour (which I think is good to have in the test name), whereas "element" in the test body refers to a technical implementation detail (CLR type `JsonElement`) so I don't think these are confusing. I can make it into "JsonElement", or leave the type name out of the variable.

2022-12-19 19:13 UTC, maurei commented on test/OpenApiClientTests/SchemaProperties/NullableReferenceTypesEnabled/NullabilityTests.cs
> +    }
1,2,3,5: OK

About 4: We shouldn’t inspect the `JsonPropertyAttribute` here because it addresses a completely different testing concern that doesn’t belong to this test suite.

The concern in this test suite is the CLR nullability in the generated source code, i.e. it’s the equivalent of the `GeneratedTypeTests` from the existing test suite. This nullability is in no way affected by `JsonPropertyAttribute` (Such tests are questionable because they don’t test our own code, but we decided to occasionally do so anyway because we’re in very new waters).

Instead, testing `JsonPropertyAttribute` addresses the concern of how `JsonApiClient` behaves at runtime during serialization. But by inspecting this attribute directly it does so only poorly because there are many other factors at play: `DefaultValueHandling`, `NullValueHandling`, how the `JsonApiClient` is called, etc. Instead this should be tested jointly in a behavioural test, which probes these attributes in their relevant context. That’s what happens in `RequiredAttributesTests`.

2022-12-19 19:14 UTC, maurei commented on test/OpenApiClientTests/SchemaProperties/NullableReferenceTypesEnabled/NullabilityTests.cs
> +    }
I’m currently working out a more rigorous test suite that will replace RequiredAttributesTests with a similar suite that covers more scenarios. This will further capture the runtime behaviour of `JsonApiClient`. 

For these changes I will make a PR into this branch to allow for better reviewability

2022-12-19 19:19 UTC, maurei commented on test/OpenApiTests/SchemaProperties/NullableReferenceTypesDisabled/ModelStateValidationEnabledTests.cs
> +public sealed class ModelStateValidationEnabledTests
Initially I thought it could be neglected for that precise reason. 

But now I think it is useful and complete to demonstrate that those attributes which cannot be omitted during a POST request, can be omitted during a PATCH request.

2022-12-20 13:14 UTC, maurei commented on test/OpenApiClientTests/SchemaProperties/NullableReferenceTypesDisabled/RequiredAttributesTests.cs
> +        await action.Should().ThrowAsync<JsonSerializationException>();
This will be superseded by a test in #1231.

2022-12-20 13:28 UTC, maurei commented
> I took the liberty to merge in #1186, I hope you don't mind. However, I was surprised that _running the tests_ changed two swagger.g.json files on disk, _without_ any of the tests failing. That doesn't seem right: when an OAS file changes unexpectedly, something definitely should fail.

Haven't been able to reproduce this.  Compared two fresh clones of this branch where in only one of them I ran the tests

2022-12-20 15:10 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceFieldObjectSchemaBuilder.cs
> +    private static bool IsDataPropertyNullableInRelationshipSchemaType(Type relationshipSchemaType)
It's true that relationships require equally thorough test suites as we have for attributes for both server-side OAS generation (like in this PR) as well as client-side request behaviour (like in #1231).  I didn't really realise that until later because the code changes here `JsonApiDotNetCore.OpenApi` exclusively target support for `nullable`/`required` for attributes, not relationships.

So, indeed, this is the logical next step after the current work on attributes is finished.

2022-12-20 15:19 UTC, maurei commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceFieldObjectSchemaBuilder.cs
> +    private static bool IsDataPropertyNullableInRelationshipSchemaType(Type relationshipSchemaType)
For equally rigorous relationship tests, we'll need `Chicken`/`Cow` models that have 4 to 8 relationship properties.

I would like to propose to _not_ use `Chicken`/`Cow` for this, because this will cause the overviews in #1111 and #1231 to explode and be hard to follow, and same for the associated test suites. Especially the client tests will become very verbose and complicated. Eg all attribute related request body declarations will need a lot of redundant relationship data, and conversely.

Instead, I would like to propose to have `SchemaProperties/AttributesObject` tests and `SchemaProperties/RelationshipObjects` tests with dedicated models. Relationships and attributes behave differently so can be seen as separate concerns. This will keep it grouped by those concern.

Given that it wouldn't overlap, it could go in a separate PR dedicated for relationships, and keep this one for attributes

2022-12-28 23:34 UTC, maurei commented
@bkoelman there are tests failing due to timeouts unrelated to this PR. It seems to happens during the test cleanup phase which you recently worked on. Do you have any idea what could be causing this?

See for example https://ci.appveyor.com/project/json-api-dotnet/jsonapidotnetcore/builds/45792318/job/l2grxineggemqslq#L317

2023-09-30 13:42 UTC, bkoelman commented on test/OpenApiTests/SchemaProperties/NullableReferenceTypesDisabled/ModelStateValidationEnabledTests.cs
> +    public async Task Resource_when_ModelStateValidation_is_enabled_produces_expected_required_property_in_schema()
I agree we should stick with the OpenAPI terminology in test names. The JSON elements are an implementation detail, which only applies _when choosing the JSON file format_. It makes no sense for the YAML file format. This matches the guideline that tests should state a rule, whose implementation is based on an example (using JSON in this case).

2023-09-30 13:49 UTC, bkoelman commented on test/OpenApiClientTests/SchemaProperties/NullableReferenceTypesEnabled/NullabilityTests.cs
> +    }
Closing, all concerns have been addressed.

2023-09-30 13:50 UTC, bkoelman commented on test/OpenApiClientTests/SchemaProperties/NullableReferenceTypesDisabled/NullabilityTests.cs
> +    }
The suggestion is outdated, however, the underlying concerns have been addressed.

2023-09-30 13:59 UTC, bkoelman commented on test/OpenApiClientTests/SchemaProperties/NullableReferenceTypesDisabled/RequiredAttributesTests.cs
> +        await action.Should().ThrowAsync<JsonSerializationException>();
Closing, this has been addressed.

2023-09-30 14:20 UTC, bkoelman commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceFieldObjectSchemaBuilder.cs
> +    private static bool IsDataPropertyNullableInRelationshipSchemaType(Type relationshipSchemaType)
@maurei It looks like this is now implemented for create/update resource endpoints (see OpenApiTests...NullabilityTests/RequiredTests and OpenApiClientTests...CreateResourceTests/UpdateResourceTests), but not yet for relationship endpoints. Can you confirm?

2023-10-01 00:33 UTC, bkoelman commented on test/OpenApiClientTests/SchemaProperties/NullableReferenceTypesDisabled/RequiredAttributesTests.cs
> +public sealed class RequiredAttributesTests
Closing, it looks like all cases have been addressed.

2023-10-09 19:03 UTC, bkoelman commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/ResourceFieldObjectSchemaBuilder.cs
> +    private static bool IsDataPropertyNullableInRelationshipSchemaType(Type relationshipSchemaType)
Discussed offline: these use the same OAS schemas, so not relevant to test separately.

2023-10-09 19:04 UTC, bkoelman approved these changes

2023-10-09 19:15 UTC, merged