Relationship capabilities and bugfixes
json-api-dotnet/JsonApiDotNetCore pull request #1197
Opened 2022-10-01 17:31 UTC by bkoelman

Adds the equivalent of `AttrCapabilities` for relationships. See #1187 for design considerations.
This PR fixes some small bugs.

Closes #1187.
Closes #1196.
Closes #1195.

#### QUALITY CHECKLIST
- [x] Changes implemented in code
- [x] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [x] Adapted tests
- [x] Documentation updated

2022-10-01 18:00 UTC, bkoelman commented
This PR has a dependency on #1192. If that one is merged earlier, this PR needs additional changes.

2022-10-19 14:43 UTC, maurei requested changes

2022-10-19 15:32 UTC, bkoelman commented on docs/usage/resources/relationships.md
> +@JsonApiDotNetCore.Configuration.JsonApiOptions#JsonApiDotNetCore_Configuration_JsonApiOptions_DefaultHasManyCapabilities:
Thanks. I'm going to try this locally first, to see if the DocFx accepts it.

2022-10-19 17:04 UTC, bkoelman commented on docs/usage/resources/relationships.md
> +@JsonApiDotNetCore.Configuration.JsonApiOptions#JsonApiDotNetCore_Configuration_JsonApiOptions_DefaultHasManyCapabilities:
Nope, that doesn't work:

![image](https://user-images.githubusercontent.com/10324372/196757461-ebbccec3-c8a3-40a8-84cd-2aeec27698f0.png)

2022-10-20 07:10 UTC, maurei commented on docs/usage/resources/relationships.md
> +@JsonApiDotNetCore.Configuration.JsonApiOptions#JsonApiDotNetCore_Configuration_JsonApiOptions_DefaultHasManyCapabilities:
I see what it was supposed to do now :)

2022-10-20 07:11 UTC, maurei approved these changes

2022-10-20 07:11 UTC, merged