Fix missing HttpContext on ValidationContext during atomic operations
json-api-dotnet/JsonApiDotNetCore pull request #1251
Opened 2023-01-30 18:48 UTC by Tommy228

Closes #{ISSUE_NUMBER}

#### QUALITY CHECKLIST
- [ ] Changes implemented in code
- [ ] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [ ] Adapted tests
- [ ] Documentation updated

2023-01-31 01:40 UTC, bkoelman commented
Hi @Tommy228, thanks for your contribution! I intend to look at it somewhere this week.

2023-01-31 12:33 UTC, bkoelman reviewed
Thanks for carefully adhering to our code style and naming conventions. See comments below.

2023-01-31 12:33 UTC, bkoelman commented on test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/ModelStateValidation/AtomicModelStateValidationTests.cs
> +        error.Source.Should().BeNull();
The source pointer isn't populated because the custom validator acts on the `MusicTrack` class, instead of the `ReleasedAt` property.

By using the approach below, the source pointer does get populated (and the validation becomes reusable):
```c#
public sealed class MusicTrack : Identifiable<Guid>
{
    [Attr]
    [DateMustBeInThePast]
    public DateTimeOffset ReleasedAt { get; set; }
}

[AttributeUsage(AttributeTargets.Property)]
internal sealed class DateMustBeInThePastAttribute : ValidationAttribute
{
    protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
    {
        var targetedFields = validationContext.GetRequiredService<ITargetedFields>();

        if (targetedFields.Attributes.Any(attribute => attribute.Property.Name == validationContext.MemberName))
        {
            PropertyInfo propertyInfo = validationContext.ObjectType.GetProperty(validationContext.MemberName!)!;

            if (propertyInfo.PropertyType == typeof(DateTimeOffset) || propertyInfo.PropertyType == typeof(DateTimeOffset?))
            {
                var typedValue = (DateTimeOffset?)propertyInfo.GetValue(validationContext.ObjectInstance);
                var systemClock = validationContext.GetRequiredService<ISystemClock>();

                if (typedValue >= systemClock.UtcNow)
                {
                    return new ValidationResult($"{validationContext.MemberName} must be in the past.");
                }
            }
        }

        return ValidationResult.Success;
    }
}
```
Which results in:
```json
"status": "422",
"title": "Input validation failed.",
"detail": "ReleasedAt must be in the past.",
"source": {
  "pointer": "/atomic:operations[0]/data/attributes/releasedAt"
}
```

2023-01-31 12:33 UTC, bkoelman commented on test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/ModelStateValidation/AtomicModelStateValidationTests.cs
> +            services.AddSingleton<IReleasedAtValidator, ReleasedAtValidator>().AddSingleton<ISystemClock, SystemClock>());
Assuming this is going to stay, please put the two registrations in individual statements. It makes it easier to spot the dependencies.

2023-01-31 12:33 UTC, bkoelman commented on test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/Validation/ReleasedAtValidator.cs
> +public sealed class ReleasedAtValidator : IReleasedAtValidator
Assuming these types are going to stay, please move them up one directory. We try to use the subdirectories for the tests and put shared files above them.

2023-01-31 15:25 UTC, Tommy228 commented on test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/ModelStateValidation/AtomicModelStateValidationTests.cs
> +        error.Source.Should().BeNull();
You're right, that's a much better approach! And it will still test that the dependency injection is working properly. I'll update the PR according to this.

2023-02-01 11:02 UTC, bkoelman requested changes

2023-02-01 12:05 UTC, Tommy228 commented on test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/Creating/AtomicCreateResourceTests.cs
> +            services.AddSingleton<ISystemClock, SystemClock>();
No worries. This is what I would usually do with `FakeClock` using `NodaTime`. I didn’t bother with it for this test but it’s definitely the good practice. I’ll update the PR later this day .

2023-02-04 12:04 UTC, bkoelman approved these changes

2023-02-04 12:04 UTC, merged