Document JsonApiEndpoints enum
json-api-dotnet/JsonApiDotNetCore pull request #1301
Opened 2023-08-20 19:55 UTC by verdie-g

Closes #1298

#### QUALITY CHECKLIST
- [X] Changes implemented in code
- [X] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [X] Adapted tests
- [X] Documentation updated

2023-08-21 19:21 UTC, bkoelman commented
Thanks. I'll get back to this next month, after my break.

2023-09-02 11:05 UTC, bkoelman requested changes
Please note the line at the top of this file:
```
// IMPORTANT: An internal copy of this type exists in the SourceGenerators project. Keep these in sync when making changes.
```

These changes should be replicated in the other file.

2023-09-03 22:27 UTC, bkoelman requested changes

2023-09-03 22:27 UTC, bkoelman commented on src/JsonApiDotNetCore.Annotations/Controllers/JsonApiEndpoints.shared.cs
> +    /// ]]></code>
Did you intentionally leave out the second example? See https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/JsonApiDotNetCore/Controllers/BaseJsonApiController.cs#L126-L133.

2023-09-03 22:27 UTC, bkoelman commented on src/JsonApiDotNetCore.Annotations/Controllers/JsonApiEndpoints.shared.cs
> +    /// Represents the endpoint to creates a new resource with attributes, relationships or both. Example:
```suggestion
    /// Represents the endpoint to create a new resource with attributes, relationships or both. Example:
```

2023-09-04 14:06 UTC, verdie-g commented
The CI error is weird, I did run cleanupcode 🤔

2023-09-04 21:50 UTC, bkoelman commented
> The CI error is weird, I did run cleanupcode 🤔

Strange indeed. Running locally on Windows does not produce a diff. I haven't seen this happen before, will investigate. What OS are you using?

2023-09-04 22:10 UTC, verdie-g commented
Windows 11 and
```
$ dotnet --info
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  6.0.413 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

2023-09-04 22:11 UTC, verdie-g commented
Could it be a line-ending thing? Maybe locally I'm using CRLF and the CI is using LF the number of characters on the line is different?

2023-09-07 20:42 UTC, bkoelman commented
> Could it be a line-ending thing? Maybe locally I'm using CRLF and the CI is using LF the number of characters on the line is different?

Yes, but I don't think that should matter. It has always worked that way. I've created a temporary PR #1304 to investigate.

2023-09-21 00:49 UTC, bkoelman commented
@verdie-g Sorry this is taking so long. I've opened a bug at https://youtrack.jetbrains.com/issue/RSRP-494002, but it hasn't been triaged yet.

Meanwhile, can you please merge or rebase on the latest changes in master? I've replaced AppVeyor with GitHub Actions. This is a nice opportunity to test whether everything works from a community PR. I can't do it myself because my account has write permissions and I'd like to confirm builds work without that. Sadly, it won't fix the cleanupcode bug though.

2023-09-22 14:12 UTC, verdie-g commented
Looks like it's failing for macos

2023-09-22 17:02 UTC, bkoelman commented
> Looks like it's failing for macos

Yes, same as linux.

2023-11-09 03:21 UTC, closed without merging

2023-11-09 16:59 UTC, bkoelman commented
@verdie-g I'd like to keep this PR open. I suspect this was closed unintentionally as a side effect of deleting your fork. I'me unable to reopen because your fork no longer exists. Can you restore it?

We still want to take this PR. The related issue has been triaged with priority critical, so I have high hopes a fix will become available soon.

2023-11-09 17:22 UTC, verdie-g commented
I completely forgot about that PR. I'll try restoring the fork when I get some time.

2023-12-15 09:19 UTC, bkoelman commented
Superseded by #1423.