openapi: include ETag/Location headers
json-api-dotnet/JsonApiDotNetCore pull request #1459
Opened 2024-02-07 23:56 UTC by verdie-g

Closes #1367

#### QUALITY CHECKLIST
- [X] Changes implemented in code
- [X] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [X] Adapted tests
- [ ] Documentation updated

How can I regenerate this file https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/openapi/src/Examples/JsonApiDotNetCoreExample/GeneratedSwagger/JsonApiDotNetCoreExample.json?

2024-02-07 23:57 UTC, verdie-g commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiOperationDocumentationFilter.cs
> +        {
Might need to add Required=true here if required in this context means that it will always be present.

2024-02-08 00:15 UTC, verdie-g commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiOperationDocumentationFilter.cs
> +        {
Found my answer here https://github.com/OAI/OpenAPI-Specification/issues/321#issuecomment-284074270

2024-02-08 05:36 UTC, verdie-g commented
This change does make the header appear in the OpenAPI document but the swagger generation remains the same. The reason is that the methods of the generated clients only return the deserialized body. I think an option must be enabled to actually return an object with status code and headers (https://github.com/RicoSuter/NSwag/issues/3557#issuecomment-922370812).

2024-02-08 22:21 UTC, verdie-g commented
![image](https://github.com/json-api-dotnet/JsonApiDotNetCore/assets/9092290/a6b8f22e-c505-488c-84a3-a8f4f9a9eefe)

An NSwag method looks like that
![image](https://github.com/json-api-dotnet/JsonApiDotNetCore/assets/9092290/9d82e586-d8aa-4b8f-8406-b01e020dfa4f)
The argument name `if_None_Match` is not great but what's even less great are these lines
```cs
if (status_ == 304)
{
    string responseText_ = ( response_.Content == null ) ? string.Empty : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
    throw new ApiException("The resource was not modified.", status_, responseText_, headers_, null);
}
```
It throws on 403. Though, I'm not sure what would be a better behavior.

2024-02-10 10:30 UTC, bkoelman commented
> The argument name if_None_Match is not great

Can we use https://github.com/RicoSuter/NSwag/issues/808 somehow?

> It throws on 403

We have https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/openapi/src/JsonApiDotNetCore.OpenApi.Client/ApiResponse.cs for that; probably needs to be adapted to handle 403 as well.

I've clarified the description in the original issue. For NSwag, we may even provide our own ResponseClass (pass `/GenerateResponseClasses:false`) if that smoothens the caching experience. For Kiota, see https://learn.microsoft.com/en-us/openapi/kiota/query-parameters-request-headers#request-headers and https://github.com/microsoft/kiota/issues/2963.

2024-02-13 00:38 UTC, verdie-g commented
> Can we use https://github.com/RicoSuter/NSwag/issues/808 somehow?

Probably but I'm not sure we can use by just passing a command line option so maybe that will fall outside of the scope of the PR.

Also I'm so confused about how clients are generated.

This code clones the repo, makes a change and can't find that change in the generate clients. What am I missing?
```bash
git clone git@github.com:json-api-dotnet/JsonApiDotNetCore.git test
cd test
git checkout openapi
dotnet build

sed -i 's/"query"/"hello"/' src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiOperationDocumentationFilter.cs
dotnet build

grep hello test/OpenApiClientTests/obj/OpenApiClient.cs # nothing

dotnet clean
dotnet build

grep hello test/OpenApiClientTests/obj/OpenApiClient.cs # nothing

git clean -fdx
dotnet clean
dotnet build

grep hello test/OpenApiClientTests/obj/OpenApiClient.cs # nothing
grep hello test/OpenApiEndToEndTests/obj/QueryStringsClient.cs # nothing
```

2024-02-13 07:54 UTC, bkoelman commented
> > Can we use [RicoSuter/NSwag#808](https://github.com/RicoSuter/NSwag/issues/808) somehow?
> 
> Probably but I'm not sure we can use by just passing a command line option so maybe that will fall outside of the scope of the PR.

I don't understand, can you clarify?

> Also I'm so confused about how clients are generated.

When building project OpenApiTests, your changes from JsonApiDotNetCore.OpenApi are compiled. When _running the tests_ in OpenApiTests, it writes updated `swagger.json` into the OpenApiClientTests and/or OpenApiEndToEndTests test project (for example, [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/openapi/test/OpenApiTests/QueryStrings/QueryStringTests.cs#L19)). When adding Kiota support, I'd like to change that to output into the server-test project itself, so that multiple clients can reference it.

When building JsonApiDotNetCoreExample, it starts the webserver and writes `GeneratedSwagger/JsonApiDotNetCoreExample.json` (which is consumed by JsonApiDotNetCoreExampleClient) because of [this line](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/openapi/src/Examples/JsonApiDotNetCoreExample/JsonApiDotNetCoreExample.csproj#L4). Turn it off when the JsonApiDotNetCore.OpenApi produces something broken, so you can run the example project and debug it.

2024-02-13 08:05 UTC, bkoelman commented
Also, NSwag doesn't always detect changes properly. For example, if project options have changed but the source swagger.json has not, it won't regenerate. Delete the `obj` directory in the client project to workaround that.

2024-02-14 01:37 UTC, verdie-g commented
> Delete the obj directory in the client project to workaround that.

Oh that's it thanks.

> We have https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/openapi/src/JsonApiDotNetCore.OpenApi.Client/ApiResponse.cs for that; probably needs to be adapted to handle 403 as well.

Though I'm not sure what to return in that case. I've generated a response object to be able to get the response headers (e.g. ETag) so maybe it could return `{ status: 403, headers: /* ... */, data: null }` and the user should know that if status is 403 then data will be null.

> I don't understand, can you clarify?

NSwag clients are generated using a command line from the csproj. How can I pass an implementation of IParameterNameGenerator there 🤔

2024-02-16 23:48 UTC, bkoelman commented
@verdie-g Looking at your last commit message, you may have faced the same mystery as I did this week. See #1463.

2024-02-17 00:15 UTC, verdie-g commented
Oh actually I think I just didn't know anymore what I changed so I wrote some random message.

2024-02-17 01:43 UTC, bkoelman commented
Thanks for looking into all these details. You're on the right track. Sorry if this turned out more complicated than I initially imagined, I appreciate you're not giving up.

> > I don't understand, can you clarify?
> 
> NSwag clients are generated using a command line from the csproj. How can I pass an implementation of IParameterNameGenerator there 🤔 I think a custom generator needs to be created like in here https://github.com/daveaglick/NetlifySharp/blob/main/tools/NetlifySharp.Generator/Program.cs.

Thanks, I understand now. It goes a bit too far to build our own generator for this, so let's just stick with `if_None_Match`. Feel free to open an issue in the NSwag repo with a request to add a switch to adhere to the C# naming conventions.

> > We have https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/openapi/src/JsonApiDotNetCore.OpenApi.Client/ApiResponse.cs for that; probably needs to be adapted to handle 403 as well.
> 
> Though I'm not sure what to return in that case. I've generated a response object to be able to get the response headers (e.g. ETag) so maybe it could return `{ status: 403, headers: /* ... */, data: null }` and the user should know that if status is 403 then data will be null.

I propose to extend the `ApiResponse` class in JADNC.OpenApi.Client project in the following way:
- Add classes `ApiResponse` and `ApiResponse<>`, similar to what NSwag generates. I don't think the name JsonApiResponse is appropriate, as it contains nothing specific to JSON:API.
- Extend existing methods to respond to `304` and return `null`.
- Add new methods (for returning void and T) for wrapped responses (a user may choose to use them or not), ie:
    ```c#
    public static async Task<ApiResponse<T?>> TranslateWrappedAsync<T>(Func<Task<ApiResponse<T>>> operation)
        where T : class
    {
        try
        {
            ApiResponse<T> response = await operation();
            return new ApiResponse<T?>(response.StatusCode, response.Headers, response.Result);
        }
        catch (ApiException exception) when (exception.StatusCode == (int)HttpStatusCode.NotModified)
        {
            return new ApiResponse<T?>(exception.StatusCode, exception.Headers, null);
        }
    }
    ```
- Move `ApiException` outside of the `.Exceptions` namespace, so we'll only need a single `/AdditionalNamespaceUsages` switch.

2024-02-17 01:44 UTC, bkoelman requested changes
Aside from comments, remaining things to address:
- https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1459#issuecomment-1949582165
- End-to-end tests (subset of what's in `ETagTests.cs`)
- Possibly update sample to show how ETag works, ie: call wrapped `GetPersonCollectionAsync`, capture ETagfrom header, call again with that ETag, and observe the result is `null` with status 304.
- Document the (optional) use of `/WrapResponses:true /GenerateResponseClasses:false` in docs/usage/openapi.md
- Try if it works with Kiota (no commit needed, but would be nice if you can add some working code in a PR comment so I can integrate it later)

2024-02-17 01:44 UTC, bkoelman commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiOperationDocumentationFilter.cs
> +            Description = "Size of the response body in bytes",
Suggestion:
> Size of the HTTP response body, in bytes.

2024-02-17 01:44 UTC, bkoelman commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiOperationDocumentationFilter.cs
> +            Description = "ETag identifying the version of the requested resource.",
Suggestion:
> A list of ETags, resulting in HTTP status 304 without a body, if one of them matches the current fingerprint.

2024-02-17 01:44 UTC, bkoelman commented on test/OpenApiClientTests/OpenApiClientTests.csproj
> +      <Options>/GenerateClientInterfaces:true /ClientClassAccessModifier:internal /GenerateExceptionClasses:false /GenerateOptionalParameters:true /AdditionalNamespaceUsages:JsonApiDotNetCore.OpenApi
I'd rather not have this switch added in test projects. While it leads to shorter code, it also hides potential errors when a new parameter gets added that wasn't intended.

2024-02-17 01:44 UTC, bkoelman commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiOperationDocumentationFilter.cs
> +            Required = false,
Isn't `false` the default? If so, this line can be omitted.

2024-02-17 01:44 UTC, bkoelman commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiOperationDocumentationFilter.cs
> +    private static void AddHeaderParameterIfNoneMatch(OpenApiOperation operation)
Should probably be named `AddRequestHeaderIfNoneMatch` for consistency with the other added methods).

2024-02-17 01:44 UTC, bkoelman commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiOperationDocumentationFilter.cs
> +                Type = "string"
I wonder if anything would break if we added `format: uri` (see https://swagger.io/docs/specification/data-models/data-types/#format). Note that the value we emit today is always a relative URI, but that may change. 

Actually, I think it would be more correct to take `JsonApiOptions.UseRelativeLinks` into account, but that change needs to happen in the master branch, so out of scope of this PR.

2024-02-17 18:29 UTC, verdie-g commented on src/Examples/JsonApiDotNetCoreExampleClient/Program.cs
> +static Task<JsonApiResponse<PersonCollectionResponseDocument>> GetPersonCollectionAsync(ExampleApiClient apiClient, string? ifNoneMatch = null)
I'm calling it twice so it's just to avoid copying the code.

2024-02-17 18:34 UTC, verdie-g commented
> Document the (optional) use of /WrapResponses:true /GenerateResponseClasses:false in docs/usage/openapi.md

Hmm I was expecting to see a NSwag section there, not sure what to add.

> Try if it works with Kiota (no commit needed, but would be nice if you can add some working code in a PR comment so I can integrate it later)

I don't think I'll have the time/energy to test with Kiota. Though this library looks promising.

2024-02-18 00:14 UTC, bkoelman requested changes
Please update this PR to the latest version of the base branch.

2024-02-18 00:14 UTC, bkoelman commented on test/OpenApiEndToEndTests/QueryStrings/ETagTests.cs
> +namespace OpenApiEndToEndTests.QueryStrings;
These tests don't really belong here. Ideally, they would live in OpenApiEndToEndTests.Headers, with their own separate model, DbContext and fakers, unrelated to query string client tests. I'm not so happy to see this PR requires changes to all the query string test cases in this project. Those should not use wrap-response syntax.

Can you come up with a separate sample model and isolate it?

2024-02-18 06:58 UTC, verdie-g commented on test/OpenApiTests/Headers/HeaderTests.cs
> +        return _testContext.GetSwaggerDocumentAsync();
There is probably a better way to do that

2024-02-18 16:25 UTC, bkoelman commented
For future reference, here's what the sample looks like using Kiota:
```c#
var headerInspector = new HeadersInspectionHandlerOption
{
    InspectResponseHeaders = true
};

PersonCollectionResponseDocument? getResponse1 = await client.Api.People.GetAsync(
    configuration => configuration.Options.Add(headerInspector));

string eTag = headerInspector.ResponseHeaders["ETag"].Single();

try
{
    PersonCollectionResponseDocument? getResponse2 = await client.Api.People.GetAsync(
        configuration => configuration.Headers.Add("If-None-Match", eTag));
}
catch (ApiException exception) when (exception.ResponseStatusCode == (int)HttpStatusCode.NotModified)
{
    Console.WriteLine("The HTTP response hasn't changed, so no response body was returned.");
}
```
The try/catch is needed due to a bug in Kiota: it fails to map the 304 status, despite being in the OAS.

2024-02-18 16:25 UTC, bkoelman requested changes

2024-02-18 16:35 UTC, bkoelman commented
Please add `HttpStatusCode.NotModified` to the appropriate entries in `OpenApiEndpointConvention.GetSuccessStatusCodesForEndpoint`, so that status codes are ordered alphabetically in the OAS document.

2024-02-19 22:58 UTC, verdie-g commented on test/OpenApiEndToEndTests/OpenApiEndToEndTests.csproj
> +      <Options>/ClientClassAccessModifier:internal /GenerateExceptionClasses:false /WrapResponses:true /GenerateResponseClasses:false /ResponseClass:ApiResponse /AdditionalNamespaceUsages:JsonApiDotN
It seems like the default value is `SwaggerResponse`.

2024-02-19 23:04 UTC, verdie-g commented on test/OpenApiTests/Headers/HeaderTests.cs
> +        return _testContext.GetSwaggerDocumentAsync();
Isn't it what `DocCommentsTests.cs` is already testing?

2024-02-20 07:24 UTC, bkoelman commented on test/OpenApiTests/Headers/HeaderTests.cs
> +        return _testContext.GetSwaggerDocumentAsync();
Partly, yes. You probably noticed that simple changes cause a lot of churn in many OAS files. We're set up like that _currently_ because we'd like to be notified of any impact (and potential undesired side effects) of structural changes. As the number of tests grows, this becomes a burden. The vision is to move these files under `.gitignore` in the future, after we have established good test coverage.

So we need test coverage that asserts on all the bits and pieces we expect to be produced. For headers, this means producing the right headers at the expected places, but also that they don't occur at places where they shouldn't be. `DocCommentsTests` focuses on the documentation only (and in order to do that, it needs to reference a location in the OAS). If we were to turn off doc-comments, headers still need to be produced at the right places and with the right details. That's what these tests are for.

I think that `DocCommentsTests` will go away in the future, as well as (most of) `JsonApiOperationDocumentationFilter`. It was my first contribution after picking up from Maurits, and I'm still learning. In hindsight, I think the documentation should be generated at the places where nodes are produced, not afterward in a post-processing step as it is now. Producing documentation in all the right places isn't much of a feature itself, but merely an aspect. As test coverage grows, we should probably move these assertions there, as those tests already assert on the location where these nodes need to be.

This is my current thinking, which may change over time. This is not all set in stone and I'm open to new ideas. It's hard to know upfront how OpenAPI tests are best organized. So unfortunately, we may be doing work today that's going to disappear eventually. That's frustrating sometimes, but I don't see any other way that enables us to confidently refactor internals, knowing that the required test coverage is in place.

2024-02-20 14:58 UTC, verdie-g commented on test/OpenApiTests/Headers/HeaderTests.cs
> +        return _testContext.GetSwaggerDocumentAsync();
Alright, I'll work do that later in the day.

2024-02-21 06:07 UTC, bkoelman requested changes
Looks good, minor comments aside.

2024-02-21 06:07 UTC, bkoelman commented on test/OpenApiTests/Headers/HeaderTests.cs
> +    public async Task Get_and_head_endpoints_have_caching_headers(string endpointPath)
I don't think the test name should include the inputs it is being used with.
```suggestion
    public async Task Endpoints_have_caching_headers(string endpointPath)
```

2024-02-21 06:07 UTC, bkoelman commented on test/OpenApiTests/Headers/HeaderTests.cs
> +    public async Task Post_patch_and_delete_endpoints_do_not_have_caching_headers(string endpointPath)
```suggestion
    public async Task Endpoints_do_not_have_caching_headers(string endpointPath)
```

2024-02-21 06:07 UTC, bkoelman commented on test/OpenApiTests/Headers/HeaderTests.cs
> +    public async Task Head_endpoints_have_content_length_response_header(string endpointPath)
```suggestion
    public async Task Endpoints_have_content_length_response_header(string endpointPath)
```

2024-02-21 06:07 UTC, bkoelman commented on test/OpenApiTests/Headers/HeaderTests.cs
> +        document.Should().ContainPath($"paths.{endpointPath}.responses.201.headers.Location").With(locationElement =>
```suggestion
        document.Should().ContainPath("paths./countries.post.responses.201.headers.Location").With(locationElement =>
```

2024-02-21 06:07 UTC, bkoelman commented on test/OpenApiTests/Headers/HeaderTests.cs
> +    public async Task Post_endpoints_have_location_response_header(string endpointPath)
```suggestion
    public async Task Post_resource_endpoint_has_location_response_header()
```

2024-02-22 01:30 UTC, bkoelman requested changes
Final round of review. Thanks for all the hard work!
I'll propose something to add to the docs; with that included, this looks ready for merge.
Meanwhile, can you update the PR description, with an updated SwaggerUI screenshot?

2024-02-22 01:30 UTC, bkoelman commented on src/JsonApiDotNetCore.OpenApi/SwaggerComponents/JsonApiOperationDocumentationFilter.cs
> +            Description = "The URL at which the newly created JSON:API resource can be retrieved.",
I suddenly realized this looks inconsistent:

![image](https://github.com/json-api-dotnet/JsonApiDotNetCore/assets/10324372/7ab613d2-a49e-4407-aca7-5f505248b285)

To fix this, this method needs to take the `singularName` value from the caller as a parameter.

2024-02-22 01:30 UTC, bkoelman commented on test/OpenApiTests/LegacyOpenApiIntegration/swagger.json
> +            "additionalProperties": {},
I wonder why this changed? Don't copy/paste the file contents in your IDE to sync up, because that reformats the file. Instead, copy the file itself.

2024-02-22 18:24 UTC, verdie-g commented on test/OpenApiTests/LegacyOpenApiIntegration/swagger.json
> +            "additionalProperties": {},
I copy the actual result from the test failure output. How do you do it?

2024-02-22 22:22 UTC, bkoelman commented on test/OpenApiTests/LegacyOpenApiIntegration/swagger.json
> +            "additionalProperties": {},
I have a desktop shortcut to a .bat file containing:
```
copy /Y C:\Source\Repos\JsonApiDotNetCore\test\OpenApiClientTests\LegacyClient\swagger.g.json C:\Source\Repos\JsonApiDotNetCore\test\OpenApiTests\LegacyOpenApiIntegration\swagger.json
```

2024-02-23 00:56 UTC, verdie-g commented
I'm not committing the suggestions one by one ever again :D

2024-02-23 02:21 UTC, bkoelman commented
> I'm not committing the suggestions one by one ever again :D

I'd welcome that. You can batch them into a single commit from the **Files changed** tab.

I've created a suggestion to update the docs, see the diff at https://github.com/json-api-dotnet/JsonApiDotNetCore/compare/openapi...openapi-header-docs. Probably just easiest for you to cherry-pick the commit, assuming you agree with the change.

2024-02-23 02:27 UTC, verdie-g commented
> You can batch them into a single commit from the Files changed tab.

Good to know.

> Probably just easiest for you to cherry-pick the commit

Done

2024-02-23 15:14 UTC, bkoelman commented on test/OpenApiTests/Headers/HeaderFakers.cs
> +        .RuleFor(textLanguage => textLanguage.Code, faker => faker.PickRandom(LazyLanguageCodes.Value)));
~textLanguage~ language

2024-02-23 15:16 UTC, bkoelman commented on test/OpenApiTests/Headers/HeaderFakers.cs
> +        .GetCultures(CultureTypes.NeutralCultures)
Executing multiple times is okay, these appear to be cached internally.
```
CultureInfo.GetCultures ...  0:00:00:00.0158958
CultureInfo.GetCultures ...  0:00:00:00.0001816
CultureInfo.GetCultures ...  0:00:00:00.0001518
```

2024-02-23 16:37 UTC, bkoelman commented on test/OpenApiEndToEndTests/Headers/ETagTests.cs
> +        Country country = _fakers.Country.Generate();
Oh, I was partially wrong here. Don't extract into separate variables, but do use the `new` prefix. Sorry for the confusion.

2024-02-23 20:48 UTC, bkoelman commented on test/OpenApiEndToEndTests/Headers/ETagTests.cs
> +        Country newCountry = _fakers.Country.Generate();
```suggestion
        Country newCountry = _fakers.Country.Generate();

```

2024-02-23 20:49 UTC, bkoelman approved these changes

2024-02-23 21:07 UTC, merged