openapi: support client-generated id
json-api-dotnet/JsonApiDotNetCore pull request #1475
Opened 2024-02-23 04:29 UTC by verdie-g

Closes #1054 

#### QUALITY CHECKLIST
- [ ] Changes implemented in code
- [ ] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [ ] Adapted tests
- [ ] Documentation updated

2024-02-23 04:30 UTC, verdie-g commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = null!, // FIXME: passing "" here works fine 🤔
Is that expect?

2024-02-23 04:30 UTC, verdie-g commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +        // Probably not what we want.
Any idea how to write that test correctly?

2024-02-23 04:30 UTC, verdie-g commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = game.StringId!, // FIXME: StringId is null, how to generate an id?
How can I generate an id here?

2024-02-23 04:31 UTC, verdie-g commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = null!, // FIXME: incorrect nullability here
Because `ClientIdGenerationMode.Allowed` is used, I think `Id` should be nullable.

2024-02-23 04:31 UTC, verdie-g commented
@bkoelman could you help with the those comments 👆

2024-02-23 16:24 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = null!, // FIXME: passing "" here works fine 🤔
Interesting! I've debugged it down to `RuntimeTypeConverter`, which returns the target type's default value for an empty string. And there are tests for that behavior. However, I have no idea _why_ it works like that. It was introduced in #139, all the way back in 2017.

When removing that behavior, all the tests are still green. However this is a very risky thing to change.

@maurei does this ring any bells? What's happening here is that a client sends `"data": { "id": "", ... }` in a post resource request, with the configuration that client-generated IDs are required.

2024-02-23 16:33 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +        // Probably not what we want.
This is Newtonsoft intentionally failing, because OAS defines the property as required, so NSwag generates the appropriate Newtonsoft attributes to reflect that. Similar to https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/openapi/test/OpenApiClientTests/ResourceFieldValidation/NullableReferenceTypesOn/ModelStateValidationOn/CreateResourceTests.cs#L158.

2024-02-23 16:36 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = game.StringId!, // FIXME: StringId is null, how to generate an id?
By assigning a value right after the faker created an instance. Similar to https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/test/JsonApiDotNetCoreTests/IntegrationTests/ReadWrite/Creating/CreateResourceWithClientGeneratedIdTests.cs#L36.

However, it's very unlikely to use client-generated IDs with `long` identifiers. More representative would be to use GUIDs.

2024-02-23 16:40 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = null!, // FIXME: incorrect nullability here
No, because sending `"id": null` would cause an error. It is optional, but not nullable, from the OAS perspective. How this shows up in the generated client depends on the usage of `/GenerateNullableReferenceTypes` and `/GenerateOptionalParameters`.

2024-02-23 16:43 UTC, bkoelman commented
Tests are needed to cover:
- Sending without ID
- Sending with ID

for the three modes `Forbidden`, `Allowed` and `Required`.

The easiest setup would be to have three resource types with different `[Resource(ClientIdGeneration = ...)]` for the three modes.

2024-02-23 16:49 UTC, verdie-g commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = game.StringId!, // FIXME: StringId is null, how to generate an id?
Actually I reused my use-case from https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/1299, i.e. creating a user for a given steam id.

2024-02-23 16:51 UTC, verdie-g commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = null!, // FIXME: incorrect nullability here
Is the difference that it's allowed to omit the property but not setting it explicit to null?

2024-02-23 20:04 UTC, verdie-g commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = game.StringId!, // FIXME: StringId is null, how to generate an id?
But let's use a Guid to ease the test.

2024-02-23 20:52 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = null!, // FIXME: incorrect nullability here
Yes

2024-02-23 21:36 UTC, verdie-g commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +}
I can't write a `Pass_forbidden_id` because the id property is generated.

2024-02-24 02:24 UTC, bkoelman requested changes
See comments.

2024-02-24 02:24 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +namespace OpenApiEndToEndTests.ClientGeneratedId;
The topic is `ClientIdGenerationModes`, so the namespace/directory should reflect that. Test class, fakers, DbContext, etc. should be named accordingly.

2024-02-24 02:24 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +    public async Task Omit_required_id()
Test names should be proper English sentences that state something functional. See the existing tests outside OpenAPI for examples. This could be: Cannot_create_resource_without_ID_when_required.

2024-02-24 02:24 UTC, bkoelman commented on test/OpenApiTests/ClientGeneratedId/Group.cs
> +public sealed class Group : Identifiable<Guid>
PlayerGroup? or Team with Members?

2024-02-24 02:24 UTC, bkoelman commented on test/OpenApiTests/ClientGeneratedId/Player.cs
> +    public List<Game> Games { get; set; } = [];
What's this, purchased games, recently played games, ...?

2024-02-24 02:24 UTC, bkoelman commented on test/OpenApiTests/ClientGeneratedId/Player.cs
> +    public string Name { get; set; } = null!;
Perhaps NickName, to avoid having a Name property everywhere?

2024-02-24 02:24 UTC, bkoelman commented on test/OpenApiTests/ClientGeneratedId/Player.cs
> +    public List<Group> Groups { get; set; } = [];
If these are the groups this player is a member of, then the relationship name should reflect that. But I'm just guessing what "groups" is supposed to mean.

2024-02-24 02:24 UTC, bkoelman commented on test/OpenApiTests/ClientGeneratedId/Game.cs
> +    public string Name { get; set; } = null!;
Title?

2024-02-24 02:24 UTC, bkoelman commented on test/OpenApiTests/ClientGeneratedId/Game.cs
> +    public decimal Price { get; set; }
PurchasePrice, MonthlyCost, ...?

2024-02-24 02:24 UTC, bkoelman commented on test/OpenApiTests/ClientGeneratedId/ClientGeneratedIdFakers.cs
> +        .RuleFor(player => player.Price, faker => decimal.Parse(faker.Commerce.Price())));
these are not players

2024-02-24 02:24 UTC, bkoelman commented on test/OpenApiTests/ClientGeneratedId/ClientGeneratedIdTests.cs
> +        document.Should().ContainPath("components.schemas.groupDataInPostRequest").With(resourceDataInPostRequestElement =>
`resourceDataInPostRequestElement` is quite long, I think `dataElement` would be sufficiently clear.

2024-02-26 02:58 UTC, bkoelman requested changes
See comments.

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiTests/ClientIdGenerationModes/Player.cs
> +    public List<PlayerGroup> GroupMemberships { get; set; } = [];
Or just MemberOf?

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiTests/ClientIdGenerationModes/PlayerGroup.cs
> +public sealed class PlayerGroup : Identifiable<Guid>
Probably more realistic to make this `Identifiable<long>`, as setting the ID is forbidden.

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiTests/ClientIdGenerationModes/ClientGeneratedIdFakers.cs
> +using Bogus;
Please rename files to match their containing type. There's a refactoring for that at the project/solution level.

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiTests/ClientIdGenerationModes/ClientGeneratedIdFakers.cs
> +        .RuleFor(game => game.PurchasePrice, faker => decimal.Parse(faker.Commerce.Price())));
Use `faker.Finance.Amount()`, and set a reasonable range.

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientIdGenerationModes/PostTests.cs
> +    public async Task Cannot_create_resource_without_ID_when_mode_is_required()
This is an integration test (as opposed to a unit test), so it should be functional instead of describing implementation details. The use case is that a user is trying to create a resource without specifying an ID, while the system requires an ID to be provided. That there's an internal "mode" is irrelevant to the user. If we rename that, the scenario does not change.

Therefore I suggested: Cannot_create_resource_without_ID_when_required.
Perhaps better: Cannot_create_resource_without_ID_when_supplying_ID_is_required.

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientIdGenerationModes/PostTests.cs
> +public sealed class PostTests : IClassFixture<IntegrationTestContext<OpenApiStartup<ClientIdGenerationModesDbContext>, ClientIdGenerationModesDbContext>>
ClientIdGenerationModesTests

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientIdGenerationModes/PostTests.cs
> +        doc.Should().BeNull();
We generally don't assert that something doesn't throw, because anything could throw at any time, which would make the test fail already.

We normally assert on the response (status code and body, and occasionally on headers if relevant) and what's changed in the database. So this should assert on the returned document (don't abbreviate), and verify the database was updated (see `CreateResourceWithClientGeneratedIdTests` for examples).

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiTests/ClientIdGenerationModes/ClientGeneratedIdTests.cs
> +    public async Task Post_data_should_have_required_id()
Suggestion: Schema_property_for_ID_is_required_in_post_request (based on names used in `NullabilityTests`)

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiTests/ClientIdGenerationModes/ClientGeneratedIdTests.cs
> +    public async Task Post_data_should_have_non_required_id()
Suggestion: Schema_property_for_ID_is_optional_in_post_request

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiTests/ClientIdGenerationModes/ClientGeneratedIdTests.cs
> +    public async Task Post_data_should_not_have_id()
Suggestion: Schema_property_for_ID_is_omitted_in_post_request

2024-02-26 02:58 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientIdGenerationModes/swagger.g.json
> +{
This file can be shortened a lot by adding:
```
GenerateControllerEndpoints = JsonApiEndpoints.Post
```
to the `[Resource]` attribute on models. I don't expect we'll ever need to assert on other endpoints here.

2024-02-26 07:50 UTC, maurei commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = null!, // FIXME: passing "" here works fine 🤔
Read into it a little bit. It sounds familiar for sure, but it doesn't _really_ ring a concrete bell at this moment... 🤷

2024-02-26 21:28 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientGeneratedId/PostTests.cs
> +                Id = null!, // FIXME: passing "" here works fine 🤔
Closing, tracked at https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/1485.

2024-02-26 21:48 UTC, bkoelman requested changes
Few minor comments.

2024-02-26 21:48 UTC, bkoelman commented on test/OpenApiEndToEndTests/ClientIdGenerationModes/ClientIdGenerationModesTests.cs
> +        doc?.Data.Id.Should().NotBeNullOrEmpty();
This assertion is conditional, ie when null is returned, nothing is asserted on.
Instead, first assert the response isn't null using `.ShouldNotBeNull()`. This extension method is a workaround for https://github.com/fluentassertions/fluentassertions/issues/1115.

2024-02-26 23:52 UTC, bkoelman approved these changes
LGTM

If you don't mind, I'd like to merge Kiota support first, so Kiota tests can be added to this PR before merging it.

2024-03-10 09:50 UTC, merged

2024-03-10 17:05 UTC, verdie-g commented
Thanks! I couldn't find the time to do the Kiota part.