openapi: support validation attributes
json-api-dotnet/JsonApiDotNetCore pull request #1477
Opened 2024-02-24 01:07 UTC by verdie-g

Closes #1055

#### QUALITY CHECKLIST
- [ ] Changes implemented in code
- [ ] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [ ] Adapted tests
- [ ] Documentation updated

2024-02-24 01:20 UTC, verdie-g commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +                // TODO: no length constraint?
It seems like the library used to generate the OpenAPI document doesn't support `Length` and `Base64String` which were both introduced in .NET 8.

2024-02-24 01:21 UTC, verdie-g commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +            // TODO: TimeSpan format is an akward object with all the TimeSpan public properties.
What is the user expected to do with user to avoid the default TimeSpan JSON serialization?

2024-02-24 01:21 UTC, verdie-g commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +    public async Task String(string modelName)
Any opinion on the test names?

2024-02-24 01:24 UTC, verdie-g commented
@bkoelman could you give a first review on just that?

2024-02-26 22:23 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +                // TODO: no length constraint?
Swashbuckle's type mappings are defined [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs#L189-L215). ModelState attributes are mapped [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/OpenApiSchemaExtensions.cs#L91-L108).

I suppose we could fill the gap ourselves, as Swashbuckle isn't maintained anymore. Or just postpone adding support for the .NET 8 annotations. Either way, `[StringLength(10)]` can still be used on both frameworks.

It all depends on what .NET 8 adds and how useful that is, how much effort it takes to implement, and how messy the codebase becomes when doing so.

We _could_ adapt the write logic to emit a swagger.g.json per target framework (not saying we _should_, but something to consider).

2024-02-26 22:25 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +                // TODO: no length constraint?
It's also unclear at this point if our OpenAPI support is going to support .NET 6, which EOLs in less than a year.

2024-02-26 22:26 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +            // TODO: TimeSpan format is an akward object with all the TimeSpan public properties.
I'm not sure I understand, can you clarify?

2024-02-26 22:30 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +    public async Task String(string modelName)
How about this?

Phone_annotation_on_resource_property_produces_expected_schema
EmailAddress_annotation_on_resource_property_produces_expected_schema
RegularExpression_annotation_on_resource_property_produces_expected_schema
StringLength_annotation_on_resource_property_produces_expected_schema
etc...

2024-02-26 23:35 UTC, verdie-g commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +            // TODO: TimeSpan format is an akward object with all the TimeSpan public properties.
The default TimeSpan serialization is
```json
"timeSpan": {
        "type": "object",
        "properties": {
          "ticks": {
            "type": "integer",
            "format": "int64"
          },
          "days": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "hours": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "milliseconds": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "microseconds": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
...
```
So I was just wondering, should I validate that the type is a reference to this object?

It's so sad that there is no good standard to represent a duration as a string (except the horrible `P3Y6M4DT12H30M5S` in ISO 8601).

2024-02-26 23:46 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +            // TODO: TimeSpan format is an akward object with all the TimeSpan public properties.
Can you google a bit? You're surely not the first person wondering about this.

2024-02-27 05:39 UTC, verdie-g commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +            // TODO: TimeSpan format is an akward object with all the TimeSpan public properties.
Yeah it's a known issue. I was just wondering if you had a preference about it.

A custom converter can be used to do a TimeSpan.ToString() or TimeSpan.TotalMilliseconds.

2024-03-11 02:37 UTC, bkoelman commented
@verdie-g Do you still intend to complete this?

2024-04-11 17:55 UTC, verdie-g commented
I pushed some old changes that were still on my machine in case someone wants to continue the PR.

2024-05-27 21:29 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +                    // TODO: ValidatedDateAt = new DateTimeOffset(fingerprint.ValidatedDateAt!.Value.ToDateTime(new TimeOnly()).ToUniversalTime()),
If uncommented, fails with
```
 "JsonApiDotNetCore.Repositories.DataStoreUpdateException: Failed to persist changes in the underlying data store.",
          " ---> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.",
          " ---> System.ArgumentException: Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array, range, or multirange. (Parameter 'value')",
          "   at PgConverterResolution? Npgsql.Internal.Converters.DateTimeConverterResolver<T>.Get(DateTime value, PgTypeId? expectedPgTypeId, bool validateOnly)",
          "   at DateTimeConverterResolver<DateTime> Npgsql.Internal.Converters.DateTimeConverterResolver.CreateResolver(PgSerializerOptions options, PgTypeId timestampTz, PgTypeId timestamp, bool dateTimeInfinityConversions)+(DateTimeConverterResolver<DateTime> resolver, DateTime value, PgTypeId? expectedPgTypeId) => { }",
          "   at PgConverterResolution? Npgsql.Internal.Converters.DateTimeConverterResolver<T>.Get(T value, PgTypeId? expectedPgTypeId)",
          "   at PgConverterResolution? Npgsql.Internal.PgConverterResolver<T>.GetAsObjectInternal(PgTypeInfo typeInfo, object value, PgTypeId? expectedPgTypeId)",
          "   at PgConverterResolution? Npgsql.Internal.PgResolverTypeInfo.GetResolutionAsObject(object value, PgTypeId? expectedPgTypeId)",
          "   at PgConverterResolution Npgsql.Internal.PgTypeInfo.GetObjectResolution(object value)",
          "   at PgConverterResolution Npgsql.NpgsqlParameter.ResolveConverter(PgTypeInfo typeInfo)",
          "   at void Npgsql.NpgsqlParameter.ResolveTypeInfo(PgSerializerOptions options)",
          "   at void Npgsql.NpgsqlParameterCollection.ProcessParameters(PgSerializerOptions options, bool validateValues, CommandType commandType)",
          "   at async ValueTask<NpgsqlDataReader> Npgsql.NpgsqlCommand.ExecuteReader(bool async, CommandBehavior behavior, CancellationToken cancellationToken) x 2",
          "   at async Task<DbDataReader> Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)",
          "   at async Task<RelationalDataReader> Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) x 2",
          "   at async Task Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)",
          "   --- End of inner exception stack trace ---",
          "   at async Task Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)",
          "   at async Task<int> Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable<ModificationCommandBatch> commandBatches, IRelationalConnection connection, CancellationToken cancellationToken) x 3",
          "   at async Task<int> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList<IUpdateEntry> entriesToSave, CancellationToken cancellationToken) x 2",
          "   at async Task<TResult> Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync<TState, TResult>(TState state, Func<DbContext, TState, CancellationToken, Task<TResult>> operation, Func<DbContext, TState, CancellationToken, Task<ExecutionResult<TResult>>> verifySucceeded, CancellationToken cancellationToken)",
          "   at async Task<int> Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken) x 2",
          "   at async Task JsonApiDotNetCore.Repositories.EntityFrameworkCoreRepository<TResource, TId>.SaveChangesAsync(CancellationToken cancellationToken) in JsonApiDotNetCore/src/JsonApiDotNetCore/Repositories/EntityFrameworkCoreRepository.cs:line 651",
          "   --- End of inner exception stack trace ---",
          "   at async Task JsonApiDotNetCore.Repositories.EntityFrameworkCoreRepository<TResource, TId>.SaveChangesAsync(CancellationToken cancellationToken) in JsonApiDotNetCore/src/JsonApiDotNetCore/Repositories/EntityFrameworkCoreRepository.cs:line 657",
          "   at async Task JsonApiDotNetCore.Repositories.EntityFrameworkCoreRepository<TResource, TId>.CreateAsync(TResource resourceFromRequest, TResource resourceForDatabase, CancellationToken cancellationToken) in JsonApiDotNetCore/src/JsonApiDotNetCore/Repositories/EntityFrameworkCoreRepository.cs:line 232",
          "   at void CallSite.Target(Closure, CallSite, object)",
          "   at void System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1<T0>(CallSite site, T0 arg0)",
          "   at async Task JsonApiDotNetCore.Repositories.ResourceRepositoryAccessor.CreateAsync<TResource>(TResource resourceFromRequest, TResource resourceForDatabase, CancellationToken cancellationToken)",
          "   at async Task<TResource> JsonApiDotNetCore.Services.JsonApiResourceService<TResource, TId>.CreateAsync(TResource resource, CancellationToken cancellationToken) in JsonApiDotNetCore/src/JsonApiDotNetCore/Services/JsonApiResourceService.cs:line 217",
          "   at async Task<TResource> JsonApiDotNetCore.Services.JsonApiResourceService<TResource, TId>.CreateAsync(TResource resource, CancellationToken cancellationToken) in JsonApiDotNetCore/src/JsonApiDotNetCore/Services/JsonApiResourceService.cs:line 223",
          "   at async Task<IActionResult> JsonApiDotNetCore.Controllers.BaseJsonApiController<TResource, TId>.PostAsync(TResource resource, CancellationToken cancellationToken) in JsonApiDotNetCore/src/JsonApiDotNetCore/Controllers/BaseJsonApiController.cs:line 207",
          "   at async Task<IActionResult> JsonApiDotNetCore.Controllers.JsonApiController<TResource, TId>.PostAsync(TResource resource, CancellationToken cancellationToken) in JsonApiDotNetCore/src/JsonApiDotNetCore/Controllers/JsonApiController.cs:line 78",
          "   at async ValueTask<IActionResult> Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)",
          "   at async Task Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()+Logged(?)",
          "   at async Task Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()+Awaited(?)",
          "   at void Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)",
          "   at Task Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)",
          "   at Task Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()",
          "   at async Task Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextExceptionFilterAsync()+Awaited(?)"
```

It sounds to me that JADNC pass the DateOnly as a DateTime to Npgsql?

2024-05-27 21:31 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +    public async Task Invalid_datetime_should_return_an_error()
Date, DateTime, and Uri tests all fail because the generated code disallows me to pass an invalid value. Should I bypass the generated client and craft a request using the HttpClient?

2024-05-27 22:01 UTC, verdie-g commented
Hi @bkoelman, I'll try finishing that PR. Could you have a pass on its current state, I'll add tests for Kiota once the one for NSwag start looking okay. Also, is there anything worth adding to the doc regarding this change?

2024-05-28 07:11 UTC, bkoelman commented
> Hi @bkoelman, I'll try finishing that PR. Could you have a pass on its current state, I'll add tests for Kiota once the one for NSwag start looking okay. Also, is there anything worth adding to the doc regarding this change?

Cool! Sure, I'll take a look. I don't expect the docs need to be updated, unless there are pitfalls users should know about. For kiota, it's worth removing the `--log-level Error` switch temporarily to see what comes up. However, kiota is pretty rigid and inflexible, so don't worry too much about its quirks.

2024-05-28 07:17 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +                    // TODO: ValidatedDateAt = new DateTimeOffset(fingerprint.ValidatedDateAt!.Value.ToDateTime(new TimeOnly()).ToUniversalTime()),
Fakers generally contain `.ToUniversalTime()`, so PostgreSQL won't block non-UTC values. Though it's odd you're getting this error on a `DateOnly`. You can check the generated SQL by running a server-side test in debug mode, which writes to the Output window. Perhaps this is a bug in the PostgreSQL EF Core provider?

2024-05-28 07:20 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +    public async Task Invalid_datetime_should_return_an_error()
Then it's not an OpenAPI test anymore. If it can't be tested through OpenAPI, just leave them out.

2024-05-28 07:53 UTC, bkoelman reviewed
I've added some comments on things that jumped out to me. Before focussing on kiota, we should get the proposed scope table in better shape.

2024-05-28 07:53 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/OpenApiNSwagEndToEndTests.csproj
> +      <Options>/ClientClassAccessModifier:internal /GenerateExceptionClasses:false /AdditionalNamespaceUsages:JsonApiDotNetCore.OpenApi.Client.NSwag /GenerateNullableReferenceTypes:true</Options>
#1470 was fixed, so `/GenerateOptionalParameters:true` should work properly now.

2024-05-28 07:53 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +public sealed class ModelValidationTests : IClassFixture<IntegrationTestContext<OpenApiStartup<ModelValidationDbContext>, ModelValidationDbContext>>
Meanwhile, `XUnitLogHttpMessageHandler` was added to all other tests, which writes the JSON request/response to the xUnit test output window. Please adapt accordingly, I've found it quite helpful in debugging.

2024-05-28 07:53 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +    public async Task Omitting_a_required_attribute_should_return_an_error()
We've generally used statement form in test names, ie:
- Cannot_omit_required_attribute (note this applies to POST only, so it would be better to include that in the name: Cannot_create_resource_with_omitted_required_property)
- Cannot_exceed_length_constraint
- Cannot_violate_regular_expression_constraint
- Cannot_use_invalid_email
- Cannot_use_TimeSpan_outside_of_valid_range
- ...
- Can_create_resource_with_valid_properties

2024-05-28 07:53 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/Fingerprint.cs
> +public sealed class Fingerprint : Identifiable<Guid>
Perhaps the name `SocialMediaAccount` is more appropriate?

2024-05-28 07:53 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/Fingerprint.cs
> +    public TimeOnly? ValidatedTimeAt { get; set; }
`ValidatedAtDate` / `ValidatedAtTime` sounds more like proper English.

2024-05-28 07:53 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +namespace OpenApiNSwagEndToEndTests.ModelValidation;
Please rename to ModelStateValidation, to match with existing non-OpenAPI tests.

2024-05-28 07:53 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +    }
Nullability and requiredness are extensively covered by the tests in `ResourceFieldValidation`, so I think they can be left out here. But one case to include here is using `[Required(AllowEmptyStrings = false)]`.

2024-05-28 07:53 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +            userNameEl.Should().HaveProperty("nullable", true);
I wouldn't expect nullability to be of concern in these tests. Am I missing something?

2024-05-28 20:39 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +    public async Task Invalid_datetime_should_return_an_error()
Make sense

2024-05-28 20:42 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +                    // TODO: ValidatedDateAt = new DateTimeOffset(fingerprint.ValidatedDateAt!.Value.ToDateTime(new TimeOnly()).ToUniversalTime()),
That's cool
```
Failed executing DbCommand (34ms) [Parameters=[@p0='43debb5f-abe4-4e44-bad5-b852124e8dd4', @p1='95' (Nullable = true), @p2='https://loremflickr.com/320/240?lock=1798481699', @p3='6759-7554-5043-3270', @p4='Kellie15@gmail.com', @p5='Kellie', @p6='Wilderman' (Nullable = false), @p7='02:00:00' (Nullable = true) (DbType = Object), @p8='(546) 274-9304 x65491', @p9='https://loremflickr.com/320/240?lock=475250130', @p10='ogxiroilgkft', @p11='2019-12-30T20:45:27.0196183-05:00' (Nullable = true) (DbType = DateTime), @p12='12/31/2019' (Nullable = true) (DbType = Date), @p13='19:31' (Nullable = true) (DbType = Time)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Fingerprints" ("Id", "Age", "BackgroundPicture", "CreditCard", "Email", "FirstName", "LastName", "NextRevalidation", "Phone", "ProfilePicture", "UserName", "ValidatedAt", "ValidatedDateAt", "ValidatedTimeAt")
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13);
```
Looks fine
```
@p12='12/31/2019' (Nullable = true) (DbType = Date)
```
I'll dig more

2024-05-28 20:47 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/OpenApiNSwagEndToEndTests.csproj
> +      <Options>/ClientClassAccessModifier:internal /GenerateExceptionClasses:false /AdditionalNamespaceUsages:JsonApiDotNetCore.OpenApi.Client.NSwag /GenerateNullableReferenceTypes:true</Options>
I don't remember exactly what this is about but I understand you would want me to add it to this client

2024-05-28 20:49 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/OpenApiNSwagEndToEndTests.csproj
> +      <Options>/ClientClassAccessModifier:internal /GenerateExceptionClasses:false /AdditionalNamespaceUsages:JsonApiDotNetCore.OpenApi.Client.NSwag /GenerateNullableReferenceTypes:true</Options>
Oh I understand now, it allows me to write
```
apiClient.PostFingerprintAsync(new FingerprintPostRequestDocument
```
instead of
```
apiClient.PostFingerprintAsync(null, new FingerprintPostRequestDocument
```

2024-05-28 20:51 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +public sealed class ModelValidationTests : IClassFixture<IntegrationTestContext<OpenApiStartup<ModelValidationDbContext>, ModelValidationDbContext>>
That's indeed pretty neat

2024-05-28 21:02 UTC, verdie-g commented on test/OpenApiTests/ModelValidation/Fingerprint.cs
> +public sealed class Fingerprint : Identifiable<Guid>
Agreed

2024-05-29 01:04 UTC, verdie-g commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +                // TODO: no length constraint?
I've added the table to the PR description and will complete it later.

2024-05-29 01:06 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Length(0, 10)]
Even if Length is `0, 10`, a POST with `Tags = null` will fail with `The Tags field does not equal any of the values specified in AllowedValuesAttribute.` :(

2024-05-29 01:16 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Length(0, 10)]
Oh AllowedValues probably doesn't work on collections

2024-05-29 04:28 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/OpenApiNSwagEndToEndTests.csproj
> +      <Options>/ClientClassAccessModifier:internal /GenerateExceptionClasses:false /AdditionalNamespaceUsages:JsonApiDotNetCore.OpenApi.Client.NSwag /GenerateNullableReferenceTypes:true</Options>
I'm fine either way. I just mentioned it because you added it initially and it didn't work properly.

2024-05-29 04:34 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +    }
My mistake: `AllowEmptyStrings` is already false by default. We should test the case with `true`.

2024-05-29 04:48 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +                // TODO: no length constraint?
I've re-pasted the table in the PR description from the above comment's source to preserve formatting. I noticed the `DataType` entries were removed, was that intentional? They _do_ affect the `openapi.json` output when used.

2024-05-30 02:05 UTC, verdie-g commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +                // TODO: no length constraint?
>  I noticed the DataType entries were removed, was that intentional?

I did remove them because of your comment

> so perhaps the [DataType] entries are better left out of scope


I'm not sure how to fill that table. What does "yes" means for NSwag, MVC, and EF Core?

2024-05-30 04:33 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +                // TODO: no length constraint?
> > I noticed the DataType entries were removed, was that intentional?
> 
> I did remove them because of your comment

The point of the table is to document the outcome of experiments and decisions. For example, if we decide that `[DataType(DataType.Html)]` is out of scope because it doesn't affect validation, the notes column should indicate so. This makes it possible to distinguish between "there's intentionally no test coverage" vs "we simply forgot it".

> > so perhaps the [DataType] entries are better left out of scope
> 
> I'm not sure how to fill that table. What does "yes" means for NSwag, MVC, and EF Core?

That it behaves the way JADNC users would expect, without oddities/workarounds. It indicates if we need to warn users in the docs, log warnings, etc.
- NSwag/Kiota means a working C# client is generated (with test coverage for valid/invalid input, part of this PR).
- MVC means the expected server-side validation error is produced. Sometimes NSwag already catches bad input, so it never hits the server. We don't need to add tests for that in this PR, but it should be tried out. For example, if adding `[StringLength]` does NOT validate server-side, but only NSwag catches it, we should document that. Because only client-side validation is insecure.
- EF Core means checking what SQL data type and SQL constraints are being generated, and whether they make sense. For example, does `[Required(AllowEmptyStrings = false)]` generate just a non-nullable column, or does it also add the minimum length constraint? If not, should it do so, if possible at all? Google for it, are there open issues, StackOverflow questions, etc? We need to understand how it works and is supposed to be used, and reason about the feature from an API developer perspective. Is there anything to watch out for? Similar to the previous bullet, this is exploration.

2024-05-30 04:35 UTC, bkoelman commented on test/OpenApiTests/ModelValidation/ModelValidationTests.cs
> +                // TODO: no length constraint?
According to https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validationattribute?view=net-8.0, there's also `[MinLength]` and `[MaxLength]`. They should be included in the table.

2024-05-30 05:29 UTC, bkoelman reviewed
See comments. The test coverage needs adjustment, based on the table (that isn't finished yet). I would expect to see some net80-only tests too.

2024-05-30 05:29 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationTests.cs
> +        document.Should().ContainPath($"components.schemas.{modelName}.properties.tags").With(tagsEl =>
Please rename `tagsEl` to `tagsElement`, as well as similar variables in this file.

2024-05-30 05:29 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationTests.cs
> +        // ReSharper disable once UseCollectionExpression
This looks like a Resharper bug. Is there an open issue at https://youtrack.jetbrains.com/issues/RSRP we can link to? If not, can you create one and link to it from here?

2024-05-30 05:29 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(typeof(TimeSpan), "01:00", "05:00")]
Can you check if `TimeSpan` is culture-sensitive? If so, should add `ConvertValueInInvariantCulture = true, ParseLimitsInInvariantCulture = true`.

2024-05-30 05:29 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationTests.cs
> +    public static TheoryData<string> ModelNames =>
```suggestion
    public static readonly TheoryData<string> ModelNames =
```

2024-06-07 19:16 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/GeneratedSwagger/net6.0/swagger.g.json
I think the .NET 8 attributes are currently not supported by OpenAPI.

2024-06-07 19:17 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationFakers.cs
> +        .RuleFor(socialMediaAccount => socialMediaAccount.UserName, faker => faker.Random.String2(3, 18))
I missed the `Random.UserName`

2024-06-07 20:51 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(typeof(TimeSpan), "01:00", "05:00")]
It seems like it only accepts invariant culture. I added a test to check that a comma is not allowed.

2024-06-07 20:56 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationFakers.cs
> +        .RuleFor(socialMediaAccount => socialMediaAccount.UserName, faker => faker.Random.String2(3, 18))
Ah never mind. I used `String2` because I added a only-letters constraint on UserName.

2024-06-08 11:52 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +        SocialMediaAccountPostRequestDocument requestBody = new()
This doesn't look right. Building the request body is not part of the act phase.

2024-06-08 11:57 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(typeof(TimeSpan), "01:00", "05:00")]
I believe it is culture sensitive. According to https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-timespan-format-strings, the decimal separator is used for milliseconds.

2024-06-08 12:19 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationTests.cs
> +        });
```suggestion
        document.Should().ContainPath($"components.schemas.{modelName}.properties.givenName").With(givenNameElement =>
        {
            givenNameElement.Should().HaveProperty("type", "string");
        });
```

2024-06-08 12:22 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationTests.cs
> +#endif
This was updated in this file, but it occurs in multiple places. Please adapt accordingly.

2024-06-08 12:31 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationFakers.cs
> +        .RuleFor(socialMediaAccount => socialMediaAccount.UserName, faker => faker.Random.String2(3, 18))
Ok, that makes sense. But it doesn't apply to the other places where `String2` is used, right?

2024-06-08 12:32 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/GeneratedSwagger/net6.0/swagger.g.json
At least `Length` _is_ supported, see https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2882. I haven't checked the other ones.

2024-06-08 12:37 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(typeof(TimeSpan), "01:00", "05:00")]
Ah maybe my computer is using US culture. I'll try setting the culture explicitly in the program.

2024-06-08 12:42 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +        SocialMediaAccount socialMediaAccount = _fakers.SocialMediaAccount.Generate();
The tests in the codebase use the convention to prefix variables that represent unstored data with `new`, and existing data (at the time of _act_) with `existing`. For example, see https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/test/JsonApiDotNetCoreTests/IntegrationTests/ReadWrite/Updating/Resources/UpdateResourceTests.cs#L86-L110. I'd prefer to apply the same convention here for consistency.

Please rename to `newAccount` here, and use `newLastName` in the other tests.

2024-06-08 14:21 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationFakers.cs
> +        .RuleFor(socialMediaAccount => socialMediaAccount.UserName, faker => faker.Random.String2(3, 18))
For `Planet` and `Tags` I could not find a better alternative

2024-06-08 14:33 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +        SocialMediaAccount socialMediaAccount = _fakers.SocialMediaAccount.Generate();
> and use newLastName in the other tests.

I assume something like this `string newLastName = _fakers.SocialMediaAccount.Generate().LastName;`

I think I would prefer keeping `SocialMediaAccount newAccount = _fakers.SocialMediaAccount.Generate();` in case another property from `newAccount` is needed later.

2024-06-08 14:50 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/GeneratedSwagger/net6.0/swagger.g.json
Even after setting `SwashbuckleVersion` to 6.6.2, no special fields seem to be set on `firstName`

2024-06-10 00:38 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/GeneratedSwagger/net6.0/swagger.g.json
Oh nvm I missed the `SwashbuckleFrozenVersion` that was set to 6.6.1

2024-06-10 01:58 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +                    // TODO: ValidatedDateAt = new DateTimeOffset(fingerprint.ValidatedDateAt!.Value.ToDateTime(new TimeOnly()).ToUniversalTime()),
My bad, it's `ValidatedAt` that causes some issues. I was able to reproduce the issue
```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContext<AppDbContext>(options => options.UseNpgsql("Host=localhost:5432;Database=test;Username=postgres;Password=root"));
builder.Services.AddJsonApi<AppDbContext>();
var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    db.Database.EnsureCreated();
}

app.UseRouting();
app.UseJsonApi();
app.MapControllers();

app.Run();

[Resource]
public class Author : Identifiable<Guid>
{
    [Attr]
    public DateTime Date { get; set; }
}

public class AppDbContext : DbContext
{
    public DbSet<Author> Authors => Set<Author>();

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }
}
```

```
curl -X POST http://localhost:18574/authors -H "Content-Type: application/vnd.api+json" --data '{"data":{"type":"authors","attributes":{"date": "2019-12-31T01:23:25.2607037+00:00"}}}'
```

After some debugging I found out that a date like `2019-12-31T01:23:25.2607037+00:00` will be converted by ASP.NET to `30-Dec-19 20:23:25 (Kind=Local)`. However, `2019-12-31T01:23:25.2607037Z` is converted to `31-Dec-19 01:23:25 (Kind=Utc)`.

The reason why a timezone offset is used in the test is that NSwag generates a `DateTimeOffset` for `DateTime` attributes.

So this doesn't seem to bug. It's super awkward for the user to get a 500 for that though. Also, I'm not sure how to fix the test. One work-around is to replace the `DateTime` with `DateTimeOffset` in the resource definition.

2024-06-10 02:17 UTC, verdie-g commented
I've completed the table except the EF Core column which I think is out-of-scope for this PR.

2024-06-10 23:50 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(typeof(TimeSpan), "01:00", "05:00")]
I was a bit confused about what these properties do so I copied the `RangeAttribute` code to play with it
```csharp
CultureInfo.CurrentCulture = new CultureInfo("fr-FR");
RangeAttribute2 a1 = new(typeof(TimeSpan), "01:00", "05:00");
RangeAttribute2 a2 = new(typeof(TimeSpan), "01:00", "05:00")
{
    ConvertValueInInvariantCulture = true,
    ParseLimitsInInvariantCulture = true,
};
foreach (string s in new[] { "02:00:00", "02:00:00.123", "02:00:00,123" })
{
    Console.WriteLine($"{s} -> {a1.IsValid(s)}");
    Console.WriteLine($"{s} -> {a2.IsValid(s)}");
}
```
this prints
```
02:00:00 -> True
02:00:00 -> True
02:00:00.123 -> True
02:00:00.123 -> True
02:00:00,123 -> True
02:00:00,123 -> False
```

`ParseLimitsInInvariantCulture` is to parse `01:00` and `05:00` as invariant. In our case since they are constants, it's not super useful. Though, `ConvertValueInInvariantCulture` means that the input will be parsed using InvariantCulture. This one is important. My computer uses US culture so I could not see the difference.

2024-06-11 02:41 UTC, verdie-g commented
> For kiota, it's worth removing the --log-level Error switch temporarily to see what comes up.
```
#/paths/~1socialMediaAccounts/post/responses/201/headers/Location/schema - The format uri is not supported by Kiota and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPatchRequest/properties/creditCard - The format credit-card is not supported by Kiota for the type string and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPatchRequest/properties/email - The format email is not supported by Kiota and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPatchRequest/properties/phone - The format tel is not supported by Kiota for the type string and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPatchRequest/properties/profilePicture - The format uri is not supported by Kiota and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPatchRequest/properties/backgroundPicture - The format uri is not supported by Kiota and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPatchRequest/properties/nextRevalidation - The format date-span is not supported by Kiota for the type string and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPostRequest/properties/creditCard - The format credit-card is not supported by Kiota for the type string and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPostRequest/properties/email - The format email is not supported by Kiota and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPostRequest/properties/phone - The format tel is not supported by Kiota for the type string and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPostRequest/properties/profilePicture - The format uri is not supported by Kiota and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPostRequest/properties/backgroundPicture - The format uri is not supported by Kiota and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInPostRequest/properties/nextRevalidation - The format date-span is not supported by Kiota for the type string and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInResponse/properties/creditCard - The format credit-card is not supported by Kiota for the type string and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInResponse/properties/email - The format email is not supported by Kiota and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInResponse/properties/phone - The format tel is not supported by Kiota for the type string and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInResponse/properties/profilePicture - The format uri is not supported by Kiota and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInResponse/properties/backgroundPicture - The format uri is not supported by Kiota and the string type will be used.
#/components/schemas/socialMediaAccountAttributesInResponse/properties/nextRevalidation - The format date-span is not supported by Kiota for the type string and the string type will be used.
```

Kiota doesn't support the formats `uri` and `date-span` :/

2024-06-12 04:39 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationFakers.cs
> +        .RuleFor(socialMediaAccount => socialMediaAccount.UserName, faker => faker.Random.String2(3, 18))
Oh, I see now. It's because a string of a certain length is needed. And .`String()` potentially generates malformed UTF-16.

2024-06-12 04:49 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(typeof(TimeSpan), "01:00", "05:00")]
Yes, that's how it works. Thanks for looking into it.

The `ConvertValueInInvariantCulture = true` on `Age` should be removed, because it's meaningless. See the documentation at https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.rangeattribute.convertvalueininvariantculture?view=net-8.0:

> Gets or sets a value that determines whether any conversions of the value being validated to [OperandType](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.rangeattribute.operandtype?view=net-8.0#system-componentmodel-dataannotations-rangeattribute-operandtype) as set by the type parameter of the [RangeAttribute(Type, String, String)](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.rangeattribute.-ctor?view=net-8.0#system-componentmodel-dataannotations-rangeattribute-ctor(system-type-system-string-system-string)) constructor use the invariant culture or the current culture.
> 
> This property has no effect on the constructors with [Int32](https://learn.microsoft.com/en-us/dotnet/api/system.int32?view=net-8.0) or [Double](https://learn.microsoft.com/en-us/dotnet/api/system.double?view=net-8.0) parameters, which always use the invariant culture for any conversions of the validated value.

2024-06-12 04:56 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +        Func<Task<SocialMediaAccountPrimaryResponseDocument>> action = () => apiClient.PostSocialMediaAccountAsync(requestBody);
This can be shortened to:
```c#
Func<Task> action = async() => await apiClient.PostSocialMediaAccountAsync(requestBody);
```

2024-06-12 04:56 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +        SocialMediaAccount socialMediaAccount = _fakers.SocialMediaAccount.Generate();
Sounds good. I'm seeing failed tests because `Age` is not in a valid range.

2024-06-12 06:15 UTC, bkoelman reviewed
I'm not seeing any end-to-end tests for the .NET 8 attributes.

Oh well, I expected to find `#if` lines, but end-to-end tests can't multi-target so it's .NET 8 only.

2024-06-12 06:15 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +                    ValidatedAtDate = new DateTimeOffset(newAccount.ValidatedAtDate!.Value.ToDateTime(new TimeOnly()).ToUniversalTime()),
This looks ugly. Can it be addressed more elegantly? See tips at https://github.com/RicoSuter/NSwag/issues/4062. A similar approach possibly also solves the `ValidatedAt` UTC issue.

This is why we write tests: to see if/how we can provide a smooth experience to our users, instead of just hacking around the quirks we encounter.

2024-06-12 06:23 UTC, bkoelman commented
> I've completed the table except the EF Core column which I think is out-of-scope for this PR.

I've mentioned earlier that the goal of writing end-to-end tests is to assess the overall experience our users will face. This doesn't mean we need to write tests for EF Core features in this PR, but we do need to check for oddities and possibly create separate issues to address them, or document things to watch out for. So I disagree that it's out of scope. Otherwise, I wouldn't have added the EF Core column in the first place.

2024-06-12 22:56 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationFakers.cs
> +        .RuleFor(socialMediaAccount => socialMediaAccount.ValidatedAt, faker => faker.Date.Recent().ToUniversalTime())
> Is there a way for the client to send with "Z" suffix instead?

Yeah I mentioned that issue there https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1477#discussion_r1632492916 :/ I didn't find a good solution yet except adding a custom json converter.

2024-06-13 00:58 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +                    ValidatedAtDate = new DateTimeOffset(newAccount.ValidatedAtDate!.Value.ToDateTime(new TimeOnly()).ToUniversalTime()),
The ugliness comes from the fact that there is no direct conversion from DateOnly to DateTimeOffset. I'm not sure a custom serializer will help here.

2024-06-13 02:07 UTC, verdie-g commented
Here is SQL statements to create the table
```sql
CREATE TABLE "SocialMediaAccounts" (
    "Id" uuid NOT NULL,
    "AlternativeId" uuid,
    "FirstName" text,
    "LastName" text NOT NULL,
    "UserName" character varying(18),
    "CreditCard" text,
    "Email" text,
    "Password" text,
    "Phone" text,
    "Age" double precision,
    "ProfilePicture" text,
    "BackgroundPicture" text,
    "Tags" text[],
    "CountryCode" text,
    "Planet" text,
    "NextRevalidation" interval,
    "ValidatedAt" timestamp with time zone,
    "ValidatedAtDate" date,
    "ValidatedAtTime" time without time zone,
    CONSTRAINT "PK_SocialMediaAccounts" PRIMARY KEY ("Id")
);
```
I've updated the table accordingly.

2024-06-15 20:44 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +                    // TODO: ValidatedDateAt = new DateTimeOffset(fingerprint.ValidatedDateAt!.Value.ToDateTime(new TimeOnly()).ToUniversalTime()),
I added custom JSON converter for DateTime to always convert them to UTC. The code copied between the two tests projects. It could probably be shared in another assembly.

2024-06-19 20:05 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +        Func<Task<SocialMediaAccountPrimaryResponseDocument>> action = () => apiClient.PostSocialMediaAccountAsync(requestBody);
I don't see this change was applied. Did you push it?

2024-06-19 20:07 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationFakers.cs
> +        .RuleFor(socialMediaAccount => socialMediaAccount.ValidatedAt, faker => faker.Date.Recent().ToUniversalTime())
The custom converter is a nice solution.

2024-06-19 20:10 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationFakers.cs
> +        .RuleFor(socialMediaAccount => socialMediaAccount.ValidatedAtTime, faker => TimeOnly.FromDateTime(faker.Date.Recent())));
I don't see this changed. Did you know you can batch-up suggestions and commit them in one go? If you take the suggestion, it auto-resolves the conversation.

2024-06-19 20:13 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +                    ValidatedAtDate = new DateTimeOffset(newAccount.ValidatedAtDate!.Value.ToDateTime(new TimeOnly()).ToUniversalTime()),
Probably not, let's just leave it like this then.

2024-06-19 21:31 UTC, bkoelman reviewed
Great work on filling out the feature table.

Please update the following entries, replacing the '?':
- | [ValidateNever] | - | N | N | N |
- | [Remote] | - | N | N | N |

Also, `readOnly` and `writeOnly` need to move one column to the right. I've tried adding properties for them, but set-only causes a crash inside `Microsoft.AspNetCore.Mvc.ModelBinding.GetMetadataForProperty`, so let's forget about them.

I'm working on a PR to support atomic:operations in OpenAPI, which has heavy changes throughout all tests that I don't want to disturb you with. So if feasible, I'd like to get this PR merged first. With some luck, mine will be completed somewhere next week. No pressure, but it would be nice if we can get this one finalized in the next few days.

2024-06-19 21:34 UTC, bkoelman commented on test/OpenApiNSwagEndToEndTests/ModelValidation/ModelValidationTests.cs
> +                    // TODO: ValidatedDateAt = new DateTimeOffset(fingerprint.ValidatedDateAt!.Value.ToDateTime(new TimeOnly()).ToUniversalTime()),
Nice. We don't have a central place for that yet, so I'm fine with the duplication.

2024-06-19 22:06 UTC, verdie-g commented on test/OpenApiNSwagEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +        Func<Task<SocialMediaAccountPrimaryResponseDocument>> action = () => apiClient.PostSocialMediaAccountAsync(requestBody);
Maybe on the first file only. Done.

2024-06-19 22:10 UTC, verdie-g commented on test/OpenApiKiotaEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +    public async Task Cannot_use_double_outside_of_valid_range(int age)
Oh that's sad that values are silently casted to int :/

2024-06-19 22:11 UTC, verdie-g commented on test/OpenApiKiotaEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +    public async Task Cannot_use_invalid_url()
Yes, with NSwag ProfilePicture is a `System.Uri`. Here we get an opportunity to test the server-side url validation

2024-06-19 22:13 UTC, verdie-g commented on test/OpenApiKiotaEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +                    Tags = Enumerable.Repeat("-", length).ToList()
Tags is a List with Kiota and an ICollection with NSwag. I can change them both to ToList for consistency.

2024-06-19 22:15 UTC, verdie-g commented on test/OpenApiKiotaEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +    public async Task Cannot_use_invalid_url()
Reading your other comments, this doesn't JADNC so I'll remove it.

2024-06-19 22:18 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationFakers.cs
> +        .RuleFor(socialMediaAccount => socialMediaAccount.ValidatedAtTime, faker => TimeOnly.FromDateTime(faker.Date.Recent())));
I'll do that from now on

2024-06-19 22:19 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationTests.cs
> +        CultureInfo.CurrentCulture = new CultureInfo("fr-FR");
Ope, I didn't mean to leave that here.

2024-06-19 22:27 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(0.1, 122.9)]
Done. It doesn't seem to be supported by the OpenAPI library though.

2024-06-19 22:27 UTC, bkoelman commented on test/OpenApiKiotaEndToEndTests/ModelStateValidation/ModelStateValidationTests.cs
> +                    Tags = Enumerable.Repeat("-", length).ToList()
Ah, that explains it. Yes, please do.

2024-06-19 22:30 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +public sealed class SocialMediaAccount : Identifiable<Guid>
The above bullets are based on the assumption that Swashbuckle understands them, which I didn't verify. If that's not the case, there's no point in adding tests, but then please update the overview table with N for OpenAPI.

2024-06-19 22:31 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(0.1, 122.9)]
My comment was based on the assumption that Swashbuckle understands them, which I didn't verify. If that's not the case, there's no point in adding tests, but please update the overview table with a comment they're not supported.

2024-06-19 22:40 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +public sealed class SocialMediaAccount : Identifiable<Guid>
Done for Min/Max.

HashSet is trickier because it's not supported by EF.

The PR is already pretty large, I'll skip the DataType for now.

2024-06-20 07:36 UTC, bkoelman commented
That table update isn't correct. The Y/N columns need to move one position to the right.
![image](https://github.com/json-api-dotnet/JsonApiDotNetCore/assets/10324372/2b35d45f-614c-4bde-badb-0b7a1b4fc47a)

The same applies to: `[AllowedValues]`, `[DeniedValues]`, `[Remote]`, and `[ValidateNever]`.

2024-06-20 08:02 UTC, bkoelman requested changes
I've created https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2957 for the missing entries.

2024-06-20 12:31 UTC, verdie-g commented
> The Y/N columns need to move.

I used `N` to specify that it's not supported. I can use `-` instead.

2024-06-20 20:25 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/ModelStateValidationTests.cs
> +        CultureInfo.CurrentCulture = new CultureInfo("fr-FR");
This still hasn't been fully addressed.

2024-06-20 20:33 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(0.1, 122.9)]
Why were `[MinimumIsExclusive]` and `[MaximumIsExclusive]` fully removed in the latest commit? Please revert, I didn't ask for that. There's value in having them in end-to-end tests. If you insist on removing them, do so correctly by also removing the assertions on `exclusiveMaximum`/`exclusiveMinimum`.

2024-06-20 20:34 UTC, bkoelman requested changes
See comments. Not all changes have been applied yet, and unexpected parts got deleted.

2024-06-21 16:38 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(0.1, 122.9)]
>  there's no point in adding tests

I'm receiving some mixed signals here. I can add them back.

2024-06-21 16:44 UTC, verdie-g commented
> Both (remove culture and change assertions) haven't been addressed yet.

I'm not able to access the comment to answer but I could you clarify what you are expecting here.

2024-06-21 16:57 UTC, bkoelman commented
> > Both (remove culture and change assertions) haven't been addressed yet.
> 
> I'm not able to access the comment to answer but I could you clarify what you are expecting here.

Using the dollar sign and putting literal values in there, so it becomes culture-insensitive.

2024-06-21 16:58 UTC, bkoelman commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(0.1, 122.9)]
To clarify: they don't matter for OpenApiTests, but do provide value in EndToEndTests.

2024-06-21 18:37 UTC, verdie-g commented on test/OpenApiTests/ModelStateValidation/SocialMediaAccount.cs
> +    [Range(0.1, 122.9)]
Got it, makes sense

2024-06-21 19:58 UTC, bkoelman approved these changes
Thanks, this is in great shape now!

2024-06-21 20:19 UTC, merged