Support for Kiota to generate OpenAPI clients
json-api-dotnet/JsonApiDotNetCore pull request #1479
Opened 2024-02-25 13:49 UTC by bkoelman

This PR adds a support library, tests, examples and documentation for using JsonApiDotNetCore with [Kiota](https://learn.microsoft.com/en-us/openapi/kiota/overview), which is a fairly new OpenAPI client generator that supports the following languages: C#, Go, Java, PHP, Python, Ruby, Swift and TypeScript.

Because the project is still young, it has some rough edges and bugs, for which we provide workarounds:
- Everything is always nullable https://github.com/microsoft/kiota/issues/3911
- Query strings are inaccessible https://github.com/microsoft/kiota/issues/3800
- Incompatible classes are generated for includes https://github.com/microsoft/kiota/issues/4191
- HTTP 304 (Not Modified) is not properly recognized https://github.com/microsoft/kiota/issues/4190
- Warning for `format:uri` in HTTP Location header https://github.com/microsoft/kiota/issues/4227

In preparation, this PR contains various refactorings. See the individual commit messages for details.

Closes #1458.

#### QUALITY CHECKLIST
- [x] Changes implemented in code
- [x] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [x] Adapted tests
- [x] Documentation updated

2024-02-26 02:39 UTC, bkoelman commented
@verdie-g Would you like to review this PR?

2024-02-26 02:44 UTC, verdie-g commented
I can have a look if there is no hurry to merge it.

2024-02-26 02:47 UTC, bkoelman commented
> I can have a look if there is no hurry to merge it.

There's no urgency. Also, the changes are relevant to be aware of for future development. Probably easiest to review per commit.

2024-02-27 22:46 UTC, verdie-g requested changes

2024-02-27 22:46 UTC, verdie-g commented on docs/usage/openapi-client.md
> +dotnet add package JsonApiDotNetCore.OpenApi.Client.NSwag
It seems like this nuget was not published yet. I really have doubts about the future of NSwag and Kiota looks promising. Do you plan maintaining both nugets?

2024-02-27 22:46 UTC, verdie-g commented on docs/usage/openapi-client.md
> +For C# clients, we provide an additional package that provides workarounds for bugs in NSwag and enables using partial PATCH/POST requests.
> enables using partial PATCH/POST requests

Is this supported in Kiota?

2024-02-27 22:46 UTC, verdie-g commented on package-versions.props
> +    <NewtonsoftJsonFrozenVersion>13.0.3</NewtonsoftJsonFrozenVersion>
Why is Newtonsoft.Json added? I suppose Kiota uses STJ

2024-02-27 22:46 UTC, verdie-g commented on src/Examples/OpenApiKiotaClientExample/ColoredConsoleLogHttpMessageHandler.cs
> +    [UsedImplicitly]
I suppose this is added to avoid a warning in release mode? Maybe you can wrap that in `#if DEBUG` too

2024-02-27 22:46 UTC, verdie-g commented on src/Examples/OpenApiKiotaClientExample/GeneratedCode/Api/ApiRequestBuilder.cs
Can the client be generated as a single file? Also I don't think the NSwag client was versioned. What's the difference with Kiota?

2024-02-27 22:46 UTC, verdie-g commented on src/Examples/OpenApiKiotaClientExample/Program.cs
> +builder.Services.AddSingleton<IAuthenticationProvider, AnonymousAuthenticationProvider>();
```suggestion
builder.Services
    .AddHostedService<Worker>()
    .AddSingleton<ColoredConsoleLogHttpMessageHandler>()
    .AddSingleton<SetQueryStringHttpMessageHandler>()
    .AddSingleton<IAuthenticationProvider, AnonymousAuthenticationProvider>();
```

2024-02-27 22:46 UTC, verdie-g commented on src/Examples/OpenApiKiotaClientExample/Worker.cs
> +                // Workaround for https://github.com/microsoft/kiota/issues/3800.
That's awkward. I feel like this should be a blocker to publish a nuget for Kiota

2024-02-27 22:46 UTC, verdie-g commented on src/JsonApiDotNetCore.OpenApi.Client.NSwag/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("OpenApiNSwagClientTests")]
That can be added to the csproj instead
```xml
<InternalsVisibleTo Include="OpenApiNSwagClientTests" />
```

2024-02-27 22:46 UTC, verdie-g commented on test/OpenApiKiotaEndToEndTests/Headers/ETagTests.cs
> +        var apiClient = new HeadersClient(requestAdapter);
What do you think of forcing
```
var a = new A();
```
to be replaced with
```
A a = new();
```
?

2024-02-28 00:35 UTC, bkoelman commented on docs/usage/openapi-client.md
> +dotnet add package JsonApiDotNetCore.OpenApi.Client.NSwag
> It seems like this nuget was not published yet.

It will be published automatically to the GitHub feed when merging this PR.

> I really have doubts about the future of NSwag and Kiota looks promising. Do you plan maintaining both nugets?

I share your thoughts. I'm not sure yet, that's why I wanted to give Kiota a try. There are more client generators, which I haven't tried yet, listed at https://marketplace.visualstudio.com/items?itemName=ChristianResmaHelle.ApiClientCodeGenerator2022.

2024-02-28 00:39 UTC, bkoelman commented on docs/usage/openapi-client.md
> +For C# clients, we provide an additional package that provides workarounds for bugs in NSwag and enables using partial PATCH/POST requests.
Yes, see the next remark in this file:
> [!CAUTION]
> The `--backing-store` switch is needed for JSON:API partial PATCH/POST requests to work correctly.

It tracks property assignments, similar to `INotifyPropertyChanged`.

2024-02-28 00:42 UTC, bkoelman commented on package-versions.props
> +    <NewtonsoftJsonFrozenVersion>13.0.3</NewtonsoftJsonFrozenVersion>
NSwag requires it. Previously, the project referenced Swashbuckle, which implicitly imports Newtonsoft.Json.

2024-02-28 00:51 UTC, bkoelman commented on src/Examples/OpenApiKiotaClientExample/GeneratedCode/Api/ApiRequestBuilder.cs
> Can the client be generated as a single file?

Not that I'm aware of. I had to git-ignore `kiota-lock.json` due to a limitation that's mentioned in the PR description.

> Also I don't think the NSwag client was versioned. What's the difference with Kiota?

I tried to add NSwag under source control too, but ran into issues. See the PR description. NSwag has a switch to generate multiple files, we could use that.

2024-02-28 00:52 UTC, bkoelman commented on src/Examples/OpenApiKiotaClientExample/Program.cs
> +builder.Services.AddSingleton<IAuthenticationProvider, AnonymousAuthenticationProvider>();
That conflicts with code cleanup. It can be worked around by adding formatter directives in the comments, but I don't see the point.

2024-02-28 00:53 UTC, bkoelman commented on src/Examples/OpenApiKiotaClientExample/Worker.cs
> +                // Workaround for https://github.com/microsoft/kiota/issues/3800.
Feel free to upvote the issues I created, perhaps it helps.

2024-02-28 00:53 UTC, bkoelman commented on src/JsonApiDotNetCore.OpenApi.Client.NSwag/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("OpenApiNSwagClientTests")]
I know, but what would be the advantage?

2024-02-28 00:54 UTC, bkoelman commented on test/OpenApiKiotaEndToEndTests/Headers/ETagTests.cs
> +        var apiClient = new HeadersClient(requestAdapter);
I'm not aware of a way to do that, are you?

2024-02-28 02:12 UTC, verdie-g commented on test/OpenApiKiotaEndToEndTests/Headers/ETagTests.cs
> +        var apiClient = new HeadersClient(requestAdapter);
I think [IDE0090](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0090) covers that.

2024-02-28 02:38 UTC, verdie-g commented on src/JsonApiDotNetCore.OpenApi.Client.NSwag/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("OpenApiNSwagClientTests")]
Just group assembly-level settings together. For example if the nullable could be enabled globally from a c# file you would probably still want it to be defined in the csproj.

2024-02-28 02:43 UTC, verdie-g commented on docs/usage/openapi-client.md
> +dotnet add package JsonApiDotNetCore.OpenApi.Client.NSwag
We use both AutoRest and NSwag at my company and there is not one that I prefer. I'm usually pretty confident when Microsoft releases a library like Kiota to address some weaknesses in the .NET ecosystem.

I'm really concerned about maintaining more than 1 openapi client though. I would hold off releasing these nugets until Kiota is mature enough to take a decision on which one to commit to.

2024-02-28 02:59 UTC, bkoelman commented on src/JsonApiDotNetCore.OpenApi.Client.NSwag/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("OpenApiNSwagClientTests")]
AssemblyInfo.cs is the traditional place to declare assembly-level attributes. Project-level configuration is unrelated to that.

2024-02-28 03:06 UTC, bkoelman commented on test/OpenApiKiotaEndToEndTests/Headers/ETagTests.cs
> +        var apiClient = new HeadersClient(requestAdapter);
Thanks. I'm wondering if Resharper provides something similar. Created https://youtrack.jetbrains.com/issue/RSRP-496140/Target-typed-new-style.

2024-02-28 03:14 UTC, verdie-g commented on src/JsonApiDotNetCore.OpenApi.Client.NSwag/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("OpenApiNSwagClientTests")]
I would argue AssemblyInfo.cs is legacy thing from .NET framework. Everything that it used to contain is now defined in the csproj which then automatically generates an AssemblyInfo.cs when `GenerateAssemblyInfo` is true (the default).

2024-02-28 03:29 UTC, bkoelman commented on docs/usage/openapi-client.md
> +dotnet add package JsonApiDotNetCore.OpenApi.Client.NSwag
The goal of our OpenAPI efforts is to generate documentation and enable client generation. The popularity of libraries for the latter changes over time. We initially chose to use NSwag because VS has built-in support for it. The OpenAPI document produced needs to be generally usable, so we have tests (using various tools), to prove we're actually producing something that's useful.

I don't think an open-source project providing a server should dictate which client must be used, as that defeats the purpose of having standards (JSON:API, OpenAPI) in the first place.

We're not maintaining any client generators, just telling people how to use them. And write tests to prove it actually works. Possibly combined with a small library to ease the pain, so users don't need to reinvent the wheel. It's not very different from what we do for Entity Framework Core.

2024-03-02 02:58 UTC, merged