Return proper response for empty parameter name
json-api-dotnet/JsonApiDotNetCore pull request #1484
Opened 2024-02-26 03:14 UTC by verdie-g

Closes #1480 

#### QUALITY CHECKLIST
- [X] Changes implemented in code
- [X] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [X] Adapted tests
- [ ] Documentation updated

2024-02-26 09:22 UTC, bkoelman commented on src/JsonApiDotNetCore/QueryStrings/QueryStringReader.cs
> +                throw new InvalidQueryException("Empty query string parameter name.", null);
I don't see why JADNC should forbid using empty parameters. It just shouldn't crash on them.

2024-02-26 23:28 UTC, verdie-g commented on src/JsonApiDotNetCore/QueryStrings/QueryStringReader.cs
> +                throw new InvalidQueryException("Empty query string parameter name.", null);
Fair

2024-02-26 23:44 UTC, bkoelman requested changes
Thanks

2024-02-26 23:44 UTC, bkoelman commented on test/JsonApiDotNetCoreTests/IntegrationTests/QueryStrings/QueryStringTests.cs
> +    [InlineData("foo")]
```suggestion
    [InlineData("bar")]
```
To match up with the test above it.

2024-02-26 23:44 UTC, bkoelman commented on test/JsonApiDotNetCoreTests/IntegrationTests/QueryStrings/QueryStringTests.cs
> +    public async Task Should_ignore_query_parameter_with_empty_name(string parameterValue)
Looking at the names of existing tests in this file:
- Cannot_use_unknown_query_string_parameter
- Can_use_unknown_query_string_parameter
- Cannot_use_empty_query_string_parameter_value

I'd suggest:
```suggestion
    public async Task Can_use_empty_query_string_parameter_name(string parameterValue)
```

2024-02-26 23:45 UTC, bkoelman commented
Please update to the latest master.

2024-02-28 00:58 UTC, bkoelman approved these changes
LGTM

2024-02-28 00:59 UTC, merged