Fix/786
json-api-dotnet/JsonApiDotNetCore pull request #805
Opened 2020-08-26 08:54 UTC by maurei

Closes #786 

- tbc -

2020-08-26 13:17 UTC, bart-degreed requested changes
See review feedback. In general, these types are mixing a lot of concerns and are deeply independent on each other, which makes it hard to track what is going on. But this was already the case, I'm not asking you to clean that up.

2020-08-26 13:17 UTC, bart-degreed commented on src/JsonApiDotNetCore/Extensions/ServiceCollectionExtensions.cs
> +            applicationBuilder.RegisterResourceSources(dbContextType, autoDiscovery, resources);
This is vague terminology: what are 'sources'? To me this indicates the method is doing too much and should be split into individual methods instead (like it was before).

2020-08-26 13:17 UTC, bart-degreed commented on src/JsonApiDotNetCore/Builders/ResourceGraphBuilder.cs
> +        private ResourceContext CreateResourceContext(string pluralizedResourceName, Type resourceType, Type idType) => new ResourceContext
I think this should just be `publicName`, because it is the publicly exposed resource name in json:api. Comparable to `AttrAttribute.PublicName`. The fact that it is being pluralized is an implementation detail and may as well not be the case, because callers can specify whatever they like here. I think the whole point of making this customizable is that it does not need to apply to any casing or naming convention.

2020-08-26 13:17 UTC, bart-degreed commented on src/JsonApiDotNetCore/Builders/JsonApiApplicationBuilder.cs
> +        private void ConfigureResources()
Based on the documentation above this method, I think this should just be named something like ConstructResourceGraph, or am I missing something here?

2020-08-26 13:17 UTC, bart-degreed commented on src/JsonApiDotNetCore/Builders/JsonApiApplicationBuilder.cs
> +        private IResourceGraph BuildResourceGraph(ServiceProvider intermediateProvider)
This method is not just building the resource graph, but a lot more. It scans the DbContext, then scans assemblies, then delegates building the graph.

2020-08-26 13:17 UTC, bart-degreed commented on src/JsonApiDotNetCore/Builders/JsonApiApplicationBuilder.cs
> +            _serviceDiscoveryFacade.DiscoverServices();
Scanning for services in assemblies is a separate operation from registering objects in the D/I container, so I don't think this call belongs inside this method.

2020-08-26 13:17 UTC, bart-degreed commented on src/JsonApiDotNetCore/Builders/JsonApiApplicationBuilder.cs
> +        public void RegisterResourceSources(Type dbContextType, Action<IServiceDiscoveryFacade> autoDiscovery,
Why not pass these in the constructor? It does not look like they change over time,

2020-08-26 13:20 UTC, bart-degreed commented
I think this PR should address #807 as well. Docs are fully up-to-date and verified right now, so I don't see why it should be postponed.

2020-08-26 13:23 UTC, bart-degreed commented
Another question: can you confirm that that https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/800#issuecomment-674380601 still holds?

2020-08-27 07:28 UTC, maurei commented on test/DiscoveryTests/ServiceDiscoveryFacadeTests.cs
> +            IServiceDiscoveryFacade facade = new ServiceDiscoveryFacade(_services, _resourceGraphBuilder);
Agree. It's beyond the scope of this PR but very little work, so I'll add them

2020-08-27 07:32 UTC, maurei commented on src/JsonApiDotNetCore/Internal/JsonApiRoutingConvention.cs
> +            if (!_registeredResources.TryGetValue(model.ControllerName, out var resourceContext))
I agree that if inversions in general isn't a thing to pursue, but in this case I considered it more readable

2020-08-27 07:48 UTC, maurei commented on src/JsonApiDotNetCore/Builders/JsonApiApplicationBuilder.cs
> +        public void RegisterResourceSources(Type dbContextType, Action<IServiceDiscoveryFacade> autoDiscovery,
This comment also applies to the `Action<JsonApiOptions>` argument, moving that too the constructor too

2020-08-27 07:48 UTC, maurei commented on src/JsonApiDotNetCore/Builders/ResourceGraphBuilder.cs
> +        private ResourceContext CreateResourceContext(string pluralizedResourceName, Type resourceType, Type idType) => new ResourceContext
Agree

2020-08-27 07:49 UTC, maurei commented on src/JsonApiDotNetCore/Extensions/ServiceCollectionExtensions.cs
> +            applicationBuilder.RegisterResourceSources(dbContextType, autoDiscovery, resources);
No longer relevant as arguments are now passed in the constructor

2020-08-27 07:53 UTC, maurei commented on src/JsonApiDotNetCore/Graph/ServiceDiscoveryFacade.cs
> +        void IServiceDiscoveryFacade.DiscoverServices()
I think the method name is descriptive: the method scans for anything that needs to be registered with the DI container. Services here refers to .net core DI-registrable services, not the JADNC service layer.

Splitting into resources and DI-registrable services makes sense because the former aren't added to the DI container. Also, the resources need to be discovered earlier than the rest, which is why this call is factored out. There is no advantage to factoring out resourcedefs/repositories/resourceservices into different method calls because these are still handled at once anyway

2020-08-27 08:00 UTC, maurei commented on src/JsonApiDotNetCore/Graph/ServiceDiscoveryFacade.cs
> +        void IServiceDiscoveryFacade.DiscoverServices()
I think the method name is sufficiently descriptive: the method scans for anything that needs to be registered with the DI container. "Services" here refers to .net core DI-registrable services, not the JADNC service layer.

Factoring out the (1) resource discovery and (2) DI-registrable service discovery from the former discovery call is required because (1) is needed in a different phase: at the time of the `resourceConfigurationIntermediateProvider` instantiation, (2) is only performed after all intermediate providers have been disposed. At this point resourcedefs/repositories/resourceservices are still registered at the same time so there is no advantage to factoring these out to separate calls, like there is with (1). It's also justifiable to distinguish between (1) and (2) because only the latter are registrable with the DI container.

2020-08-27 08:03 UTC, maurei commented on src/JsonApiDotNetCore/Builders/JsonApiApplicationBuilder.cs
> +            _serviceDiscoveryFacade.DiscoverServices();
Proceeding to refactor this a bit further. This comment also applies to `ConfigureMvc`, it does a lot more than just configuring .net core `MvcOptions`.

2020-08-27 08:10 UTC, maurei commented on src/JsonApiDotNetCore/Builders/JsonApiApplicationBuilder.cs
> +        private void ConfigureResources()
No, it just *configures* the resource graph builder by invoking the action provided by the user in the `AddJsonApi( .. )` call, in which `AddResource( .. )` calls are performed. I think this is pretty clear from the method name + docs, but let me know if you'd like to see a change here  

The actual construction of the resource graph is performed else where, internally.

2020-08-27 10:16 UTC, maurei commented on src/JsonApiDotNetCore/Builders/JsonApiApplicationBuilder.cs
> +        private void ConfigureResources()
This is no longer applicable after most recent refactor

2020-08-27 10:17 UTC, maurei commented on src/JsonApiDotNetCore/Builders/JsonApiApplicationBuilder.cs
> +        private IResourceGraph BuildResourceGraph(ServiceProvider intermediateProvider)
JsonApplicationBuilder flow has been refactored to clean up violations of single responsibility

2020-08-27 10:18 UTC, maurei commented on src/JsonApiDotNetCore/Builders/JsonApiApplicationBuilder.cs
> +        public void RegisterResourceSources(Type dbContextType, Action<IServiceDiscoveryFacade> autoDiscovery,
This is no longer applicable after most recent refactor

2020-08-27 10:23 UTC, maurei commented
> Another question: can you confirm that [#800 (comment)](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/800#issuecomment-674380601) still holds?

No: it this has not been the case for a long while now. The mapping between resources/routes/controllers is handled by `IJsonApiRoutingConvention`, also see `IControllerResourceMapping` which it inherits. Docs need to be updated on this, I'll put some work in #807

2020-08-27 12:57 UTC, bart-degreed commented on src/JsonApiDotNetCore/Internal/JsonApiRoutingConvention.cs
> +            if (!_registeredResources.TryGetValue(model.ControllerName, out var resourceContext))
I disagree, there are now three exit paths instead of two, where two of them now return null. It believe it would be more optimal to return null only once and I don't think we are dealing with such deep nesting here that the flow would be difficult to track otherwise.

But I'm fine with this change for now, as we have no coding guidelines in this repo at the moment.

2020-08-27 13:01 UTC, bart-degreed commented on src/JsonApiDotNetCore/Graph/ServiceDiscoveryFacade.cs
> +        void IServiceDiscoveryFacade.DiscoverServices()
I'm fine either way, but "Services" is ambiguous here, renaming this to `DiscoverInjectedTypes` would help.

2020-08-27 13:29 UTC, maurei commented on src/JsonApiDotNetCore/Internal/JsonApiRoutingConvention.cs
> +            if (!_registeredResources.TryGetValue(model.ControllerName, out var resourceContext))
You changed my mind. Minimizing for the amounts of exit paths indeed is nicer

2020-08-27 13:29 UTC, maurei commented on src/JsonApiDotNetCore/Graph/ServiceDiscoveryFacade.cs
> +        void IServiceDiscoveryFacade.DiscoverServices()
I agree on that. Changed!

2020-08-28 23:21 UTC, bart-degreed commented
I've found there is no need for `UseJsonApi()` to have an extra parameter. When `AddMvcOptions` is called multiple times, multiple callbacks are executed in the order provided. The next code enables to replace services/filters etc, without the use of `UseJsonApi(Action<MvcOptions>)`.
```c#
public class Startup
{
    private Action<MvcOptions> _postConfigureMvcOptions;

    public void ConfigureServices(IServiceCollection services)
    {
        var mvcCoreBuilder = services.AddMvcCore();

        // We can affect options *before* AddJsonApi

        mvcCoreBuilder.AddMvcOptions(x =>
        {
            Debug.WriteLine("** PRE **");
        });

        services.AddJsonApi<AppDbContext>(ConfigureJsonApiOptions, discovery => discovery.AddCurrentAssembly(), mvcBuilder: mvcCoreBuilder);

        // We can affect options *after* AddJsonApi

        mvcCoreBuilder.AddMvcOptions(x =>
        {
            Debug.WriteLine("** POST **");

            _postConfigureMvcOptions?.Invoke(x);
        });
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment environment)
    {
        // Using a callback, we can defer to later (when service collection has become available).

        _postConfigureMvcOptions = x =>
        {
            // shows we have access to injected stuff here
            var customFilter = app.ApplicationServices.GetRequiredService<IQueryStringActionFilter>();

            // the next line breaks stuff intentionally (it proves we are not too late to change filters)
            x.Filters.Clear();
        };
        
        app.UseRouting();
        app.UseJsonApi();
        app.UseEndpoints(endpoints => endpoints.MapControllers());
    }
}
```

This is similar to what is described at https://stackoverflow.com/questions/56042989/what-are-the-costs-and-possible-side-effects-of-calling-buildserviceprovider-i, so I'd say we should not add the new parameter.

2020-08-28 23:31 UTC, bart-degreed commented
Looking at remaining usages of `intermediateServiceProvider`. Aside from some logging (not critical and it can easily be deferred to later) the only one left is scanning the `DbContext` model. Would it be feasible to move building the resource graph from `AddJsonApi` to `UseJsonApi`?

2020-08-28 23:41 UTC, bart-degreed commented
Perhaps we should explore using the built-in options support of netcore using `services.Configure` as described here: https://andrewlock.net/access-services-inside-options-and-startup-using-configureoptions/

2020-08-31 08:57 UTC, maurei commented
> Would it be feasible to move building the resource graph from AddJsonApi to UseJsonApi?
I don't think this is doable. In the `public void Configure( ... )` phase, the application's `ServiceProvider` has already been built, i.e. we won't be able to register `IResourceGraph` anymore. We could consider registering a `IResourceGraphProvider` instead and expose a deferred build of the `ResourceGraph` through an internal setter. Something like
```c#
public interface IResourceGraphProvider
{
	IResourceGraph Get();
	internal void Set(IResourceGraph set);
}
```
I'm not sure if I like this though. I prefer having the internally used intermediate service provider as it is shielded shut off from the user, so all of the previously discussed risks are not really a threat (except for a custom `ILoggerFactory` implementation, for which I think the risk of captivity or disposal bugs is negligible). 

> Perhaps we should explore using the built-in options support of netcore using `services.Configure` as described here: https://andrewlock.net/access-services-inside-options-and-startup-using-configureoptions/

I think in this approach code is executed in the phase 2 config, so that would only work if we defer the construction of the resource graph to this phase. And this is problematic, as described above.


> I've found there is no need for UseJsonApi() to have an extra parameter
Yes! You're right. Good catch. Removing the parameter.

2020-09-01 07:53 UTC, maurei commented
We have discussed the topic in a private meeting and have arrived at the following conclusions:

- Even though microsoft warns for building a service provider like we do with our intermediate service provider, we have not identified any risks in our current use-case and have decided on relying on an intermediate provider for reflecting on the DbContext during startup phase 1.
- Building the resource graph during start up phase 2 is currently not possible, and the changes we would need to introduce to support it are not desirable (`IResourceGraphProvider` instead of `IResourceGraph`).
- `IInverseRelationshipResolver` needs to be put back to phase 2

2020-09-01 13:04 UTC, bart-degreed commented
You removed `IResourceGraphBuilder`, which makes inheritdoc invalid on ResourceGraphBuilder. Instead, replace them with the actual documentation that was on the interface. Same for ServiceDiscoveryFacade.

2020-09-01 14:00 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/IJsonApiTypeMatchFilter.cs
> +    /// Action filter used to verify the incoming type matches the target type, else return a 409
. at end

2020-09-01 14:02 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/JsonApiExceptionFilter.cs
> +            };
We've discussed this, don't make changes like that.

2020-09-01 14:03 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/IJsonApiInputFormatter.cs
> +namespace JsonApiDotNetCore.Formatters
This is now in the wrong namespace. To fix them all, use Resharper/Rider to find and fix similar issues in project.

2020-09-01 14:06 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/JsonApiOutputFormatter.cs
> +
These changes are not helping, if you're not going to fix them all. I get that when you're rewriting a whole file then it makes sense, but this is just adding clutter to the PR.

2020-09-01 14:08 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/JsonApiRoutingConvention.cs
> +            return null;
The null check was removed here, which looks wrong. And please keep the code style similar to how it was.

Did you check that newly added code has proper null checks on publicly-visible methods?

2020-09-01 14:13 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/JsonApiTypeMatchFilter.cs
> +            if (!context.HttpContext.IsJsonApiRequest())
Missing null check from old code. And again, you're re-ordering code with early returns that makes the diff harder to read without adding value, so please revert to the original code from IncomingTypeMatchFilter.

2020-09-01 14:18 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/QueryStringActionFilter.cs
> +        public void OnActionExecuting(ActionExecutingContext context)
I think it is a mistake to switch from async to sync here and in all other filters. Especially from the point of extensibility we should always prefer async where available. Doing sync work can always be done, but when async dependencies exist, it is forcing the users to block the thread which is a no-go for scalable applications.

2020-09-01 14:26 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/QueryStringActionFilter.cs
> +            _queryStringReader.ReadAll(disableQueryAttribute);
Why is this duplicated?

2020-09-01 14:26 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/QueryStringActionFilter.cs
> +            if (!context.HttpContext.IsJsonApiRequest())
Nice! That one was missing.

2020-09-01 14:29 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/IJsonApiInputFormatter.cs
> +    public interface IJsonApiInputFormatter : IInputFormatter { }
These interfaces should be close to their implementing type (same namespace and folder). As these are intended to plug into the D/I system (the actual processing is deferred to elsewhere) I believe the best location to put these is in the Configuration namespace, next to all the middleware and IoC code.

2020-09-01 14:31 UTC, bart-degreed commented on src/JsonApiDotNetCore/AssemblyInfo.cs
> +[assembly:InternalsVisibleTo("ResourceEntitySeparationExampleTests")]
There existed two versions of this file, which I merged into Properties\AssemblyInfo.cs (which is the default location). In the process, I removed all assembly:InternalsVisibleTo lines that were unneeded.

2020-09-01 14:33 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/DocumentTests/LinksWithoutNamespaceTests.cs
> +        public NoNamespaceStartup(IConfiguration configuration) : base(configuration) { }
Another unneeded change that makes the diff larger than needed.

2020-09-01 14:33 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/Factories/ClientGeneratedIdsApplicationFactory.cs
> +                }, discovery => discovery.AddAssembly(Assembly.Load(nameof(JsonApiDotNetCoreExample))));
Unneeded change that makes the diff larger than needed.

2020-09-01 14:33 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/TestableStartup.cs
> +        public TestableStartup(IConfiguration configuration) : base(configuration) { }
Unneeded change that makes the diff larger than needed.

2020-09-01 14:34 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/Acceptance/NonJsonApiControllerTests.cs
> +            var test = await response.Content.ReadAsStringAsync();
Why was this added?

2020-09-02 06:20 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/Acceptance/NonJsonApiControllerTests.cs
> +            var test = await response.Content.ReadAsStringAsync();
Whoops. That slipped through my reviews. It's a piece of left-over debugging code. Will remove

2020-09-02 06:29 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +}
> Try to provide code samples that actually work.
I disagree. The goal of these examples is not to provide the developer with a minimally working example that works off-the-shelve. That results overly verbose examples while the code of interest is actually a very minimal set of lines. (Microsoft does the former in their documentation and I have always found their examples extremely unreadable, I don't want to go down that road). The goal of these examples is to point the developer to the relevant bits of code, under the assumption that the developer knows how to call `AddJsonApi` or eg even register a `CustomFilter`. If the developer does not know this, this part of the documentation is not the place to be anyway.

2020-09-02 06:38 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +
I disagree. This part of the documentation aims to elaborate on the extensibility of the middleware, therefore having an overview of what the components are in the middleware makes a lot of sense. The extensibility of the middleware has been made extremely accessible, there is no point in having this section of the documentation if the core message of this section is: check out the source code to figure out how to.

2020-09-02 06:40 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +2. In the Startup.Configure method, configure your application to use routing, to add the JsonApiMiddleware and to configure endpoint routing.
I have changed the documentation to be more elaborate on what actually happens in the middleware, because else I don't think there is any point in having this section at all. In the previous state it did not really explain anything about the extensibility of the middleware. See my comment on your next review comment below.

2020-09-02 06:43 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +JsonApiDotNetCore internally configures `MvcOptions` when calling `AddJsonApi( ... )`. However, it is still possible to register a custom configuration callback. To achieve this it is recommended to
I disagree. I included this piece to provide the developers with some background information on what took us quite some time to figure out. As such the provided insight around the `AddJsonApi` is very relevant. Again, I strongly think we should include this type of information as this topic is about the *extensibility* of the middleware. Without it, we might as well remove the entire section, because we would be claiming it is extensible while requiring the developers to dive into the source code to figure out the caveats. That is no user-friendly extensibility.

2020-09-02 06:44 UTC, maurei commented on docs/usage/resource-graph.md
> +current assembly by adding the following to your `Startup` class.
Agree, will edit

2020-09-02 06:44 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +It is also possible to directly access the .NET Core `MvcOptions` object and have full controll over which components are registered.
Will change

2020-09-02 06:46 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +JsonApiDotNetCore internally configures `MvcOptions` when calling `AddJsonApi( ... )`. However, it is still possible to register a custom configuration callback. To achieve this it is recommended to
Will change

2020-09-02 06:46 UTC, maurei commented on docs/usage/resource-graph.md
> +        builder.AddResource<Person>();
Will change

2020-09-02 06:53 UTC, maurei commented on docs/usage/resource-graph.md
> +}
Agree. Will move this bit over.

2020-09-02 06:56 UTC, maurei commented on docs/usage/resource-graph.md
> +1. The `publicName` option when manually adding a resource to the graph
Will edit

2020-09-02 06:56 UTC, maurei commented on docs/usage/resource-graph.md
> +    builder.AddResource<Person>(publicName: "people");
Will edit

2020-09-02 07:01 UTC, maurei commented on docs/usage/routing.md
> +There are two ways the library will try to create a route for a controller:
Will move it up

2020-09-02 07:05 UTC, maurei commented on docs/usage/routing.md
> +  }]
Partially agree. The segment can be formulated in a simpler way, but you've left out two essential pieces of information
- not just any type parameter, it needs to be a *resource*.
- the explicit statement that changing the `publicName` of the resource directly affects the route. There is no point in leaving this out while having this section.

Will update accordingly

2020-09-02 07:25 UTC, maurei commented on docs/usage/routing.md
> +```
Your suggestion doesn't really offer any insight on how to customise routes.

Regardless, will simplify.

2020-09-02 07:26 UTC, maurei commented on docs/usage/routing.md
> +It is possible to fully customize routing behaviour by registering a `IJsonApiRoutingConvention` implementation.
Behaviour is valid spelling

2020-09-02 07:41 UTC, maurei commented on docs/usage/routing.md
> +It is possible to fully customize routing behaviour by registering a `IJsonApiRoutingConvention` implementation.
>  this is not something users are likely to ever do

- I try to be more conservative in my assumptions on how users will use the framework. At my previous employer we needed this, which is why I built it in the first place
- Why exclude it? Conventional routing is a routing approach supported off-the-shelve by dotnet core, and what we're doing here is re-exposing that configurability.

2020-09-02 07:42 UTC, maurei commented on src/Examples/JsonApiDotNetCoreExample/Startups/EmptyStartup.cs
> +using Microsoft.Extensions.Logging;
What do you mean with curly formatting?

Will remove unneeded using statements

2020-09-02 07:43 UTC, maurei commented on src/Examples/JsonApiDotNetCoreExample/Startups/TestStartup.cs
> +using Microsoft.Extensions.Logging;
Will remove unneeded using statements

2020-09-02 07:44 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ApplicationBuilderExtensions.cs
> +            };
In general I agree, but in this case I chose to put it inline because there is not a lot to debug here: `GetRequiredService` will throw if the service is not found. Putting it on separate lines does not add any value

2020-09-02 07:45 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +        public Action<MvcOptions> ConfigureMvcOptions { get; set; }
Will add

2020-09-02 07:48 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +            _serviceDiscoveryFacade = new ServiceDiscoveryFacade(_services, _resourceGraphBuilder, loggerFactory);
I think this is a bit of an exaggeration: its 6 short lines of code. 

Will add line breaks regardless

2020-09-02 07:55 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +            _intermediateProvider.Dispose();
Will change

2020-09-02 07:59 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +        /// Configures and build the resource graph with resources from the provided sources and adds it to the DI container.
That's incorrect. The resource graph is being added to the DI container, not the resources individually

2020-09-02 08:07 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +            UserConfigureResources(configureResources, _resourceGraphBuilder);
I think it is more as it is. The encapsulating method does three things: adding resources from 3 resources: autodiscovery, dbcontext and the user configuration. Right now these three actions are separate methods with descriptive method names. Just inlining this method and keeping the other two does breaks with that consistency and does not add any value.

2020-09-02 08:07 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +            if (_options.EnableResourceHooks)
will add

2020-09-02 08:20 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +            _serviceDiscoveryFacade = new ServiceDiscoveryFacade(_services, _resourceGraphBuilder, loggerFactory);
It is not, line breaks help readers to visually group and distinct lines of code that have a different goal. Input validation is something different than fetching services. There are coding guidelines that requires methods to contain at most 7 statements, so this is not an exaggeration. The visual distinction is helpful for both long and short methods, as it is not a construct to group a fixed number of lines but to aid in the intent of code.

2020-09-02 08:25 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +            UserConfigureResources(configureResources, _resourceGraphBuilder);
Do not use 'user' when referring to calling code, 'user' is a term that is used for many different concepts depending on who's looking at it. Therefore the method name you're using *adds confusion* because it hides what it does without providing a clear explanation. The containing code itself is clearer if that's not abstracted away. Sometimes it is good when methods contain a single line of code, when that line of code describes some implementation details while the containing method clarifies *why* it was implemented like that, this adding value. This method name is adding no value in that sense. If a method does 3 things, its single responsibility is orchestration. That does not mean it needs to delegate that to child methods if they are simple enough. Inlining adds value because it makes the code simpler without sacrificing readability.

2020-09-02 08:27 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +        /// Configures and build the resource graph with resources from the provided sources and adds it to the DI container.
You're right on 'them', 'build' needs to change though.

2020-09-02 08:28 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/ApplicationBuilderExtensions.cs
> +            };
If is not about throwing, it is about inspecting which implementation was returned from the service provider. Putting it into a variable enables to hover over it and inspect directly.

2020-09-02 08:29 UTC, bart-degreed commented on src/Examples/JsonApiDotNetCoreExample/Startups/EmptyStartup.cs
> +using Microsoft.Extensions.Logging;
Changing from:
```c#
{
}
```
to:
```c#
{ }
```

2020-09-02 08:30 UTC, bart-degreed commented on docs/usage/routing.md
> +It is possible to fully customize routing behaviour by registering a `IJsonApiRoutingConvention` implementation.
In British English, yes. Not in American English.

2020-09-02 08:42 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +                sp => sp.GetService<IResourceDefinitionQueryableParameterReader>());
I think that is a bit inconsistent with your previous review comment. Previously two line breaks were required to make 6 lines of code more readable, but in the current scenario adding line breaks to significantly more lines of code is said to make it less readable. I think the line breaks add to readability here because they categorise the service collection registrations in a way that seemed intuitive for me: by registration type.

Also I don't think optimising the code PR for diff readability is something to strive for.

2020-09-02 08:52 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ResourceGraphBuilder.cs
> +            _logger = loggerFactory?.CreateLogger<ResourceGraphBuilder>();
You're right! For a moment I thought `ILoggerFactory` wasn't always available by default, but I checked and as long as `CreateDefaultBuilder` is used in `Program.cs` it should be fine!

Will make it non optional

2020-09-02 08:53 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +        private void AutoDiscoverResources(ServiceDiscoveryFacade serviceDiscoveryFacade)
See my comment related to the other method call in this encapsulating method

2020-09-02 08:54 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ResourceGraphBuilder.cs
> +            ResourceName = publicName,
I agree. Let's just throw it in right now.

2020-09-02 09:00 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ResourceGraphBuilder.cs
> +            ResourceName = publicName,
> `ResourceName` => `publicName`

This makes sense, because its about how the resource is publicly exposed in the json:api payload.

Since this field is strongly coupled to the [json:api "type: xxxx" member](https://jsonapi.org/format/#document-resource-objects), we could even consider renaming this to `PublicType` or `ExposedType`. Thoughts?

> `ResourceType` => `PublicType` 

This makes less sense, because we don't expose the c# type information in any way to the client. Ideally we would just use `Type`, but this property name is of course unavailable. Hence I think `ResourceType` makes the most sense, because it also allows to differentiate from other `Type`ish property, like `IdType`.

2020-09-02 09:01 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ServiceCollectionExtensions.cs
> +            ILoggerFactory loggerFactory = null)
ILoggerFactory dependency is a mistake, will remove. Forgo to remove. I think the rest of your comment is directly resolved by that.

2020-09-02 09:02 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ServiceCollectionExtensions.cs
> +            Action<ResourceGraphBuilder> configureResources, IMvcCoreBuilder mvcBuilder, Type dbContextType)
Agree, will change

2020-09-02 09:04 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ServiceDiscoveryFacade.cs
> +            _logger = loggerFactory?.CreateLogger<ResourceGraphBuilder>();
See other comment. Will change

2020-09-02 09:12 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/ConvertEmptyActionResultFilter.cs
> +                    break;
Good catch! Will revert

2020-09-02 09:21 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/ConvertEmptyActionResultFilter.cs
> +                    break;
It would be good to have a test that covers that scenario

2020-09-02 09:24 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/ConvertEmptyActionResultFilter.cs
> +                    break;
I don't see how the semantics are changed? AFAIK the control flow hasn't changed, the expression of the first if is still executed before the other expression?

I preferred the readability of this syntax.

2020-09-02 09:31 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/IJsonApiTypeMatchFilter.cs
> +    /// Action filter used to verify the incoming type matches the target type, else return a 409
Will add

2020-09-02 09:32 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/JsonApiExceptionFilter.cs
> +            };
I'm not sure what you're referring to.

2020-09-02 09:33 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/IJsonApiInputFormatter.cs
> +namespace JsonApiDotNetCore.Formatters
Good catch. This is slipped through resolving the merge conflicts. Will adjust

2020-09-02 09:44 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/JsonApiOutputFormatter.cs
> +
We have discussed that it is fine to introduce changes like these when working in files, which was the case here. If you no longer agree with that we can discuss that, but reverting these changing at this stage just to declutter the PR does not make any sense to me, and I also don't think its helpful to start a review comment for this

2020-09-02 09:50 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/JsonApiRoutingConvention.cs
> +            return null;
> And please keep the code style similar to how it was.

This comment is not really helpful, especially considering that I'm the only contributor to this class. Please elaborate or leave it out. This 

> The null check was removed here, which looks wrong
Null check was removed by accident in while resolving the merge conflicts. Will put it back.

> Did you check that newly added code has proper null checks on publicly-visible methods?
At the time of writing the PR this was not a thing, and technically it still isn't without formal guidelines and explicit resharper rules to enforce them. Let's prioritise this in a next PR and get that over with once and for all.

2020-09-02 09:54 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/JsonApiTypeMatchFilter.cs
> +            if (!context.HttpContext.IsJsonApiRequest())
> Missing null check from old code

Result of resolving the merge conflict, will put it back

> so please revert to the original code from IncomingTypeMatchFilter

Not reverting: see my replies to your other comments that relate to this.

2020-09-02 10:04 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/QueryStringActionFilter.cs
> +        public void OnActionExecuting(ActionExecutingContext context)
I played around with this. Using the async filter version leads to weird behaviour: try it out and run the tests. The bug that resulted from that I managed to fix by relying on this filter being synchronous. You're right on that sync filters could pose a potential issue for scalable applications, but in the current scenario this not an issue:
- everything inside this filter is synchronous, and that code is in our internal namespace anyway
- if a dev would ever need this filter to be async, it can do so by removing the original filter and registering a custom async version. Current extensibility of the framework perfectly allows for that.

2020-09-02 10:06 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/QueryStringActionFilter.cs
> +            _queryStringReader.ReadAll(disableQueryAttribute);
Good catch! Slipped through while resolving the merge conflicts. Will remove

2020-09-02 10:07 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/QueryStringActionFilter.cs
> +            if (!context.HttpContext.IsJsonApiRequest())
💯

2020-09-02 10:07 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/IJsonApiInputFormatter.cs
> +    public interface IJsonApiInputFormatter : IInputFormatter { }
Yes: you're right. This is a merge conflict fail, see my comment on your other review item related to this. 

Is to be resolved

2020-09-02 10:11 UTC, maurei commented on src/JsonApiDotNetCore/AssemblyInfo.cs
> +[assembly:InternalsVisibleTo("ResourceEntitySeparationExampleTests")]
Good catch! Its really annoying to go through very large merge conflicts. Will restore yours and removed the redundant one:)

2020-09-02 10:13 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/DocumentTests/LinksWithoutNamespaceTests.cs
> +        public NoNamespaceStartup(IConfiguration configuration) : base(configuration) { }
Was working in the file for other reasons which is when it was changed. In general you can assume that this is the case where ever this occurs in the diff, as we agreed on only doing it in these case. Reverting it solely to enhance the diffs readability does not make sense to me, so IMO no need to make a review item for this

2020-09-02 10:14 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/Factories/ClientGeneratedIdsApplicationFactory.cs
> +                }, discovery => discovery.AddAssembly(Assembly.Load(nameof(JsonApiDotNetCoreExample))));
See my reply on your previous comment

2020-09-02 10:14 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/TestableStartup.cs
> +        public TestableStartup(IConfiguration configuration) : base(configuration) { }
See my reply on your previous comment

2020-09-02 10:14 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +                sp => sp.GetService<IResourceDefinitionQueryableParameterReader>());
I think you misunderstand what I'm saying here. I'm not saying to revert adding extra empty lines here. Instead, the diff here adds line breaks that break a single statement over multiple lines, which decreases readability.

Optimizing for diff readability is not a goal indeed, but it is a goal to not add changes that increase the diff without actually changing behavior or improving code readability.

2020-09-02 10:27 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/ResourceGraphBuilder.cs
> +            ResourceName = publicName,
`Type` is available for use, but I'm okay with keeping it like it is now, all living side-by-side:
```c#
public Type ResourceType { get; set; }
public Type IdentityType { get; set; }
public Type ResourceDefinitionType { get; set; }
```
I was wrong in assuming that `ResourceType` contains the exposed type, so my initial comment should just be about renaming ResourceName to PublicName. That the *value* is used in the types json:api field indicates usage, which is something else than what the thing itself represents: the publicly exposed name of the resource type. Since ResourceContext is always about types (instead of instances), I think PublicName fits best here. So I think we should just rename ResourceContext.ResourceName to ResourceContext.PublicName. This aligns nicely with other places like AttrAttribute and ResourceAttribute.

2020-09-02 10:36 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/ConvertEmptyActionResultFilter.cs
> +                    break;
First of all, there's no test coverage that proves this. It would require different objects that only implement interfaces, other objects that derive from base classes and intersections between those. That's a lot of test code I don't think is worth it. Second, while the current compiler implementation evaluates the switch clauses in the written order, that may change over time. But more importantly: switch is used to indicate 'pick one of these' making the cases independent from each other. And refactoring tools provide options to re-order cases based on that assumption. Like I said before, that is not the case here, so writing it as a switch is misleading and therefore it should be reverted.

The second reason to revert this is because changing this adds no value. You are making various stylistic changes throughout this PR that moves us away from the goal this PR is trying to solve and you should not do that. If you believe style changes are needed, create a PR to address those separately.

2020-09-02 11:03 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/JsonApiRoutingConvention.cs
> +            return null;
Proper null checks affect runtime behavior, which we must get right before v4 release, or they will be breaking changes otherwise. That's why I've gone over all of them recently as part of public API review. Resharper cannot enforce these, it is a manual effort. Code style is unrelated to that and can be deferred to a later time.

2020-09-02 13:50 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ApplicationBuilderExtensions.cs
> +            };
OK, will adjust

2020-09-02 13:52 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +        /// Configures and build the resource graph with resources from the provided sources and adds it to the DI container.
Good call

2020-09-02 14:15 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +            UserConfigureResources(configureResources, _resourceGraphBuilder);
I don't think it is ambiguous as there is only one type of 'user' conceptually that can interact with the resource graph configuration, which is the developer that uses the framework, so I don't see how this adds confusion. In my opinion it is more insightful than an `Invoke` method call on an `Action<T>` parameter, especially weighing in  the docs that live on the discussed method. I've changed the method name to `ExecuteManualConfigurationOfResources`, does this clear up the ambiguity you experienced?

2020-09-02 14:28 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +}
Thinking about this further, if you agree on just focussing on the few lines on interest rather than having a verbose example, I could change the example to not be syntactically incorrect by changing in into:

```c#
# In Startup.Configure
var builder = services.AddMvcCore();
services.AddJsonApi<AppDbContext>(mvcBuilder: builder);
mvcCoreBuilder.AddMvcOptions( mvcOptions =>
{
    // execute the mvc configuration callback after the JsonApiDotNetCore callback as been executed.
    _postConfigureMvcOptions?.Invoke(mvcOptions);
});

# In Startup.Configure

// Using a callback, we can defer to later (when service collection has become available).
_postConfigureMvcOptions = mvcOptions =>
{
    mvcOptions.Filters.Clear();
    mvcOptions.Filters.Insert(0, app.ApplicationServices.GetService<CustomFilter>());
};
```

Let me know if you think this is an improvement

2020-09-02 17:18 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +}
>  The goal of these examples is not to provide the developer with a minimally working example that works off-the-shelve.

I'm not saying that. Providing a code sample that actually works does not mean providing an entire sample application. It means to ensure it has no obvious compile errors or references that do not exist because you missed something during copy/paste. Your new sample is more or less what I had in mind. But even that one contains compile errors: you declare `builder`, then later act as if `mvcCoreBuilder` exists. This is misleading. Pasting your sample in an actual IDE reveals that right away and that is my point. Similarly, to indicate a place where additional code is left out, write `// ...` instead of `...`. It's just simple things like that I'm referring to. But I got a compliment recently from a community member that was happy I changed the samples into working code without fancy constructs, it made the difference between understanding and not.

To comment on your sample, I think it is fine like that, except that `app.UseJsonApi()` must be called *after* setting `_postConfigureMvcOptions` otherwise it will not work. So adding that call at the end helps. Finally, single whitespace after `AddMvcOptions(`.

2020-09-02 17:39 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +}
And it looks like the first comment needs to be ConfigureServices instead.

2020-09-03 07:20 UTC, bart-degreed commented on test/DiscoveryTests/ServiceDiscoveryFacadeTests.cs
> +            ServiceDiscoveryFacade facade = new ServiceDiscoveryFacade(_services, _resourceGraphBuilder, new NullLoggerFactory());
Use `NullLoggerFactory.Instance`

2020-09-03 07:20 UTC, bart-degreed commented on test/DiscoveryTests/ServiceDiscoveryFacadeTests.cs
> +            ServiceDiscoveryFacade facade = new ServiceDiscoveryFacade(_services, _resourceGraphBuilder, new NullLoggerFactory());
Use `NullLoggerFactory.Instance`

2020-09-03 09:27 UTC, bart-degreed requested changes

2020-09-03 09:27 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/ServiceCollectionExtensions.cs
> +            applicationBuilder.Dispose();
This only runs when no exceptions are thrown, making it leak when that happens. Use a `using` statement instead.

2020-09-03 09:27 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +            _intermediateProvider?.Dispose();
This null check looks wrong. The instance is created in ctor, so it is never null.

2020-09-03 09:27 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/ServiceDiscoveryFacade.cs
> +            _logger = loggerFactory.CreateLogger<ResourceGraphBuilder>();
You still didn't fix this creates the wrong logger.

2020-09-03 10:23 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ResourceGraphBuilder.cs
> +    public class ResourceGraphBuilder
I already did that for both, as requested. Look carefully: the comments are not old but improved/new. For `ServiceDiscoveryFacade` the method summaries were no longer accurate for what the methods actually did because I changed the discovery flow. And in the case of `ResourceGraphBuilder`,  the same comments were copy-pasted to the various `Add` overloads. I changed that to a reference to the main overload for which the comments now is the single source of truth. Also there weren't any comments on the `IResourceGraphBuilder` interface itself. I will add them in the next push

2020-09-03 10:57 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ResourceGraphBuilder.cs
> +    public class ResourceGraphBuilder
I did all of that, and the comments were not old but new. For `ResourceGraphbuilder` I decided to not have copy-pasted lines of comments but do a XML reference to the docs of the main overload from the over overloads. I'll undo it so we can proceed. There weren't any comments on the `IResourceGraphBuilder` interface itself, will add them in the next push. For `ServiceDiscoveryFacade` I changed the comments because the method descriptions were no longer accurate after I changed the discovery flow in this PR.

2020-09-03 11:18 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ResourceGraphBuilder.cs
> +            ResourceName = publicName,
Will adjust

2020-09-04 18:41 UTC, bart-degreed commented on docs/usage/options.md
> +
This is already described in resources\attributes.md, so I would leave it out.
At first I thought options.md was the place where all options are explained, but it turns out that various other docs mention options that affect the scenario covered. And options.md just contains the remaining subset of options that weren't covered elsewhere. From a usage perspective, I agree with that approach as users go to a page to accomplish something (and need to know about options relating to that topic), they are generally not just looking for all ways to configure everything.

2020-09-04 18:41 UTC, bart-degreed commented on docs/usage/routing.md
> +```
Thanks for simplifying, this is a lot better. I'm comparing the new version with the version before this PR now. And it looks to me this is rewording what was already there, but in a more complicated way. So instead of rewriting the whole doc, I'd like to explore the opposite direction. What is the essential information that is missing in the original version that requires to be added? I don't see any, except for using a custom routing convention, but then you're recommending to not do that, so I'd leave it out in that case.

2020-09-04 19:03 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +}
You put the call to `app.UseJsonApi()` in the wrong place. And didn't fix the white space.

2020-09-04 19:04 UTC, bart-degreed requested changes
See comments. I've resolved the fixed items. What's still open is not yet addressed,

2020-09-04 19:11 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +            UserConfigureResources(configureResources, _resourceGraphBuilder);
ExecuteManualConfigurationOfResources doesn't help me either. Manual as in "not automated"? What happens is invoke a callback that was passed in externally. That is what the code does and that is also the intent, so invoking the callback is clearer than having to step into a method just to understand that the callback is being invoked.

2020-09-08 09:50 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +```
> We should just indicate what developers need to do to use our middleware, simple like it was before.
This should be in the getting started document (it is already there), not the current document which is about middleware extensibility. But you're right that the examples don't relate to the extensibility of JADNC, but just the configurability of ASP.NET Core. Hence I think it makes most sense to just leave this part out.

2020-09-08 10:14 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +The following example demonstrates this by clearing all internal filters and registering a custom one.
Whole doc has been simplified

2020-09-08 10:14 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +Alternatively, you can add additional middleware components by configuring `MvcOptions` directly.
👍

2020-09-08 10:14 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +var builder = services.AddMvcCore();
👍

2020-09-08 10:30 UTC, maurei commented on docs/usage/options.md
> +
I agree that having that example in two places is undesired. However from the `resources\attributes.md` part it is not clear that this bit of configuration also affects the routes that are being constructed, while that document is not the place where routing-related documentation should be put (and conversely attribute naming information shouldn't be in the routing doc). So I think it makes most sense to reference this configurability in `options.md` from `attributes.md`. It's currently like this too from the `routing.md` doc.

2020-09-08 11:04 UTC, maurei commented on docs/usage/resource-graph.md
> +is prioritized by the order of the list above.
I agree

2020-09-08 11:51 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +}
I'm unsure if you were referring to the most recent version at the time, but the [in the doc](https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/805/files#diff-387be4618777557b1031ea8be1c39be5R38) at the time of your reply the `UseJsonApi()` call is in the right place

2020-09-08 11:56 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/JsonApiApplicationBuilder.cs
> +            _intermediateProvider?.Dispose();
Will fix

2020-09-08 12:00 UTC, maurei commented on test/DiscoveryTests/ServiceDiscoveryFacadeTests.cs
> +            facade.DiscoverResources();
Thats incorrect. The user first explicitly calls `AddCurrentAssembly` in the `discoverResources` callback, and then indirectly is responsible for the `DiscoverResources` call which occurs through the `AddJsonApi()` call.

2020-09-08 12:12 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +builder.AddMvcOptions( mvcOptions =>
Why do you want a line break here?

2020-09-08 12:13 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +var builder = services.AddMvcCore();
Will add

2020-09-09 11:23 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +}
The next order is still wrong:
```c#
/// In Startup.Configure
app.UseJsonApi();

// Ensure the configuration callback is set after calling `UseJsonApi()`.
_postConfigureMvcOptions = mvcOptions => 
{ 
    mvcOptions.Filters.Clear();
    mvcOptions.Filters.Insert(0, app.ApplicationServices.GetService<CustomFilter>());
};
```

`app.UseJsonApi();` must be placed *after* setting the callback. By showing the right way, the comment telling the order can be removed.

2020-09-09 11:25 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +}
And there is no "IJsonApiGlobalExceptionFilter" interface, it should be "IAsyncJsonApiExceptionFilter" instead.

2020-09-09 11:27 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +}
We should remove the phrase "To prevent the library from overwriting your configuration, perform your configuration *after* the library is done configuring `MvcOptions`. ", I find it confusing ("your configuration?"). The remainder of that line should be good enough.

2020-09-09 11:28 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +}
I'd also remove the comment "// Ensure the configuration action is registered after the `AddJsonApi()` call.", the example already shows that.

2020-09-09 11:30 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +}
We should rename "CustomFilter" to something more concrete, for example: CustomAsyncQueryStringActionFilter

2020-09-09 11:31 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +}
An empty line after `services.AddSingleton<CustomFilter>();` increases readability.

2020-09-09 11:34 UTC, bart-degreed commented on docs/usage/resources/attributes.md
> +1. By convention, specified by configuring the [naming strategy](./options.md#custom-serializer-settings).
```
By convention, specified by configuring the [naming strategy](./options.md#custom-serializer-settings).
```

better:

```
Using the configured [casing convention](./options.md#custom-serializer-settings).
```

Although this is accomplished by setting a naming strategy object, that is just implementation detail and subject to change.

2020-09-09 11:39 UTC, bart-degreed commented on docs/usage/resource-graph.md
> +3. The configured naming convention (by default this is camel-case).
casing convention instead of naming convention

2020-09-09 11:39 UTC, bart-degreed commented on docs/usage/resource-graph.md
> +This convention can be changed by setting the `SerializerSettings.ContractResolver` property on `IJsonApiOptions`. See the [options documentation](./options.md#custom-serializer-settings).
```
This convention can be changed by setting the `SerializerSettings.ContractResolver` property on `IJsonApiOptions`. See the [options documentation](./options.md#custom-serializer-settings).
```

better:
```
The default casing convention can be changed in [options](./options.md#custom-serializer-settings).
```

2020-09-09 11:46 UTC, bart-degreed commented on test/DiscoveryTests/ServiceDiscoveryFacadeTests.cs
> +            facade.DiscoverResources();
The rule is to put "act" on the statement that activates the behavior, not the one(s) setting it up. In this case, that would be `facade.DiscoverResources();`, because that is the operation being tested and asserted on. And then the test should be named "DiscoverResources_Adds_Resources_From_Current_Assembly_To_Graph"

2020-09-09 11:49 UTC, bart-degreed commented on docs/usage/options.md
> +
Yes, I agree to keep this in and pointing to there would be best.

2020-09-09 11:52 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +The following example demonstrates this by clearing all internal filters and registering a custom one.
You replaced it with:
```
To prevent the library from overwriting your configuration, perform your configuration *after* the library is done configuring `MvcOptions`. The following example replaces all internal filters with a custom filter.
```
I'm losing track a bit, but this is not what I asked for. See my other remark on this file.

2020-09-09 11:53 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +var builder = services.AddMvcCore();
It is still missing. Line break should be added between service registration and builder instantiation.

2020-09-09 11:54 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +builder.AddMvcOptions( mvcOptions =>
Because it makes the comment stand out. But I think I mentioned elsewhere to take out the comment, making this remark obsolete.

2020-09-09 13:49 UTC, maurei commented on test/DiscoveryTests/ServiceDiscoveryFacadeTests.cs
> +            facade.DiscoverResources();
OK, it makes sense to look at it like this

2020-09-09 14:27 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +var builder = services.AddMvcCore();
Whoops, I realised I asked for clarification in the wrong review item. I meant to ask for it here but mentioned that I added it, while in the next review item I added it but asked for clarification.

I'm assuming you're requesting it  improve readability. To me it doesn't really make a difference in a code block consisting of three lines. I added it here too regardless

2020-09-09 14:27 UTC, maurei commented on docs/usage/resources/attributes.md
> +1. By convention, specified by configuring the [naming strategy](./options.md#custom-serializer-settings).
Modified

2020-09-09 14:28 UTC, maurei commented on docs/usage/resource-graph.md
> +3. The configured naming convention (by default this is camel-case).
Modified

2020-09-10 08:51 UTC, maurei commented on docs/usage/resource-graph.md
> +This convention can be changed by setting the `SerializerSettings.ContractResolver` property on `IJsonApiOptions`. See the [options documentation](./options.md#custom-serializer-settings).
Updated

2020-09-10 09:00 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +}
Modified

2020-09-10 09:53 UTC, bart-degreed commented on docs/usage/extensibility/middleware.md
> +}
We need to verify when exactly the callback gets executed.

2020-09-10 10:14 UTC, maurei commented on docs/usage/extensibility/middleware.md
> +}
Updated example accordingly

2020-09-10 12:55 UTC, bart-degreed approved these changes

2020-09-10 12:56 UTC, merged