Fix: incorrect resource type comparison
json-api-dotnet/JsonApiDotNetCore pull request #821
Opened 2020-09-09 15:09 UTC by maurei

Fixes #789

2020-09-10 12:59 UTC, bart-degreed commented
@maurei Can you resolve merge conflicts?

2020-09-11 18:47 UTC, bart-degreed requested changes
Nice, Looks great!

2020-09-11 18:47 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +            _resourceContextProvider = resourceContextProvider;
Missing null check

2020-09-11 18:47 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +                : _jsonApiRequest.SecondaryResource?.ResourceType;
I'm not 100% sure if there are cases where this can fail, but I think using secondary with fallback to primary is more robust. So without checking `Kind` first. Because `Kind != Primary` does not always mean `Kind.Secondary`, it could mean `Kind.Relationship` too.

2020-09-11 18:47 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +            _jsonApiRequest = jsonApiRequest ?? throw new ArgumentNullException(nameof(jsonApiRequest));
I did a solution-wide refactoring in #808 to rename all parameters and fields of type `IJsonApiRequest` from `jsonApiRequest` to `request` (and the same for options) and would like to keep it that way.

2020-09-11 18:47 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +                var endPointResourceType = GetEndpointResourceType();
`endPointResourceType` should have lowercase 'p' (same as in method name)

2020-09-11 18:47 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +                    if (bodyResourceType != null && endPointResourceType != null && bodyResourceType != endPointResourceType)
I don't think `bodyResourceType` can ever be null, so comparing both without the null checks should be fine. If not, entering the loop only when `endPointResourceType != null` (check upfront) seems more appropriate, as the condition never changes when iterating through the loop.

2020-09-14 15:03 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +            _resourceContextProvider = resourceContextProvider;
Good catch, will add

2020-09-14 15:03 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +            _jsonApiRequest = jsonApiRequest ?? throw new ArgumentNullException(nameof(jsonApiRequest));
Good catch, will modify

2020-09-14 15:03 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +                var endPointResourceType = GetEndpointResourceType();
Good catch, will modify

2020-09-14 15:11 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +                    if (bodyResourceType != null && endPointResourceType != null && bodyResourceType != endPointResourceType)
Your right! the `bodyResourceType` null check is redundant because when the resource type from the body resolves to `null`, this is already caught [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/f27e020418c5f08762f57a85f221f3aa698019b8/src/JsonApiDotNetCore/Serialization/JsonApiReader.cs#L182).

Will process both suggestions

2020-09-14 15:29 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +                : _jsonApiRequest.SecondaryResource?.ResourceType;
At this stage `Kind` can only be `Relationship` or `Primary, because there can be no json:api POST or PATCH request on a secondary endpoint. `POST /todoItems/1/assignee` is not supported

A fallback on the primary resource when the secondary resource is `null` will also not suffice, because it is possible to have a request on a `Kind.Relationship` endpoint with an unknown relationship, in which case the `null` is actually desired and should not lead to a fallback to the primary resource. See [Fails_On_Unknown_Relationship](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/f27e020418c5f08762f57a85f221f3aa698019b8/test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/UpdatingRelationshipsTests.cs#L774).

2020-09-15 08:52 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +                : _jsonApiRequest.SecondaryResource?.ResourceType;
Good points! So this already was the best approach after all, let's leave it like that.

2020-09-15 09:01 UTC, bart-degreed requested changes
Looking good, one more small change.

2020-09-15 09:01 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +            if (model is ICollection<IIdentifiable> resourceCollection)
This can be `IEnumerable<T>` now.

2020-09-15 10:32 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/JsonApiReader.cs
> +            if (model is ICollection<IIdentifiable> resourceCollection)
Fixed!

2020-09-15 10:50 UTC, bart-degreed approved these changes

2020-09-15 10:50 UTC, merged