Break up AttrCapabilities.AllowChange
json-api-dotnet/JsonApiDotNetCore pull request #826
Opened 2020-09-14 12:46 UTC by bart-degreed

Before, `AttrCapabilities.AllowChange` was used for both POST and PATCH requests (although documentation said it was only for PATCH).

This commit adds a new flag and changes the meaning of the old one:
- AttrCapabilities.AllowCreate affects only POST
- AttrCapabilities.AllowChange affects only PATCH

Fixes #801.

2020-09-16 13:46 UTC, maurei requested changes

2020-09-16 13:46 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/CreatingDataTests.cs
> +        public async Task CreateResource_Blocked_Fails()
We can be more explicit on how it fails: 422

2020-09-16 13:46 UTC, maurei commented on docs/usage/resources/attributes.md
> +### Createability
[I think it should be creatability](https://english.stackexchange.com/questions/400406/create-createable-update-updateable-delete-deletable), as spelled on the next line

2020-09-17 08:29 UTC, bart-degreed commented on docs/usage/resources/attributes.md
> +### Createability
Wow, that surprises me! When I wasn't sure about the right spelling, I looked it up and found changeability. And then I assumed the same would apply to creation. Turns out it does not, so I will adapt.

2020-09-17 08:31 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/CreatingDataTests.cs
> +        public async Task CreateResource_Blocked_Fails()
I considered adding that, which means breaking with the style of existing tests in this file. Then I decided to not add it, knowing we're going to give all tests a bit overhaul in the future. Are you okay with leaving it like this for now?

2020-09-17 09:41 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/CreatingDataTests.cs
> +        public async Task CreateResource_Blocked_Fails()
Makes sense! Agreed.

2020-09-17 09:41 UTC, maurei approved these changes

2020-09-17 09:41 UTC, merged