Generic resource definitions
json-api-dotnet/JsonApiDotNetCore pull request #832
Opened 2020-09-16 15:58 UTC by bart-degreed

Fixes #806.

Made resource definitions a first-class pluggable extensibility point, similar to resource services and repositories. So developers now can derive from `JsonApiResourceDefinition`, implement `IResourceDefinition`, or insert base classes in the type hierarchy to share common logic. Such a base class can then be registered as an open generic, so that all resources will use that (unless the container finds a non-generic class, which is a better match) instead of the built-in `JsonApiResourceDefinition`.

To accomplish this, I had to split up `ResourceDefinition` into two:
- `JsonApiResourceDefinition` is highly pluggable like described above
- `ResourceHooksDefinition` contains just the hook callbacks

This way, the recursive resolve logic for resource hooks remains as-is. Since it did not use `IResourceDefinitionProvider`, that type has been replaced with `IResourceDefinitionAccessor`, which invokes the requested callbacks directly on the found class. What used to be `IResourceDefinition` (an internal type to invoke callbacks on) no longer exists.

Additionally replaced `IHasMeta` with a method on `IResourceDefinition` and only scan for hook definitions when they are enabled. I intend to update documentation on `IHasMeta` (which was already wrong) later, as part of #737 (which may change these again).

2020-09-17 10:12 UTC, maurei requested changes
Partial review, will continue later today

2020-09-17 10:12 UTC, maurei commented on src/JsonApiDotNetCore/Configuration/ServiceDiscoveryFacade.cs
> +        internal void DiscoverInjectables(bool enableResourceHooks)
Alternatively we could pass `IJsonApiOptions` to the constructor of `ServiceDiscoveryFacade` and read the option from there. That feels a little bit cleaner to me. Thought?

2020-09-17 11:36 UTC, bart-degreed commented on src/JsonApiDotNetCore/Configuration/ServiceDiscoveryFacade.cs
> +        internal void DiscoverInjectables(bool enableResourceHooks)
Sounds good, I've change it.

2020-09-17 14:26 UTC, maurei approved these changes

2020-09-18 08:54 UTC, maurei requested changes

2020-09-18 08:54 UTC, maurei commented on docs/usage/meta.md
> +Top-level custom metadata can be added to your API responses in two ways: globally and per resource type. In the event of a key collision, the resource meta will take precendence.
I think the word "custom" is redundant here

2020-09-18 08:54 UTC, maurei commented on docs/usage/meta.md
> +Global metadata can be added by injecting a service that implements `IResponseMeta`.
Is injecting the right terminology here? I usually refer to _injecting_ as adding a service to a constructors signature. Did you mean _registering_?

2020-09-18 08:54 UTC, maurei commented on docs/usage/meta.md
> +This is useful if you need access to other injected services to build the meta object.
_registered_ services

2020-09-18 12:01 UTC, bart-degreed commented on docs/usage/meta.md
> +Top-level custom metadata can be added to your API responses in two ways: globally and per resource type. In the event of a key collision, the resource meta will take precendence.
It is, thanks.

2020-09-18 12:01 UTC, bart-degreed commented on docs/usage/meta.md
> +Global metadata can be added by injecting a service that implements `IResponseMeta`.
Agreed.

2020-09-18 12:01 UTC, bart-degreed commented on docs/usage/meta.md
> +This is useful if you need access to other injected services to build the meta object.
Agreed.

2020-09-18 12:09 UTC, maurei approved these changes

2020-09-18 12:10 UTC, merged