Fix/696
json-api-dotnet/JsonApiDotNetCore pull request #833
Opened 2020-09-18 15:36 UTC by maurei

draft

2020-09-21 10:39 UTC, bart-degreed requested changes

2020-09-21 10:39 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/BaseDeserializer.cs
> +            var relatedResourceType = relationshipData.SingleData == null
I find this name confusing: related to what? It seems to hold a `System.Type` (not the public type name, as in "articles"), so I think `relationshipType` would be a better fit.

2020-09-21 10:39 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/BaseDeserializer.cs
> +        private void SetForeignKey(IIdentifiable resource, PropertyInfo foreignKey, HasOneAttribute attr, string id,
The comment above this line reads "foreign key also will to be populated". It is not part of the diff, but while you're at it, could you please correct this sentence as well?

2020-09-21 10:39 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/BaseDeserializer.cs
> +            SetNavigation(resource, attr, relatedId, relatedResourceType);
In this file, I would have expected similar changes in `SetHasManyRelationship`, which also calls `CreateInstance`. I marked that as a TODO in the closed PR. Is this an oversight?

2020-09-21 10:39 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Controllers.cs
> +    public sealed class MalesController : JsonApiController<Male>
Please put these in separate files, to make it easier to find them.

2020-09-21 10:39 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models.cs
> +    public sealed class Male : Person
Same here, please put them in separate files.

2020-09-21 10:39 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models.cs
> +        public int? OneToOnePersonId { get; set; }
I think this property can be removed. ID properties are only needed for join relationships (many-to-many via HasManyThrough).

2020-09-21 10:39 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models.cs
> +        public List<Person> OneToManyPersons { get; set; }
I'd prefer to switch to a more humanly understandable model. For example, Ferrari and Lamborghini inherit from Car, or Cat and Dog which are both Animals.

2020-09-21 10:39 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +        public async Task Can_create_resource_with_one_to_one_relationship_that_has_inheritance(string type, int index)
I think we should plan a meeting and decide on test naming. Here, I'd prefer the `When_[scenario]_it_should_[expected-outcome]` pattern.

2020-09-21 10:39 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +        [InlineData("females", 1)]
This looks like testing the same thing twice to me. Assuming the scenario is to show a base class with a derived type works.

2020-09-21 10:39 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +
Please remove this extra empty line.

2020-09-21 10:43 UTC, bart-degreed commented
I would have expected changes in `ResponseDeserializer.ParseIncludedRelationship` too, they were marked as a place we need to update.

2020-09-24 08:16 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Controllers.cs
> +    public sealed class MalesController : JsonApiController<Male>
In my opinion it only makes it harder to find them because controllers, models and test files are all mixed up in one folder. I'll separate them over different files but then will put them in children folders instead.

2020-09-24 08:44 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models.cs
> +        public List<Person> OneToManyPersons { get; set; }
This wasn't so easy to come up with. I tried to eg. elaborate on the teacher/student/article example from [the repro repository](https://github.com/bart-degreed/DeserializeIssue/tree/upgrade-netcore31-jadnc4beta1). It has an intuitive one-to-many relationship. But when trying to expand t with a one-to-one and many-to-many relationship that are all conceptually different and still intuitive, I kept ending up having weird relationships in examples that no longer fully made sense. Having only partially intuitive examples, I prefer having an abstract one. If you have a fully intuitive examples with the three relationships and using inheritance, I would be happy to include it

2020-09-24 10:08 UTC, maurei commented on src/Examples/JsonApiDotNetCoreExample/Controllers/KebabCasedModelsController.cs
> +        { }
👍

2020-09-24 10:13 UTC, maurei commented on src/JsonApiDotNetCore/Repositories/EntityFrameworkCoreRepository.cs
> +                return Convert.ChangeType(tracked ?? pointer, (tracked ?? pointer).GetType());
👍

2020-09-24 10:24 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/BaseDeserializer.cs
> +            var relatedResourceType = relationshipData.SingleData == null
To me `relationshipType` is unclear because a "relationship" refers to the coupling between two resources, eg _person_ has many articles_. But what we're after here is the _resource type_ of the RHS of the relationship, which is embedded in but not the same as `relationshipType`

2020-09-24 10:25 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/BaseDeserializer.cs
> +            SetNavigation(resource, attr, relatedId, relatedResourceType);
I think you missed the changes on lines 242-243 of this file

2020-09-24 10:26 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/BaseDeserializer.cs
> +        private void SetForeignKey(IIdentifiable resource, PropertyInfo foreignKey, HasOneAttribute attr, string id,
👍

2020-09-24 10:28 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/BaseDeserializer.cs
> +            var relatedResourceType = relationshipData.SingleData == null
But I see now I've been inconsistent in this variable naming, I've used `relationshipType` elsewhere. I'm going to update it to `relationshipType`

2020-09-24 10:28 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models.cs
> +        public int? OneToOnePersonId { get; set; }
👍

2020-09-24 11:19 UTC, maurei commented on src/JsonApiDotNetCore/Repositories/EntityFrameworkCoreRepository.cs
> +                // we should recalculate the target type for every iteration because types may vary. This is possible with resource inheritance
👍

2020-09-28 12:13 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +        [InlineData("females", 1)]
We discussed this privately. Refactored tests

2020-09-28 12:14 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +        public async Task Can_create_resource_with_one_to_one_relationship_that_has_inheritance(string type, int index)
I've refactored the tests significantly and decided to stick with the `Can_....` format. Let me know if you still think the `When...` pattern in the current form of the tests

2020-09-28 12:14 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models.cs
> +        public List<Person> OneToManyPersons { get; set; }
We discussed this in private. Tests have been refactored.

2020-09-28 12:14 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models.cs
> +        public int? OneToOnePersonId { get; set; }
Removed it

2020-09-28 14:19 UTC, maurei commented
> I would have expected changes in `ResponseDeserializer.ParseIncludedRelationship` too, it was marked as a place that needs to be updated in #828.

Thanks for the heads up. Has been addressed now too.

2020-09-29 08:11 UTC, bart-degreed requested changes
Will look at tests later.

2020-09-29 09:08 UTC, maurei commented on src/JsonApiDotNetCore/Serialization/Client/Internal/ResponseDeserializer.cs
> +            SetAttributes(relatedInstance, includedResource.Attributes, relatedResourceContext.Attributes);
Good catch!

2020-09-29 09:19 UTC, maurei commented on src/JsonApiDotNetCore/Resources/ResourceFactory.cs
> +                throw new InvalidOperationException($"No public constructors found for '{type.FullName}'.");
👍

2020-09-29 13:25 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +
Removed

2020-10-01 16:37 UTC, bart-degreed requested changes

2020-10-01 16:37 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +            var cat = new Cat();
Did you mean `var man`?

2020-10-01 16:37 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.AddRangeAsync(person, cat);
I'm not sure what's better. Calling `dbContext.AddRange()` enables passing different entity types is a single call. That's short to write, be at the cost of losing static typing (you can pass anything, such as `DateTime`). That's basically trading compile-time errors for run-time errors. I think I prefer using the typed members, such as `dbContext.Animals.AddRange()`, which better reveals intent (and is more efficient in theory, but likely not measurable).

2020-10-01 16:37 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                    .Where(p => p.Id.Equals(int.Parse(responseDocument.SingleData.Id))).FirstAsync();
In general, calling `something.Equals` should be avoided when `operator==` is implemented. It is more readable, but more importantly does not throw when `something` is `null`.

2020-10-01 16:37 UTC, bart-degreed commented on test/UnitTests/Serialization/SerializationTestsSetupBase.cs
> +using InheritancePerson = JsonApiDotNetCoreExampleTests.IntegrationTests.ResourceInheritance.Person;
I find it very confusing that we have two incompatible definitions of Person *and* that we need both of them in the same file. Better would be to rename ResourceInheritance.Person to Human so they are really distinct.

2020-10-01 16:37 UTC, bart-degreed commented on test/UnitTests/UnitTests.csproj
> +    <ProjectReference Include="..\JsonApiDotNetCoreExampleTests\JsonApiDotNetCoreExampleTests.csproj" />
I think this dependency is wrong. Unit-tests should not depend on types defined in another test project. It is only a matter of time before we need circular dependencies if we go down that path.

2020-10-01 16:37 UTC, bart-degreed commented on test/UnitTests/Serialization/Client/ResponseDeserializerTests.cs
> +            var result = _deserializer.DeserializeSingle<Male>(body);
This verifies deserialize behavior, but what if `DeserializeSingle` is called with `<Person>`? My point is that this does not prove much. So I'd prefer to have an integration test instead, with has an assertion on the json text output (see `Registered_IResponseMeta_Adds_TopLevel_Meta` for example).

For background why I believe we should have mostly integration tests, see https://kentcdodds.com/blog/write-tests and https://tyrrrz.me/blog/unit-testing-is-overrated.

2020-10-01 16:38 UTC, bart-degreed requested changes

2020-10-01 16:38 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/DocumentTests/LinksWithoutNamespaceTests.cs
> +            var blog = new Blog();
Why replace Person with Blog here? Does it have to do with namespace clashes?

2020-10-01 18:20 UTC, RichardsonWTR commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Animal.cs
> +    }
What about Animal/Dog/Bird? 
Easy to understand and realistic at the same time

2020-10-02 07:42 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Content.cs
> +namespace JsonApiDotNetCoreExampleTests.IntegrationTests.ResourceInheritance
Will fix

2020-10-02 07:42 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Content.cs
> +}
I agree on `ContentItem` vs `Content`.

I don't agree that adding extra properties is useful. I think the goal is to make example cases in the tests more intuitive by choosing a set of models that have an understandable inheritance structure rather than having classes like `BaseResource`, `DerivedResource1`, `DerivedResource2`. For this purpose having `ContentItem`, `Video`, and `Book` is sufficient. Only relationship properties are assigned in the tests, not attribute properties, so I don't think adding any unused attribute properties will be of any value or make the tests anymore intuitive. It only adds unused clutter.

2020-10-02 07:42 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/ContentPerson.cs
> +    public sealed class ContentPerson
I don't think so.  It is customary to name a jointable entity like this, see [EF cores standard example](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#many-to-many). It also doesn't make sense to name it `PersonFavoriteContentItem` because this type could be reused for other many-to-many relationships between `ContentItem` and `Person`.

2020-10-02 07:46 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Animal.cs
> +    }
I'd prefer something that developers actually do model, I've never seen the need to model animals in applications. More realistic, for example, would be BankAccount { Amount } that can be a CheckingAccount { AtmWithdrawalLimit} or SavingsAccount { InterestRate }.

2020-10-02 07:48 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Animal.cs
> +    }
I think what is required for intuitive understanding when reading the tests is an intuitive inheritance structure. `Animal` with derived types `Cat` and `Dog` suffice for that. Properties are not important because relationship assignment the only thing that happens in the test, so I think we could even just remove the properties. Either way, coming up with a different set with models with other properties won't make the test examples any more intuitive, and I don't think a change here is necessary.

2020-10-02 07:48 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +            _testContext;
I don't think `Inheritance` quite covers it. Inheritance of what? It could be anything.

2020-10-02 07:52 UTC, maurei commented on test/UnitTests/UnitTests.csproj
> +    <ProjectReference Include="..\JsonApiDotNetCoreExampleTests\JsonApiDotNetCoreExampleTests.csproj" />
The alternative would be to copy paste the models to the unit test project, I don't like that. It would be solving for something that is currently not even an issue (circular dependencies). If it would ever hit us, we can choose to create a separate class project for our test models.

2020-10-02 07:52 UTC, maurei commented on test/UnitTests/Serialization/SerializationTestsSetupBase.cs
> +using InheritancePerson = JsonApiDotNetCoreExampleTests.IntegrationTests.ResourceInheritance.Person;
I agree, will improve

2020-10-02 07:52 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +            var cat = new Cat();
Yep

2020-10-02 07:53 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Content.cs
> +namespace JsonApiDotNetCoreExampleTests.IntegrationTests.ResourceInheritance
Will change to `JsonApiDotNetCoreExampleTests.IntegrationTests.ResourceInheritance.Models`

2020-10-02 08:02 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.ClearTableAsync<Male>();
> Effectively the tables are purged before the first test executes
This is not true, it is executed before every test in the encapsulating test. 

So it is just a clean up that executes before every test, which is desired. Putting it in the constructor prevents code duplication, which is not a bad practise.

2020-10-02 08:03 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.AddAsync(cat);
Will adjust

2020-10-02 08:04 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                    .Where(p => p.Id.Equals(int.Parse(responseDocument.SingleData.Id))).FirstAsync();
Will change

2020-10-02 08:07 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +            var cat = new Cat();
No. It's not about the `person`, its about the `cat` being assigned. Could have been a `Female` as well. It could be changed to `man` or `male` but I don't think it makes much of a difference and I don't think it requires a change.

2020-10-02 08:13 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                assertPerson.Pet.GetType().Should().Be(cat.GetType());
Will add

2020-10-02 08:13 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +        }
Will add

2020-10-02 08:15 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.AddRangeAsync(person, cat);
I agree that it in general it is more safe to just the strongly typed version. However this overload also allows for more brevity, which is nice when trying to create readable tests. Safety risks or unclear intent or are not much of a concern here because the method call and the associated model declarations are very closely together.

2020-10-02 08:20 UTC, maurei commented on test/UnitTests/Serialization/Client/ResponseDeserializerTests.cs
> +            var result = _deserializer.DeserializeSingle<Male>(body);
Calling `DeserializeSingle<Person>(body)` is not possible because the type parameter must be a reference type. 

It would be different if this method call is stuffed away in other code (eg a client library) which calls this method reflectively and which could break at runtime if `Person` was supplied. In this scenario a integration would be useful, but there currently is no encapsulating code like that.

2020-10-02 08:20 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.ClearTableAsync<Male>();
Are you sure? https://xunit.net/docs/shared-context

2020-10-02 08:26 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +            var cat = new Cat();
My point exactly: this test is about the cat. So declaring a male, named person, leads to believe something related to inheritance for person/man is going on (but it is not relevant at all), distracting from the purpose of this test.

Thinking about this: wouldn't it be more correct to have Man and Woman instead of Male and Female?

2020-10-02 08:26 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/DocumentTests/LinksWithoutNamespaceTests.cs
> +            var blog = new Blog();
There tests that failed in the example test project because these tests added the example project assembly ([like this here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/10dd16a00f1b28bb96a495a710c114e48dea5507/test/JsonApiDotNetCoreExampleTests/Acceptance/KebabCaseFormatterTests.cs#L38) and my PR introduces a `PeopleController` in the example project. This leads to the routing convention throwing an error because tries to register the same route twice. `Blog` rather than `Person` can be used equally well for `LinksWithoutNamespaceTests` while it fixes this problem.

2020-10-02 08:29 UTC, bart-degreed commented on test/UnitTests/Serialization/Client/ResponseDeserializerTests.cs
> +            var result = _deserializer.DeserializeSingle<Male>(body);
`Person` _is_ a reference type, so it is possible. And I don't understand what encapsulating code you're missing that prevents you from writing an integration test. It also resolves the issue of a bad project reference vs duplicating types.

2020-10-02 08:31 UTC, bart-degreed commented on test/UnitTests/UnitTests.csproj
> +    <ProjectReference Include="..\JsonApiDotNetCoreExampleTests\JsonApiDotNetCoreExampleTests.csproj" />
Having the right dependencies is not just to prevent circular references, it is about expressing layered architecture. Tests should not depend on each other.

2020-10-02 08:36 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.AddRangeAsync(person, cat);
Makes sense. So what should be our convention then?
1. Always call dbContext.Add/AddRange and never call dbContext.Animals.Add/AddRange
2. Only call dbContext.AddRange for mixed types, in all other cases use dbContext.Animals.Add/AddRange
3. Anything else?

2020-10-02 08:43 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Content.cs
> +}
I'm not saying the tests should be assigning those properties. But this is about modelling something, not a procedure that contains dead code. To make the model more understandable and available for use, such properties add value. If in the future I wanted to add a test that works on a property, I'd need to invent one first (and possibly break existing tests that never expected the property to exist in the json output).

So the goal should be to expose a model that makes sense to humans and is easy to use. I think that is unrelated to YAGNI, which is about building features that _might_ be needed in the future. Or not, who knows?

2020-10-02 08:44 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +            _testContext;
What other forms of inheritance are you thinking of that make the term ambiguous here?

2020-10-02 08:50 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Animal.cs
> +    }
Defining a model where its hard to imagine sensible properties does not sound like a realistic model. Having a model that humans can relate to improves readability of tests, now and in the future (when adding filters or fields). Do you think it would be good practice to throw-away existing models and tests, so we can replace them with something appropriate at the time we need to add tests for filters? This is so basic, I think we can (and should) get it right initially.

2020-10-02 08:53 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +        }
See https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/833#discussion_r498676811: no longer need to check if posting to the `males` endpoint will return a resource of type `males`, that is basic functionality that is tested elsewhere.

For the `type` of the pet, this is not possible because that would require an `include`.

2020-10-02 08:54 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/ContentPerson.cs
> +    public sealed class ContentPerson
The example you're referring to doesn't apply, because there the properties and tables are named the same. This is similar to `Person Owner` vs `Person Person`. The many-to-many table you're using here links favorites, not just any many-to-many relationships that may exist between persons and content. If that were the case, you'd need to add an extra column that indicates the relationship type. But I don't think JADNC even supports that.

2020-10-02 08:57 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +        }
See https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/833#discussion_r498676811: no longer need to check if posting to the `males` endpoint will return a resource of type `males`, that is basic functionality that is tested elsewhere.

For the `type` of the pet, this is not possible because that would require an `include`.

2020-10-02 09:39 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.AddRangeAsync(person, cat);
I would argue there is no need for a very strict convention here. Different approaches could be more valuable in different scenarios. But if I would have to choose, I think 2. makes sense

2020-10-02 09:39 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +            var cat = new Cat();
Man and Woman: agreed

2020-10-02 09:40 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +            _testContext;
Inheritance of any JADNC component

2020-10-02 09:41 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.ClearTableAsync<Male>();
I think so! I put a Console.Writeline statement in the constructor which occurred as many times as there are tests in this class.

2020-10-02 09:51 UTC, maurei commented on test/UnitTests/UnitTests.csproj
> +    <ProjectReference Include="..\JsonApiDotNetCoreExampleTests\JsonApiDotNetCoreExampleTests.csproj" />
What would be your preferred way of getting rid of the dependency?

2020-10-02 10:06 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/ContentPerson.cs
> +    public sealed class ContentPerson
It's true that it doesn't work with JADNC but it can still be used like that within the context of EF Core. Probably not a very common use-case in combination with JADNC, but it is just to point out that I don't think it is convention to embed the relationship name in the table/class name. Similarly you wouldn't necessarily rename the `Person` table to `Author` just because there is an author to-one relationship between `Article` and `Person`.

One could change the property name to reflect that:
```c#
// in Person.cs
public List<PersonContentItem> PersonFavoriteContentItems { get; set; }
```

But given that there already is a `FavoriteContent` property, I don't think this adds much value to put `Favorite` in this one too.

2020-10-02 16:04 UTC, bart-degreed requested changes

2020-10-02 16:04 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/InheritanceTests.cs
> +                favoriteContent.Should().ContainSingle(h => h is Video);
More readable:

```c#
var contentItems = await dbContext.HumanFavoriteContentItems
    .Where(x => x.Human.Id == man.Id)
    .Select(x => x.ContentItem)
    .ToListAsync();

contentItems.Should().HaveCount(2);
contentItems.Should().ContainSingle(h => h is Book);
contentItems.Should().ContainSingle(h => h is Video);
```

2020-10-02 16:06 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/BaseDeserializer.cs
> +            SetNavigation(resource, attr, relatedId, relatedResourceType);
You're right, I missed that.

2020-10-02 16:08 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +        public async Task Can_create_resource_with_one_to_one_relationship_that_has_inheritance(string type, int index)
I think this is okay for now.

2020-10-02 16:12 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/ContentPerson.cs
> +    public sealed class ContentPerson
We've discussed this offline. The many-to-many table is effectively a relationship and not a data store.

2020-10-02 16:14 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +            _testContext;
My intent was to rename the _folder_ to Inheritance, but the way you've changed it now is probably okay too.

2020-10-02 16:15 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.ClearTableAsync<Male>();
Yes, you're right. We decided offline to do the clearing per test, but have a method that accepts multiple for brevity.

2020-10-02 16:16 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.AddAsync(cat);
I'm still seeing usage of `AddRangeAsync`.

2020-10-02 16:17 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                    .Where(p => p.Id.Equals(int.Parse(responseDocument.SingleData.Id))).FirstAsync();
I'm still seeing unneeded `.Equals` usage in the tests.

2020-10-02 16:17 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                assertPerson.Pet.GetType().Should().Be(cat.GetType());
Sounds good.

2020-10-02 16:18 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +        }
And I'm inferring we don't want to add the include, because then we'd make assumptions on how things work that we don't want to make at the moment, correct?

2020-10-02 16:32 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.AddRangeAsync(person, cat);
Okay, let's pick 2 then. Please update tests to match that convention.

2020-10-02 16:33 UTC, bart-degreed commented on test/UnitTests/UnitTests.csproj
> +    <ProjectReference Include="..\JsonApiDotNetCoreExampleTests\JsonApiDotNetCoreExampleTests.csproj" />
We've discussed this offline and decided to have unit tests define their own models to run against. Since they are usually very specific and intent to hit all kinds of combinations, having humanly understandable models there is less of a concern.

2020-10-02 16:34 UTC, bart-degreed commented on test/UnitTests/Serialization/Client/ResponseDeserializerTests.cs
> +            var result = _deserializer.DeserializeSingle<Male>(body);
I assumed this was testing basic serialization behavior (used by both client and server), but it turns out to be testing client-specific serialization logic. So it makes no sense to write an integration test.

2020-10-02 16:35 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/DocumentTests/LinksWithoutNamespaceTests.cs
> +            var blog = new Blog();
This problem no longer applies and so these changes can be reverted.

2020-10-02 16:38 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +            _testContext;
That wouldn't decrease the length of this particular line, unless you wanted to rename that too

2020-10-02 16:45 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +        }
correct

2020-10-03 17:43 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/InheritanceTests.cs
> +                favoriteContent.Should().ContainSingle(h => h is Video);
Applied

2020-10-03 17:43 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/InheritanceTests.cs
> +                assertMan.HealthInsurance.GetType().Should().Be(insurance.GetType());
Applied

2020-10-03 17:43 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/AppDbContextExtensions.cs
> +        public static async Task ClearTableAsync<TEntity1, TEntity2>(this DbContext dbContext) where TEntity1 : class
Applied

2020-10-03 17:43 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/InheritanceDbContext.cs
> +        public DbSet<Man> Males { get; set; }
Applied

2020-10-03 17:44 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/InheritanceDbContext.cs
> +                .HasKey(pp => new { ContentPersonId = pp.ContentItemId, PersonId = pp.HumanId });
Hadn't updated it, changed it to abbrevation of HumanFavoriteContentItem

2020-10-03 17:44 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/CompanyHealthInsurance.cs
> +    public class CompanyHealthInsurance : HealthInsurance
Applied

2020-10-03 17:44 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/InheritanceDbContext.cs
> +                .ToTable("Persons")
Applied

2020-10-03 17:44 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/FamilyHealthInsurance.cs
> +    public class FamilyHealthInsurance : HealthInsurance
Applied

2020-10-03 17:44 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Human.cs
> +
Applied

2020-10-03 17:45 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Human.cs
> +        public List<HumanFavoriteContentItem> HumanFavoriteContentItems { get; set; }
ICollection suffices for the current tests. Applied.

2020-10-03 17:45 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/Models/Video.cs
> +    public class Video : ContentItem
Applied

2020-10-03 17:45 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.AddRangeAsync(person, cat);
Applied

2020-10-03 17:46 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                await dbContext.AddAsync(cat);
Not anymore

2020-10-03 17:46 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/ResourceInheritanceTests.cs
> +                    .Where(p => p.Id.Equals(int.Parse(responseDocument.SingleData.Id))).FirstAsync();
Not anymore

2020-10-03 17:56 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/InheritanceDbContext.cs
> +                .HasKey(pp => new { ContentPersonId = pp.ContentItemId, PersonId = pp.HumanId });
Also double checked all other parameter names in lambda methods for consistent abbreviations

2020-10-03 17:57 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/InheritanceTests.cs
> +                favoriteContent.Should().ContainSingle(h => h is Video);
This amazes me by the way! EF Core is smart enough to throw in an `Include` under the hood huh?

2020-10-05 10:19 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceInheritance/InheritanceTests.cs
> +                favoriteContent.Should().ContainSingle(h => h is Video);
Yes, due to the select. This is functionally equivalent to an Include, otherwise the select would never work.

2020-10-05 10:24 UTC, bart-degreed approved these changes

2020-10-05 10:24 UTC, merged