Feat/834
json-api-dotnet/JsonApiDotNetCore pull request #847
Opened 2020-09-30 13:26 UTC by maurei

draft

2020-10-01 07:06 UTC, bart-degreed commented
The goal should be to intercept whether `IsRequired` validation executes or not from _outside_ the attribute itself. Because from within the attribute, we cannot access the position in the object graph it is executing for. And we need to know that to implement correct behavior. This PR does not solve that.

Some quick unpolished prototyped code that demonstrates what needs to be done:
```c#
        public void ConfigureMvc()
        {
            _mvcBuilder.AddMvcOptions(options =>
            {
                options.EnableEndpointRouting = true;
                options.Filters.AddService<IAsyncJsonApiExceptionFilter>();
                options.Filters.AddService<IAsyncQueryStringActionFilter>();
                options.Filters.AddService<IAsyncConvertEmptyActionResultFilter>();

                var innerProvider = options.ModelValidatorProviders.First();
                options.ModelValidatorProviders.Clear();
                options.ModelValidatorProviders.Add(new CustomModelValidatorProvider(innerProvider));

                ConfigureMvcOptions?.Invoke(options);
            });

            if (_options.ValidateModelState)
            {
                _mvcBuilder.AddDataAnnotations();
            }
        }

        public class CustomModelValidatorProvider : IModelValidatorProvider
        {
            private readonly IModelValidatorProvider _innerProvider;

            public CustomModelValidatorProvider(IModelValidatorProvider innerProvider)
            {
                _innerProvider = innerProvider;
            }

            // https://github.com/dotnet/aspnetcore/blob/v3.1.4/src/Mvc/Mvc.DataAnnotations/src/DataAnnotationsModelValidatorProvider.cs
            public void CreateValidators(ModelValidatorProviderContext context)
            {
                var meta = context.ModelMetadata;
                var kind = context.ModelMetadata.MetadataKind;

                foreach (ValidatorItem result in context.Results)
                {
                    if (result.ValidatorMetadata is RequiredAttribute requiredAttribute)
                    {
                        result.Validator = new CustomRequiredValidator(requiredAttribute);
                    }
                }

                _innerProvider.CreateValidators(context);
            }
        }

        public class CustomRequiredValidator : IModelValidator
        {
            private readonly RequiredAttribute _requiredAttribute;

            public CustomRequiredValidator(RequiredAttribute requiredAttribute)
            {
                _requiredAttribute = requiredAttribute;
            }

            // https://github.com/dotnet/aspnetcore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.DataAnnotations/src/DataAnnotationsModelValidator.cs
            public IEnumerable<ModelValidationResult> Validate(ModelValidationContext validationContext)
            {
                var metadata = validationContext.ModelMetadata;
                var memberName = metadata.Name;
                var container = validationContext.Container;

                var context = new ValidationContext(
                    instance: container ?? validationContext.Model ?? new object(),
                    serviceProvider: validationContext.ActionContext?.HttpContext?.RequestServices,
                    items: null)
                {
                    DisplayName = metadata.GetDisplayName(),
                    MemberName = memberName
                };

                // TODO: Choose if we want to run or skip required-field-validation, based on request.

                var result = _requiredAttribute.GetValidationResult(validationContext.Model, context);
                if (result != null)
                {
                    return new[]
                    {
                        new ModelValidationResult(memberName, result.ErrorMessage)
                    };
                }

                return Array.Empty<ModelValidationResult>();
            }
        }
```

Let me know if you need me to dive in more or that you'll take it from here.

2020-10-03 12:06 UTC, maurei commented
After extensive discussions and a proper deep dive with @bart-degreed, I came up with an alternative solution.

In the `ValidationVisitor` while recursing through the object model graph there is a property that determines [checks if a certain property should be validated](https://github.com/dotnet/aspnetcore/blob/ca1f9f532f540f16732e8d8b4990fbae1578786b/src/Mvc/Mvc.Core/src/ModelBinding/Validation/ValidationVisitor.cs#L453). This property is a  [IPropertyValidationFilter](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Abstractions/src/ModelBinding/Validation/IPropertyValidationFilter.cs) that lives on `ModelMetadata`. By default this property is not set. It is possible to access the property setter by registering a custom implementation of [IModelMetadataProvider](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/feat/834/src/JsonApiDotNetCore/Configuration/Validation/JsonApiMetaDataProvider.cs). Through there one can assign a custom [PartialPatchValidationFilter](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/feat/834/src/JsonApiDotNetCore/Configuration/Validation/PartialPatchValidationFilter.cs)

Unfortunately, this does not completely do the trick... Apart from the position in the object model graph, we also need access to `JsonApiRequest` and `HttpContextAccessor`, like in the old solution. The callee of this filter (`ValidationVisitor`) does not pass along any context, so this is unavailable.

This can be resolved by having a custom `ObjectModelValidator` that used a slightly adjusted `ValidationVisitor` that takes this into account. This is such a minor adjustment that I think it would make sense for aspnetcore to include this in their internal implementation. I have opened up an issue for that. Meanwhile, we can stick with this solution.

2020-10-05 10:53 UTC, bart-degreed requested changes
Will discuss the rest offline.

2020-10-05 10:53 UTC, bart-degreed commented on src/JsonApiDotNetCore/Serialization/RequestDeserializer.cs
> +
The whole method override can be removed now. And base method can be non-virtual again.

2020-10-05 13:12 UTC, bart-degreed approved these changes

2020-10-05 13:18 UTC, bart-degreed commented
Pushed changes that simplify injection.

2020-10-05 13:57 UTC, merged