Implement POST and DELETE on to-many relationship link
json-api-dotnet/JsonApiDotNetCore pull request #851
Opened 2020-10-04 09:32 UTC by maurei

Closes #353 and #850

2020-10-08 15:51 UTC, bart-degreed requested changes
Holding off further review until clean work has been done.

2020-10-08 15:51 UTC, bart-degreed commented on src/JsonApiDotNetCore/Errors/QueryExecutionException.cs
> +    public sealed class QueryExecutionException : Exception
- This should not be in the Errors namespace (see https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/808)
- The point of having our own exception (instead of reusing `DbUpdateException`) is to separate resource services from EF Core implementation, thus enabling alternative data stores. So the documentation should reflect that.
- The name `QueryExecutionException` is too broad, it is not just any query (read or write) that fails. I'm thinking `DataStoreUpdateException` is more appropriate.

2020-10-08 15:51 UTC, bart-degreed commented on src/JsonApiDotNetCore/Errors/QueryExecutionException.cs
> +        public QueryExecutionException(Exception exception) : base(exception.Message, exception) { }
The point of wrapping exceptions is to create an abstraction, so passing the inner message unmodified does not feel right. Assuming we have no need for callers to pass a specific message explaining what was going on, then we should use a standard text here, such as "Failed to apply changes in the underlying data store.". For those authorized, the call stack contains details on what happened.

2020-10-08 15:51 UTC, bart-degreed commented on src/JsonApiDotNetCore/Repositories/EntityFrameworkCoreRepository.cs
> +                throw new QueryExecutionException(exception);
All except one usage of `_dbContext.SaveChangesAsync()` is wrapped in the same try/catch. Assuming that's a bug, better extract this into a private method.

2020-10-08 15:51 UTC, bart-degreed commented on src/JsonApiDotNetCore/Errors/RelationshipUpdateForbiddenException.cs
> +    /// </summary>
Documentation is incorrect.

The json::api spec reads:
```
A server MUST return 403 Forbidden in response to an unsupported request to update a relationship.
```

So a better title would be: "Unsupported request to update relationship."

But looking at the usage, this exception is always thrown for a more specific scenario, which makes me think the next title is better: "Only to-many relationships can be updated through this endpoint."

And the `{toOneRelationship}` in Detail should be enclosed in single quotes, similar to other exceptions.

And the parameter `toOneRelationship` should be renamed to `relationshipName`. The exception is about to-manies and does not need to know what other kinds of relationships do exist and how they relate to each other.

2020-10-08 15:51 UTC, bart-degreed commented on src/JsonApiDotNetCore/Services/JsonApiResourceService.cs
> +        private readonly struct RelationshipAssignment
Don't use structs, they have pitfalls and are tricky to get right. Only for extreme performance optimizations should they be considered. And don't declare nested types in the middle, but always at the end of the containing type.

2020-10-08 15:51 UTC, bart-degreed commented on src/JsonApiDotNetCore/Services/JsonApiResourceService.cs
> +                    identifiers = ((IReadOnlyCollection<IIdentifiable>) assignment.Value).Select(TypeHelper.GetResourceStringId).ToArray();
This cast fails on any other collection type, which is completely unneeded because you're calling `.Select` on it. Instead cast to `IEnumerable<IIdentifiable>`, if you must cast.

2020-10-08 15:51 UTC, bart-degreed commented on src/JsonApiDotNetCore/TypeHelper.cs
> +        }
This is a confusing method that should not exist. It does not return the StringId of a resource, but calls .ToString() on the typed ID of a resource. Please inline all usages and remove.

2020-10-08 15:51 UTC, bart-degreed commented on src/JsonApiDotNetCore/TypeHelper.cs
> +            if (resource == null) throw new ArgumentNullException(nameof(resource));
This method is internal and should not have a null check. Also the added doc-comment does not add any helpful info so should not be there.

2020-10-08 15:51 UTC, bart-degreed commented on src/JsonApiDotNetCore/TypeHelper.cs
> +        }
This method is used only once, so should be inlined. See earlier remark on how Helpers are an anti-pattern that we should try to avoid.

2020-10-08 15:51 UTC, bart-degreed commented on src/JsonApiDotNetCore/Repositories/DbContextExtensions.cs
> +            {
strange indents

2020-10-08 16:04 UTC, maurei commented on src/JsonApiDotNetCore/Controllers/BaseJsonApiController.cs
> +        public virtual async Task<IActionResult> DeleteRelationshipAsync(TId id, string relationshipName, [FromBody] IReadOnlyCollection<IIdentifiable> removalValues)
I don't think this is an improvement. We're not removing resource identifiers from a relationship. We're removing values from a relationship.

2020-11-06 17:03 UTC, bart-degreed commented
Continued in #874.

2020-11-06 17:03 UTC, closed without merging