Fix OnReturn secondary resource pipeline for HasOne relationships
json-api-dotnet/JsonApiDotNetCore pull request #929
Opened 2021-01-21 08:55 UTC by maurei

Additional fix for #924 that covers the case of HasOne relationships

2021-01-21 13:50 UTC, bart-degreed requested changes

2021-01-21 13:50 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/Acceptance/ResourceDefinitions/ResourceDefinitionTests.cs
> +            var response = await _client.GetAsync(route);
Assertion on http status code is missing.

2021-01-21 13:50 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/Acceptance/ResourceDefinitions/ResourceDefinitionTests.cs
> +            var passport = new Passport(_dbContext) {IsLocked = true};
`passport` can be inlined

2021-01-22 00:24 UTC, woofi7 commented
I've pulled the branch and tested on my side with the project.

When tested it crashes on the call to `OnReturn`.

The var `resources` is of type `List<object>`  which is not `TResource`
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The type 'object' cannot be used as type parameter 'TResource' in the generic type or method 'JsonApiDotNetCore.Hooks.Internal.IOnReturnHookExecutor.OnReturn<TResource>(System.Collections.Generic.IEnumerable<TResource>, JsonApiDotNetCore.Hooks.Internal.Execution.ResourcePipeline)'. There is no implicit reference conversion from 'object' to 'JsonApiDotNetCore.Resources.IIdentifiable'.
  at CallSite.Target
  at System.Dynamic.UpdateDelegates.UpdateAndExecute3
  at JsonApiDotNetCore.Hooks.Internal.ResourceHookExecutorFacade.OnReturnRelationship
    D:\workspace\JsonApiDotNetCore\src\JsonApiDotNetCore\Hooks\Internal\ResourceHookExecutorFacade.cs:131
  at JsonApiDotNetCore.Services.JsonApiResourceService`2+<GetSecondaryAsync>d__11.MoveNext
    D:\workspace\JsonApiDotNetCore\src\JsonApiDotNetCore\Services\JsonApiResourceService.cs:137
```

I have tried with this and it works:
```
if (resourceOrResources is IIdentifiable)
{
    var resources = ToList((dynamic) resourceOrResources);
    object[] array = _resourceHookExecutor.OnReturn(resources, ResourcePipeline.GetRelationship).ToArray();
    return array.SingleOrDefault();
}
```

This do not work, we need to store the result in a var and then do the SingleOrDefault.
`_resourceHookExecutor.OnReturn(resources, ResourcePipeline.GetRelationship).ToArray().SingleOrDefault()`

2021-01-26 21:29 UTC, woofi7 commented
The fix work with the first problem (image loading).

2021-01-27 08:53 UTC, bart-degreed approved these changes

2021-01-27 08:54 UTC, merged