Refactor tests
json-api-dotnet/JsonApiDotNetCore pull request #941
Opened 2021-02-04 16:41 UTC by bart-degreed

Fixes #715. It's probably easiest to review the commit.

With the new infrastructure in place and all integration tests using them, we can now run them in parallel.

Running all tests on my machine (before): 56 sec
Running all tests on my machine (after): 23 sec

That's 60% faster than before!

2021-02-05 07:11 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/RestrictedControllers/HttpReadOnlyTests.cs
> +            responseDocument.Errors[0].Detail.Should().Be("Resource does not support POST requests.");
I think _Endpoint_ instead of _Resource_ is more accurate

2021-02-05 07:13 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/RestrictedControllers/Table.cs
> +
Whitespace inconsistency:
```
{
 // <---
}
```
Also, example models should contain properties

2021-02-05 07:18 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/NamingConventions/KebabCasingTests.cs
> +        public async Task Cannot_create_resource_for_invalid_request_body()
I'm doubting that this test case is relevant in the context of testing custom naming conventions

2021-02-05 07:20 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/NamingConventions/KebabCasingTests.cs
> +        public async Task Cannot_update_resource_for_invalid_attribute()
Same as above, if the goal is checking casing convention of the error document, that should be reflected in the name of the test. On its own testing attribute validation is beyond the scope of custom naming conventions

2021-02-05 07:21 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ObjectAssertionsExtensions.cs
> +        public static void BeApproximately(this ObjectAssertions source, decimal? expected, decimal precision = 0.00000000001M, string because = "",
👍

2021-02-05 07:29 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ExceptionHandling/ExceptionHandlerTests.cs
> +                Code = "X123"
Nitpicking, maybe consider defining a public static property  (eg `ConsumerArticlesController.Checksum`) and define `X` on there, to make it more explicit when how it is defined when if exception is thrown or not

2021-02-05 08:59 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/RestrictedControllers/HttpReadOnlyTests.cs
> +            responseDocument.Errors[0].Detail.Should().Be("Resource does not support POST requests.");
I agree, but that would be a breaking change so I prefer to not do that now. Perhaps we should create a tracking issue with a list of breaks that we want to take in vNext.

2021-02-05 09:02 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/RestrictedControllers/BlockingHttpDeleteController.cs
> +    [DisableQueryString(StandardQueryStringParameters.Sort | StandardQueryStringParameters.Page)]
Not related to this PR, but I don't like the `Standard` piece in the name, I think it is redundant

2021-02-05 09:11 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ObjectAssertionsExtensions.cs
> +        public static void BeApproximately(this ObjectAssertions source, decimal? expected, decimal precision = 0.00000000001M, string because = "",
Took that out later, see `IntegrationTestConfiguration`

2021-02-05 09:15 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/RestrictedControllers/BlockingHttpDeleteController.cs
> +    [DisableQueryString(StandardQueryStringParameters.Sort | StandardQueryStringParameters.Page)]
Let's add that to the list of breaking changes for vNext.

2021-02-05 09:23 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTestConfiguration.cs
> +    internal static class IntegrationTestConfiguration
👍

2021-02-05 09:46 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ControllerActionResults/ActionResultTests.cs
> +            var route = "/toothbrushes/11111111";
Consider defining a public static `ToothbrusherController.NotFoundId` to be explicit on where this `111111` is defined and what triggers which exception. Same for other tests in this suite

2021-02-05 09:48 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ControllerActionResults/Toothbrush.cs
> +    {
MIssing example properties

2021-02-05 10:23 UTC, maurei commented on test/TestBuildingBlocks/RemoteIntegrationTestContext.cs
> +    public class RemoteIntegrationTestContext<TStartup, TDbContext> : BaseIntegrationTestContext<TStartup, TStartup, TDbContext>
Why is it called `Remote`?

2021-02-05 10:23 UTC, maurei commented on test/TestBuildingBlocks/RemoteIntegrationTestContext.cs
> +    /// A test context that creates a new database and server instance before running tests and cleans up afterwards.
XML docs are the same of the base class

2021-02-05 10:30 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceHooks/ResourceHookTests.cs
> +        public async Task Article_is_hidden()
Most of the test names in this document don't functionally describe really well what they are testing. Eg what this test really is about is removing resources in a OnReturn hook. Let me know if you want me to look into that here.

2021-02-05 10:32 UTC, maurei commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/RestrictedControllers/HttpReadOnlyTests.cs
> +            responseDocument.Errors[0].Detail.Should().Be("Resource does not support POST requests.");
Technically breaking yes, but I wonder if there is anything out there that it would break. Either way, putting it on a list like that is fine.

2021-02-05 10:34 UTC, maurei requested changes
Left various comments throughout the commits

2021-02-05 10:56 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/RestrictedControllers/HttpReadOnlyTests.cs
> +            responseDocument.Errors[0].Detail.Should().Be("Resource does not support POST requests.");
Tracked at #944.

2021-02-05 10:57 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/RestrictedControllers/BlockingHttpDeleteController.cs
> +    [DisableQueryString(StandardQueryStringParameters.Sort | StandardQueryStringParameters.Page)]
Tracked at #944.

2021-02-05 11:00 UTC, bart-degreed commented on test/TestBuildingBlocks/RemoteIntegrationTestContext.cs
> +    public class RemoteIntegrationTestContext<TStartup, TDbContext> : BaseIntegrationTestContext<TStartup, TStartup, TDbContext>
Remote as in "Startup and DbContext MUST be defined in the remote API project" instead of in the local tests project itself. I'm open to better names.

2021-02-05 11:01 UTC, bart-degreed commented on test/JsonApiDotNetCoreExampleTests/IntegrationTests/ResourceHooks/ResourceHookTests.cs
> +        public async Task Article_is_hidden()
Its hard for me to say what is being tested, so I left it as-is. Would be great if you can add a before/after test name list here, and I'll adapt.

2021-02-06 01:00 UTC, bart-degreed commented on test/TestBuildingBlocks/RemoteIntegrationTestContext.cs
> +    /// A test context that creates a new database and server instance before running tests and cleans up afterwards.
This file was deleted in a later commit.

2021-02-08 12:54 UTC, bart-degreed commented on test/TestBuildingBlocks/RemoteIntegrationTestContext.cs
> +    public class RemoteIntegrationTestContext<TStartup, TDbContext> : BaseIntegrationTestContext<TStartup, TStartup, TDbContext>
But this object was removed in a later commit.

2021-02-09 09:51 UTC, maurei approved these changes

2021-02-09 09:51 UTC, merged