Make InputFormatters and OutputFormatters implement IApiRequestFormatMetadataProvider
json-api-dotnet/JsonApiDotNetCore pull request #967
Opened 2021-03-11 16:03 UTC by maurei

Input and output formatters should implement `IApiRequestFormatMetadataProvider` for the MVC api explorer to register accurate metadata about what content type these formatters handle.

2021-03-12 09:08 UTC, bart-degreed requested changes

2021-03-12 09:08 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/JsonApiFormatter.cs
> +            return objectType.GetInterface(nameof(IEnumerable)) != null && objectType.GetGenericArguments().First() == _operationContainerType;
I wanted to try why such complex logic is needed, instead of the obvious `typeof(IList<OperationContainer>)`, but there are no tests. Add some tests first, please.

2021-03-12 09:08 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/JsonApiInputFormatter.cs
> +    /// <inheritdoc cref="JsonApiDotNetCore.Middleware.IJsonApiInputFormatter" />
I assume the cref is to disambiguate between the docs on JsonApiFormatter and IJsonApiInputFormatter. We haven't used this before, but perhaps we should start doing that. Does this work correctly in:
- the generated documentation website?
- IntelliSense in IDE when consuming our NuGet?

2021-03-12 09:08 UTC, bart-degreed commented on src/JsonApiDotNetCore/Middleware/JsonApiFormatter.cs
> +        private readonly Type _operationContainerType = typeof(OperationContainer);
static

2021-03-18 10:57 UTC, maurei commented
superseded by #969 and #972

2021-03-18 10:57 UTC, closed without merging