Test controller provider
json-api-dotnet/JsonApiDotNetCore pull request #969
Opened 2021-03-17 11:06 UTC by maurei

Introduces a mechanism to explicitly register only the controllers required for a particular test suite, rather than always registering all controllers from the entire test assembly.

2021-03-17 21:26 UTC, bart-degreed requested changes
Looking good overall, few remarks.

2021-03-17 21:26 UTC, bart-degreed commented on test/TestBuildingBlocks/BaseIntegrationTestContext.cs
> +        public void AddController<TController>()
I'd like this renamed to `RegisterController` or `UseController`, because it is a method on the test context. If it was an (extension) method on `IServiceCollection`, `AddController` would be appropriate.

2021-03-17 21:26 UTC, bart-degreed commented on test/TestBuildingBlocks/BaseIntegrationTestContext.cs
> +                services.UseControllers(_testControllerProvider);
This should be called after `_beforeServicesConfiguration?.Invoke(services);`.

2021-03-17 21:26 UTC, bart-degreed commented on test/TestBuildingBlocks/ServiceCollectionExtensions.cs
> +        public static void UseControllers(this IServiceCollection services, TestControllerProvider provider)
This should be split into `ClearControllers` and `AddControllers` methods, which are sequentially called from test context. Alternatively, rename to `ReplaceControllers`.

2021-03-17 21:26 UTC, bart-degreed commented on test/TestBuildingBlocks/TestControllerProvider.cs
> +        private readonly IList<Type> _allowedControllerTypes = new List<Type>();
I think this should be a `HashSet` too. And please add a line break, to separate fields from properties.

2021-03-18 09:33 UTC, maurei commented on src/JsonApiDotNetCore/Middleware/HeaderConstants.cs
> +    [PublicAPI]
The CI build failed on it earlier, see https://ci.appveyor.com/project/jaredcnance/jsonapidotnetcore/builds/38266703

2021-03-18 10:32 UTC, bart-degreed approved these changes

2021-03-18 10:33 UTC, merged